### ISSUE TITLE
YTKNetwork 兼容iOS最低版本是多少？

### ISSUE THREAD

**Issue by ilklatte** [yuantiku/YTKNetwork#1]
YTKNetwork最低适配的iOS系统版本是由AFNetworking决定的么？

**Comment by PanDaDemo** [comment]
设置了cacheTimeInSeconds ，做了Bapi loadCacheWithError:nil 判断，ios11在请求接口数据后断网杀死app，进入app 可以读取数据。但是ios10.3.3版手机 却找不到fileManager fileExistsAtPath:path isDirectory:nil  路径 读取不到数据
