### ISSUE TITLE
请开放一个接口用于自定义YTKNetworkAgent下_manager的responseSerializer

### ISSUE THREAD

**Issue by shiqyn** [yuantiku/YTKNetwork#100]
我想设置AFHTTPRequestOperationManager的responseSerializer，如下：

AFJSONResponseSerializer *jsonReponseSerializer = [AFJSONResponseSerializer serializer]; 
// This will make the AFJSONResponseSerializer accept any content type
jsonReponseSerializer.acceptableContentTypes = nil;
manager.responseSerializer = jsonReponseSerializer;

请开放一个接口，谢谢！！！

**Comment by maojj** [comment]
YTKBaseRequest 子类重载如下方法即可
```
- (YTKRequestSerializerType)requestSerializerType {
    return YTKRequestSerializerTypeJSON;
}
```
