### ISSUE TITLE
取消请求

### ISSUE THREAD

**Issue by wLeiX** [yuantiku/YTKNetwork#102]
在控制器里面开始一个请求，当pop控制器后有什么好的办法取消请求？如果我在block里面用self了，退出的话控制器不能销毁，

**Comment by maojj** [comment]
``` YTKBaseRequest ``` 有个 ``` stop ``` 方法
```
[myRequest stop];
```

**Comment by albertjson** [comment]
我采用的是AFNetworking，对于这种处理就是controller中有个管理task的数组，当页面从页面移除的时候
取消请求：
- (void)viewWillDisappear:(BOOL)animated
{
    [super viewWillDisappear:animated];    
    if ([self isMovingFromParentViewController]) {
        for (NSURLSessionDataTask * task in _taskArray) {
            if (task.state==NSURLSessionTaskStateRunning) {
                [task cancel];
            }
        }
    }
}
