### ISSUE TITLE
同一个Request，修改参数后多次请求，返回了cachejson问题

### ISSUE THREAD

**Issue by shendy1991** [yuantiku/YTKNetwork#106]
获取消息内容，需要进行分页获取，所以设置了page 这个参数，声明了一个YTKRequest 子类，然后加了page 这个参数，每次请求，则修改page数，获取不同的分页的信息，会出现一个bug

1.开启cacheTimeInSeconds
 (NSInteger)cacheTimeInSeconds {
    return 200;
}
2.获取page=1 的信息成功后，此时返回为最新的page=1的数据
3.如果此时再次刷新获取page=1的数据，则会返回cachejson里面数据
4.然后将page改为page=2请求数据，依旧会返回page=1 的情况的cachejson里面内容

造成这个原因是：
当修改request类里面参数，请求时间在大于cacheTimeInSeconds时间请求时，虽然重新连接服务器获取了最新的信息，
int seconds = [self cacheFileDuration:path];
    if (seconds < 0 || seconds > [self cacheTimeInSeconds]) {
        [super start];
        return;
    }

程序会从这里返回，因为调用了同一个request，而此时request里面的cachejson依旧保留着上次请求的cachejson内容没有被清除，以至于在调用
(id)responseJSONObject {
    if (_cacheJson) {
        return _cacheJson;
    } else {
        return [super responseJSONObject];
    }
}
返回了cachejson内容。

解决办法：
在YTKRequest 的start方法里面前面重新初始化
_cacheJson = nil;
_dataFromCache = NO;
将cachejson 清空下，重新获取cache文件即可

不知道这样子是否和你们当初设想的有出入，求解答

**Comment by jaybowong** [comment]
#60

**Comment by maojj** [comment]
现在的做法可以在下一页请求重新发一个 request， 不复用原请求。  缓存设计 @lancy 解答下。

**Comment by lancy** [comment]
嗯，缓存这一块是 @tangqiaoboy 设计的。

按原本设计思路来看，是不允许对一个 API 多次修改的，甚至可以认为，推荐的使用方法是在初始化的时候，就把 API 一次定型的。而每次调用 start 或 cacheJson 之后，都应当视为这个 API 实例已经被使用过，再次使用的时候，就应该重新发一个。

这样设计的思路，应该是就是为了避免多次复用导致的副作用。
