### ISSUE TITLE
建议添加模型映射对应的方法

### ISSUE THREAD

**Issue by AliThink** [yuantiku/YTKNetwork#109]
首先感谢YTKNetwork带来的巨大便利，同时在使用过程中发现往往模型映射的部分不能一块封装到对应的Api类中，而需要单独在request发送成功之后单独编写，建议在基类中添加对应的模型映射方法，然后在request中添加对应获取映射完成的数据集合的属性，从而避免了单独再封装一个模型映射层的麻烦^_^

**Comment by maojj** [comment]
不是很明白具体怎么做？ 给个例子？

**Comment by AliThink** [comment]
感谢你的回复，其实就类似现有的jsonValidator的方法的处理位置，验证完了之后，再添加一个类似的方法做模型映射不知道可行吗？将映射成Model的数据集合添加到request中的类似requestModel的属性中，这样Api与模型映射就可以在同一个类中编写，那么controller在调用的时候就可以直接取出映射之后的数据集合了

**Comment by maojj** [comment]
这个我们实际产品中其实有的，这个事情其实有不少解决方案，我们用的是 Mantle 来处理这个事情，Mantle 其实做的很好了，各种奇葩需求基本都能满足（比如 string 转 枚举之类的）。我们觉得这块不应该放到 YTKNetwork 中，各自喜欢什么就用什么就好了。

**Comment by AliThink** [comment]
你好，其实不是把类似mantle的这种模型映射封装在YTKNetwork里面，而是添加一个可以防止模型映射代码的入口方法^_^
