### ISSUE TITLE
如何获取设备的一个唯一标示？

### ISSUE THREAD

**Issue by huangbaoyu** [yuantiku/YTKNetwork#113]
暂时用了一个方案， 但测试后 发现以下问题：
1 开发证书和企业打包证书 导致 唯一号变化
2 同一台pad 安装不同的app变化

请教各位 有什么 更好的方案么？ 非常感谢

#import "BSUDIDTools.h"
#import "UICKeyChainStore.h"
#import <Security/Security.h>
#include <sys/socket.h>
#include <sys/sysctl.h>
#include <net/if.h>
#include <net/if_dl.h>

@implementation BSUDIDTools

+ (NSString *)UDID {
    NSString *udid = [BSUDIDTools getUDIDFromKeyChain];
    if (!udid) {
        NSString *sysVersion = [UIDevice currentDevice].systemVersion;
        CGFloat version = [sysVersion floatValue];
        
        if (version >= 7.0) {
            udid = [BSUDIDTools UDID_iOS7];
        } else if (version >= 2.0) {
            udid = [BSUDIDTools UDID_iOS6];
        }
        
        [BSUDIDTools setUDIDToKeyChain:udid];
    }
    return udid;
}

+ (NSString *)getUDIDFromKeyChain {
    return [UICKeyChainStore stringForKey:@"::bs::device::identifier" service:@"Device"];
}

+ (void)setUDIDToKeyChain:(NSString *)udid {
    [UICKeyChainStore setString:udid forKey:@"::bs::device::identifier" service:@"Device"];
}

+ (NSString *)UDID_iOS6 {
    return [BSUDIDTools getMacAddress];
}

+ (NSString *)UDID_iOS7 {
    return [[UIDevice currentDevice].identifierForVendor UUIDString];
}

+ (NSString *)getMacAddress {
    int                 mgmtInfoBase[6];
    char                *msgBuffer = NULL;
    size_t              length;
    unsigned char       macAddress[6];
    struct if_msghdr    *interfaceMsgStruct;
    struct sockaddr_dl  *socketStruct;
    NSString            *errorFlag = nil;
    
    // Setup the management Information Base (mib)
    mgmtInfoBase[0] = CTL_NET;        // Request network subsystem
    mgmtInfoBase[1] = AF_ROUTE;       // Routing table info
    mgmtInfoBase[2] = 0;
    mgmtInfoBase[3] = AF_LINK;        // Request link layer information
    mgmtInfoBase[4] = NET_RT_IFLIST;  // Request all configured interfaces
    
    // With all configured interfaces requested, get handle index
    if ((mgmtInfoBase[5] = if_nametoindex("en0")) == 0)
        errorFlag = @"if_nametoindex failure";
    else
    {
        // Get the size of the data available (store in len)
        if (sysctl(mgmtInfoBase, 6, NULL, &length, NULL, 0) < 0)
            errorFlag = @"sysctl mgmtInfoBase failure";
        else
        {
            // Alloc memory based on above call
            if ((msgBuffer = malloc(length)) == NULL)
                errorFlag = @"buffer allocation failure";
            else
            {
                // Get system information, store in buffer
                if (sysctl(mgmtInfoBase, 6, msgBuffer, &length, NULL, 0) < 0)
                    errorFlag = @"sysctl msgBuffer failure";
            }
        }
    }
    
    // Befor going any further...
    if (errorFlag != NULL)
    {
        NSLog(@"Error: %@", errorFlag);
        if (msgBuffer) {
            free(msgBuffer);
        }
        
        return errorFlag;
    }
    
    // Map msgbuffer to interface message structure
    interfaceMsgStruct = (struct if_msghdr *) msgBuffer;
    
    // Map to link-level socket structure
    socketStruct = (struct sockaddr_dl *) (interfaceMsgStruct + 1);
    
    // Copy link layer address data in socket structure to an array
    memcpy(&macAddress, socketStruct->sdl_data + socketStruct->sdl_nlen, 6);
    
    // Read from char array into a string object, into traditional Mac address format
    NSString *macAddressString = [NSString stringWithFormat:@"%02X:%02X:%02X:%02X:%02X:%02X",
                                  macAddress[0], macAddress[1], macAddress[2],
                                  macAddress[3], macAddress[4], macAddress[5]];
    NSLog(@"Mac Address: %@", macAddressString);
    
    // Release the buffer memory
    free(msgBuffer);
    
    return macAddressString;
}

@end

**Comment by maojj** [comment]
@huangbaoyu   这个不在 YTKNetwork 的范围内呀，可以去 stackoverflow 看看。

**Comment by huangbaoyu** [comment]
Thank! 是的 ， 这里都是大神  所以 想请教下 ，一直没找到到合适的方案， 我们的产品 还必须得  用到唯一号， 现在的 处理方案 还不是太安全。还是非常感谢，我的项目一直在用YTKNetwork , 真心 感谢
