### ISSUE TITLE
找到了和 STNetTaskQueue 出奇相似的东西

### ISSUE THREAD

**Issue by kevin0571** [yuantiku/YTKNetwork#114]
Hi,
[STNetTaskQueue](https://github.com/kevin0571/STNetTaskQueue) 的基本思想和 YTKNetwork 基本一致，想了解下YTKNetwork有考虑过提供自动根据request里的property生成 request params 的功能吗？

**Comment by jaybowong** [comment]
@kevin0571 #101

**Comment by lancy** [comment]
嗯，暂时没有这样的想法，这样的需求主要用于解决的问题场景是？

**Comment by kevin0571** [comment]
@lancy 省去写 @{ @"param_a": self.paramA, @"param_b": self.paramB } 的累赘代码。

**Comment by lancy** [comment]
如 #101 @maojj 同学描述的，常常会有某些属性不想作为参数传递；另外参数也很有可能常常是一个复杂的数据结构；

类似的需求可以使用相关的 ModelToJSON 库代替。

所以不打算支持这样的功能。
