### ISSUE TITLE
关于获取缓存没有反应

### ISSUE THREAD

**Issue by SosonHuang** [yuantiku/YTKNetwork#116]
GetUserInfoApi *api = [[GetUserInfoApi alloc] initWithUserId:userId];
    if ([api cacheJson]) {
        NSDictionary *json = [api cacheJson];
        NSLog(@"json = %@", json);
        // show cached data
    }
    [api startWithCompletionBlockWithSuccess:^(YTKBaseRequest *request) {
        NSLog(@"update ui");
    } failure:^(YTKBaseRequest *request) {
        NSLog(@"failed");
    }];

如上代码，在第一次进入的时候应该会执行更新ui，但是在我切换其他界面再回来先调试是否获取得到缓存数据，发现
  if ([api cacheJson]) {
        NSDictionary *json = [api cacheJson];
        NSLog(@"json = %@", json);
        // show cached data
    }
这里进不来，打印不到json的数据！

**Comment by xserver** [comment]
请确保开启了缓存

**Comment by lancy** [comment]
请确保设置了缓存时间
