### ISSUE TITLE
BatchRequest 无法发送单个请求了？

### ISSUE THREAD

**Issue by DougMaster** [yuantiku/YTKNetwork#117]
猿题库童鞋你好，
我前几天更新了一版最新YTKNetwork，发现所有的BatchRequest请求都无效了（发动单个请求也是用的BatchRequest），服务器接收不到请求。改用ChainRequest就可以收到服务器返回数据，请问，最近几个月有没有对BatchRequest做修改，或者这种发生这种问题的原因是什么？ 
感谢

**Comment by tangqiaoboy** [comment]
其实你可以自己看看文件的改动log吧，我记得最近 BatchRequest 加了一个锁，保证在多线程下使用没有线程安全问题。应该不会有影响。
