### ISSUE TITLE
ReadMe中说的“正在加载的HUD插件”在哪里？

### ISSUE THREAD

**Issue by Jerry-Wang-Developer** [yuantiku/YTKNetwork#12]
我看了YTKNetwork的功能介绍里面有一条：
定义了一套插件机制，可以很方便地为 YTKNetwork 增加功能。猿题库官方现在提供了一个插件，可以在某些网络请求发起时，在界面上显示"正在加载"的 HUD。
但是在代码中并没有找到可以调用的接口，可以告诉我接口在哪里吗？

**Comment by huang5556019** [comment]
这个https://gist.github.com/lancy/4982d0f6f708133cc8e1# 打不开了....

**Comment by huangbaoyu** [comment]
期待 这个 功能  ／。。。。。

**Comment by maojj** [comment]
可以打开呢
