### ISSUE TITLE
插件机制?   各种 网络错误的报错?  网络状态的检查?

### ISSUE THREAD

**Issue by wjmwjmwb** [yuantiku/YTKNetwork#120]
定义了一套插件机制，可以很方便地为 YTKNetwork 增加功能。猿题库官方现在提供了一个插件，可以在某些网络请求发起时，在界面上显示"正在加载"的 HUD。没有找到这个

各种 网络错误的报错?  网络状态的检查?  
如果这些功能 都有    ....希望在教程中,写明.谢谢猿题库..

**Comment by lancy** [comment]
https://gist.github.com/lancy/4982d0f6f708133cc8e1

**Comment by Adrift001** [comment]
怎么用都没写,用个JB呐,这个库是你们用来蹭KPI的吧?
