### ISSUE TITLE
JSON数据里面的中文显示成了???

### ISSUE THREAD

**Issue by cuiwang** [yuantiku/YTKNetwork#121]
JSON数据里面的中文显示成了???,并且只能在request.responseString里面看到.request.responseJSONObject显示为nil.
  部分接口返回的JSON会这样,而且只有中文有问题.
  临时解决办法:
        NSData *jsonData = [request.responseString dataUsingEncoding:NSUTF8StringEncoding];
        NSDictionary *object = [NSJSONSerialization JSONObjectWithData:jsonData options:0 error:nil];

**Comment by lancy** [comment]
responseJSONObject是使用AFNetworking封装的接口，建议检查服务器返回Header里面的ContentType是否是JSON
