### ISSUE TITLE
YTKNetwork是否支持同步请求?

### ISSUE THREAD

**Issue by xwgit2971** [yuantiku/YTKNetwork#124]
YTKBaseRequest类中的start和startWithCompletionBlockWithSuccess:failure:都是异步请求, 如何同步请求呢?

**Comment by ivanyang1984** [comment]
AFNetworking 里 有的 他就有。。但是我扫了下 YTK 的代码 貌似我没找到同步调用。因为这类CASE 比较少。。。所以建议直接使用  nsoperationqueue自己封装一下  
[opq addOperations: op waitUntilFinished: YES];
