### ISSUE TITLE
YTKNetwork扩展支持自签名证书SSL通信

### ISSUE THREAD

**Issue by violetlige** [yuantiku/YTKNetwork#125]
首先YTKNetwork基于AFNetworking是原生支持SSL连接的，当然前提是你使用的SSL通信证书是被Apple信任的。不过由于大部分的标准CA机构所颁发证书价格昂贵或是其他一些原因（比如我们本身就是一个CA机构去用别人证书好像有点....）想使用自签名证书来进行SSL连接，这个时候就发现YTKNetwork由于没有支持对AFNetworking的AFSecurityPolicy模块扩展导致实现起来比较麻烦。
   因为现在Apple都建议使用SSL连接来通信，原来是在调研系统支持自签名SSL，接着又看AFNetworking对自签名SSL的支持，之后又机缘巧合之下看到YTKNetowork，觉得这种每种请求都作为一个类来实现的设计很棒，然后在实际测试时发现对这种自签名SSL连接扩展性不好，就自己改动了下做了对自签名证书SSL通信的扩展。当然由于自己水平有限、GitHub不熟悉、代码风格等种种原因没有选择Commit于是在这里贴出来仅给大家一个参考。
   首先在YTKBaseRequest.h定义如下方法
/// 是否使用自定义SSL连接安全证书
- (BOOL)useCustomSecurityCertificate;

/// 是否验证访问域名与证书CN指定域名一致
- (BOOL)validatesDomainName;

/// 是否校验完整证书链
- (BOOL)validatesCertificateChain;

/// SSL连接验证方式
- (AFSSLPinningMode)pinningMode;

/// SSL连接自定义安全证书
- (NSArray *)customSecurityCertificates;

  之后在 YTKBaseRequest.m中做出default实现：

//注释都是为了大家便于理解，为了保持代码风格最好.m中注释都删掉
//默认不使用自签名证书
- (BOOL)useCustomSecurityCertificate {
    return NO;
}

//默认不校验访问域名与证书CN指定域名一致，一般自签名证书不会做这个校验
- (BOOL)validatesDomainName {
    return NO;
}

//默认不校验完整证书链
- (BOOL)validatesCertificateChain {
    return NO;
}

//返回自签名证书验证方式，在AFNetworking的AFSecurityPolicy.h可以找到对应定义。
//AFSSLPinningModeNone表示要使用Apple自己的可信证书验证，自签名不会选这个
//AFSSLPinningModePublicKey表示只校验公钥是否一致
//AFSSLPinningModeCertificate表示校验证书是否一致，也会校验证书时效等信息。
//个人觉得默认校验证书及时效比较合理
- (AFSSLPinningMode)pinningMode {
    return AFSSLPinningModeCertificate;
}

//返回你自己的自签名证书，如果你选择校验完整证书链（validatesCertificateChain返回YES）这里需要返回完整的证书链结构
- (NSArray *)customSecurityCertificates {
    return nil;
}

    接着需要在YTKNetworkConfig.h做对应的扩展:
    这里在YTKNetworkConfig做扩展主要是因为一般的公司业务SSL连接都是同一套证书，所以这里配置好以后不用每个请求都配置一遍也符合YTKNetwork的设计。
//这里大家分别添加到属性和函数对应位置不要写到一块

@property (strong, nonatomic, readonly) NSArray *customSecurityCertificates;
- (void)addCustomSecurityCertificate:(id)certificate;

   在YTKNetworkConfig.m中实现如下：
//这里仅仅贴出相关代码，大家自行参照实现即可。

@implementation YTKNetworkConfig {
    NSMutableArray *_urlFilters;
    NSMutableArray *_cacheDirPathFilters;
    NSMutableArray *_customSecurityCertificates;
}
- (id)init {
    self = [super init];
    if (self) {
        _urlFilters = [NSMutableArray array];
        _cacheDirPathFilters = [NSMutableArray array];
        _customSecurityCertificates = [NSMutableArray array];
    }
    return self;
}
- (void)addCustomSecurityCertificate:(id)certificate {
    [_customSecurityCertificates addObject:certificate];
}

- (NSArray *)customSecurityCertificates {
    return [_customSecurityCertificates copy];
}

然后需要在YTKNetworkAgent.m中做出实现（同样注释仅为当前说明，为保持代码风格具体使用最好删掉）：
- (void)setRequestSecurityPolicy:(YTKBaseRequest *)request  {
    if ([request useCustomSecurityCertificate])  {
        NSArray *customSecurityCertificates = nil;
        if ([request customSecurityCertificates].count > 0) {
            customSecurityCertificates = [request customSecurityCertificates];
        } else {
            customSecurityCertificates = [_config customSecurityCertificates];
        }
        //这里就是使用请求配置的参数生成新的安全策略
       //但_manager是一个全局配置，配置后其他请求也会使用同样策略
        AFSecurityPolicy *securityPolicy = [AFSecurityPolicy policyWithPinningMode:request.pinningMode];
        [securityPolicy setAllowInvalidCertificates:YES];
        [securityPolicy setValidatesCertificateChain:request.validatesCertificateChain];
        [securityPolicy setValidatesDomainName:request.validatesDomainName];
        [securityPolicy setPinnedCertificates:customSecurityCertificates];
        
        _manager.securityPolicy = securityPolicy;
    } else {
      //这里_manager是一个全局配置，如果请求不想使用自签名SSL连接必须更新策略
        _manager.securityPolicy = [AFSecurityPolicy defaultPolicy];
    }
}
//然
后把这个函数添加到- (void)addRequest:(YTKBaseRequest *)request这个函数中
//我添加的位置是：
<img width="974" alt="ssl" src="https://cloud.githubusercontent.com/assets/9440781/11290012/50b12c7a-8f6d-11e5-9705-49bb56f1dab0.png">

最后发一个我自己的测试例子：
//需要自己定义一个基于YTKRequest的类，然后使用下面代码
//这个证书是我们公司邮件通信证书，大家可以访问https://webmail.cfca.com.cn/这个网址来做验证
#define CFCA_BASE64_CERTIFICATE @"MIIE0jCCA7qgAwIBAgIGAJKL48/8MA0GCSqGSIb3DQEBBQUAMFMxCzAJBgNVBAYTAkNOMTAwLgYDVQQKDCdDaGluYSBGaW5hbmNpYWwgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxEjAQBgNVBAMMCUNGQ0EgT0NBMjAeFw0xMzExMDEwMjQ2MjdaFw0xNjEwMzAwODE1NDlaMIGJMQswCQYDVQQGEwJDTjEQMA4GA1UECAwHQmVpamluZzEQMA4GA1UEBwwHQmVpamluZzEwMC4GA1UECgwnQ2hpbmEgRmluYW5jaWFsIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MQwwCgYDVQQLDANTU0wxFjAUBgNVBAMMDSouY2ZjYS5jb20uY24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDC8vn0SlV7O674GLtQdBMmWCaIRao445gLhE5ONXnpHhfAs1UPtjimiS+TJQCcmk2n0eVwtd2k/TXhCSKu2VeSw8nEdkIodyJUQnrithqOe0E8bQyZa9RcYrl8StXUUXsgB0IVcVfJjaBesjhLMqHRCHR97GhXedFV4yF1tSq1Qed4MiFz/W2mtSHT3femjrFEKOG/QxFA98p2a4d1bO3KsopkDlVN4oT25eJSsi5fj3n7wJVeT7p9c/6hHkRjjBsYHPC4ZMUhd8XBsb9qqMrIByHER249nHsENKVqT84nBK6kwN7YLfwxfdQWtl8jIZQEOFqng+jS/uFW30r765IJAgMBAAGjggFzMIIBbzBtBggrBgEFBQcBAQRhMF8wKAYIKwYBBQUHMAGGHGh0dHA6Ly9vY3NwLmNmY2EuY29tLmNuL29jc3AwMwYIKwYBBQUHMAKGJ2h0dHA6Ly9ndGMuY2ZjYS5jb20uY24vZ3RvY2EvZ3RvY2EyLmNlcjAfBgNVHSMEGDAWgBS3VoHCtHvavB4VcOFAX3X9nUXaGDAMBgNVHRMEBTADAQEAMEgGA1UdIARBMD8wPQYIYIEchu8qAgEwMTAvBggrBgEFBQcCARYjaHR0cDovL3d3dy5jZmNhLmNvbS5jbi91cy91cy0xMS5odG0wOgYDVR0fBDMwMTAvoC2gK4YpaHR0cDovL2NybC5jZmNhLmNvbS5jbi9ndG9jYS9SU0EvY3JsMS5jcmwwCwYDVR0PBAQDAgOoMB0GA1UdDgQWBBR3rdhCXCwiiUZ0MB4GM1E/1kqvNzAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDQYJKoZIhvcNAQEFBQADggEBAIJD34dSRz0m/04rqbk8m9/0nHG3MOLFRNgs/n6edvdKiH53MjovBNSdsYweklt5Ghk9ODpqLisKi0qrtLt9Uqv8MLDC0pPpELvGIT0UZeqCLj3VtrZsLTuhl7DZGl094myRp1CL1roct0eDYywWCuOByPfRMnj2+EfxJSO0ZHpgOVYkay3voHozmQlrXPZ3ojZ1CdFYGV9J9Afmpo1n1wV4BgYf2vzkWQzDNgFHQpsl8mSrMIbUSvHAzcTzxs6G2g9+Nsi+grNnrKdgYSyz/+tS/68Trdrh2JMs7YG5nPDeH5Uuce6bWZaN2g2amH3Df8qBSEqMIGO9RVjvi0yHSRo="

- (BOOL)useCustomSecurityCertificate {
    return YES;
}

- (NSArray *)customSecurityCertificates {
    NSData *cert = [[NSData alloc] initWithBase64EncodedString:CFCA_BASE64_CERTIFICATE options:0];
    return @[cert];
}

最后我从事iOS开发大概一年半（10年参加工作，去年转型iOS），之前都是在GitHub上做伸手党这是第一次提交个人实现希望能帮助到大家。最后不知道是不是为了之后扩展，我个人觉得YTKChainRequestAgent和YTKBatchRequestAgent这俩类存在感有点低....

**Comment by violetlige** [comment]
不太熟悉GitHub这个编辑器的用法，各种回车换行都被改掉了导致和原代码风格不太一致，大家凑合看吧，具体实现还是要适配别人的代码风格。

**Comment by maojj** [comment]
issue96

**Comment by maojj** [comment]
#96  看看这样满足你需求不，  通过 manager 设置 securityPolicy
