### ISSUE TITLE
这里是不是要把当前BatchRequest 从BatchRequestAgent 移除掉呢？

### ISSUE THREAD

**Issue by lsb332** [yuantiku/YTKNetwork#126]
- (void)requestFinished:(YTKRequest *)request {
    _finishedCount++;
    if (_finishedCount == _requestArray.count) {
        [self toggleAccessoriesWillStopCallBack];
        if ([_delegate respondsToSelector:@selector(batchRequestFinished:)]) {
            [_delegate batchRequestFinished:self];
        }
        if (_successCompletionBlock) {
            _successCompletionBlock(self);
        }
        [self clearCompletionBlock];
        [self toggleAccessoriesDidStopCallBack];
     // 在这个地方是不是要从BatchRequestAgent 中移除self 呢？
    }
}

**Comment by lancy** [comment]
同 #139 目测是Bug
