### ISSUE TITLE
关于断点续传相关问题。

### ISSUE THREAD

**Issue by samonkey-liudezhi** [yuantiku/YTKNetwork#127]
1、是否支持后台下载？
2、iOS9锁屏自动断掉下载这个问题有解决方案么？
3、每次重新启动自动换路径这个问题什么原因？
后学末进，恳请解惑。

**Comment by Au12th0psav** [comment]
+1

**Comment by lancy** [comment]
1. 目前不支持
2. 目前没有类似需求，所以还没有打算支持
3. 不清楚你具体指什么问题？

**Comment by xilin** [comment]
@samonkey-liudezhi 我猜你说的是模拟器里你每次用cmd+r运行的时候路径变化吧？真机不会有这个问题
