### ISSUE TITLE
关于API 版本号的问题

### ISSUE THREAD

**Issue by ivanyang1984** [yuantiku/YTKNetwork#128]
请问一下 目前猿题库 是  客户端决定 我要调某个接口的 相应版本号的实现， 还是客户端直接调接口名字，由服务端帮忙分配最佳可用版本？  比如在淘宝 是 API:mtop.taobao.api  version:3.0 (在服务端这个api 有多个版本的实现 1.0 2.0 3.0 2.0-snapshot)

**Comment by lancy** [comment]
我们目前是客户端决定调用的接口版本号。
