### ISSUE TITLE
不支持use_frameworks!

### ISSUE THREAD

**Issue by mdsb100** [yuantiku/YTKNetwork#129]
文件YTKBaseRequest.h这样依赖
```
#import "AFNetworking.h"
#import "AFDownloadRequestOperation.h"
```
不支持cocoapods use_frameworks!

是不是应该改成 <> 这种形式啊？？？

**Comment by wdlgame** [comment]
在Swift中  cocoapods 使用 use_frameworks! 无法引用，编译不过，只能直接把文件拖到项目中用。不知什么时候解决。

**Comment by maojj** [comment]
依赖的 AFDownloadRequestOperation  没有解决 use_frameworks，所以 YTKNetwork 也没法解决。
忧伤的是 AFDownloadRequestOperation 不再维护了，推荐用 NSURLSession
https://github.com/steipete/AFDownloadRequestOperation

**Comment by maojj** [comment]
改用 前向申明， 1.2.0 fixed

**Comment by Huang-Libo** [comment]
@maojj 可以用use_frameworks! 了？
