### ISSUE TITLE
创建继承自YTKRequest的类在头文件自动导入的头文件#import <YTKNetwork/YTKNetwork.h> not found

### ISSUE THREAD

**Issue by lianghuiyuan** [yuantiku/YTKNetwork#130]
通过"pod ' YTKNetwork' "安装的YTKNetwork后，创建一个继承自YTKRequest的类的时候头文件会自动#import <YTKNetwork/YTKNetwork.h>，但是YTKNetwork里面是并没有YTKNetwork.h这个头文件的。所以编译的时候会报错“YTKNetwork/YTKNetwork.h” file not found. 不知道大家是否有相同的问题？比如我自己建立的一个 SignUpApi类的头文件:

``` Objective-C
#import <YTKNetwork/YTKNetwork.h>

@interface SignUpApi : YTKRequest

@end

```
能否避免自动导入“YTKNetwork/YTKNetwork.h”这个错误文件呢？正确应该是
``` Objective-C
#import <YTKRequest.h>
```

**Comment by wjmwjmwb** [comment]
同问

**Comment by Huang-Libo** [comment]
我每次都自己改的

**Comment by maojj** [comment]
1.2.0 fixed

**Comment by Huang-Libo** [comment]
@maojj fix后我得马上升级，😄

**Comment by Huang-Libo** [comment]
@maojj 我用pod升级到1.2.0后还是导入的#import <YTKNetwork/YTKNetwork.h>，不是预期的#import <YTKRequest.h>

**Comment by maojj** [comment]
用pod 预期就是 
```
#import <YTKNetwork/YTKNetwork.h>
```

原来是缺  YTKNetwork.h 这个文件，已经添加上了， 这个文件里面 import 了必要的文件。
