### ISSUE TITLE
acceptableContentTypes

### ISSUE THREAD

**Issue by zhanghaoios** [yuantiku/YTKNetwork#131]
YTKBaseRequest.h可否写一个acceptableContentTypes的方法用来配置这个属性，我发现没有配置的覆盖方法，还是我没找到啊巧哥，希望回复下。
.acceptableContentTypes = [NSSet setWithObjects:@"text/plain", @"application/json", @"text/json", @"text/javascript", @"text/html", @"multipart/form-data", nil];

**Comment by zhanghaoios** [comment]
acceptableContentTypes

**Comment by Sunnyyoung** [comment]
@zhanghaoios 
```objc
[[YTKNetworkAgent sharedInstance] setValue:[NSSet setWithObjects:@"application/json", @"text/plain", @"text/javascript", @"text/json",@"text/html",@"text/css", nil]
                                    forKeyPath:@"_manager.responseSerializer.acceptableContentTypes"];
```

用KVC即可

**Comment by xilin** [comment]
用KVC虽然能解决问题但是还是有点暴力了
希望能开放出来
有些第三方服务返回的content-type格式就是不对无法控制。。

**Comment by maojj** [comment]
设计初衷是处理 json 格式，期望服务端的配置都正确。保证服务端不要返回的数据是 JSON 格式，但是 content type 不匹配（如 text/plain） 。

**Comment by applejian** [comment]
这种问题我想吐槽下，接口提交的时候，配置感觉有点繁琐了 ，而且response的地方也限制有点死了 如果一开头设置了类型，返回就容易出现失败，难道不能根据实际情况进行扩展么，比如我请求过去的时候，并不知道返回的类型是是什么，但是我response的地方可以做出相应的扩展，比如：.responeAsXML、.responeAsJSON、.responeAsString、.responeAsData ... 类似的等等

**Comment by CnKyo** [comment]
NSSet *contentTypeSet = [NSSet setWithObjects:@"application/json", @"text/plain", @"text/javascript", @"text/json",@"text/html",@"text/css", nil];
[[YTKNetworkAgent sharedInstance] setValue:contentTypeSet forKeyPath:@"_manager.responseSerializer.acceptableContentTypes"];
这个方法在新版本里面直接修改会报错,要么自定义API,要么修改AF源码AFURLResponseSerialization.h
里面搜索self.acceptableContentTypes然后在里面 添加@"text/html",@"text/plain"这样就可以解决了

**Comment by McGonagall666** [comment]
参考https://github.com/yuantiku/YTKNetwork/issues/306
