### ISSUE TITLE
关于缓存的问题

### ISSUE THREAD

**Issue by techistoner** [yuantiku/YTKNetwork#132]
由于某些原因请求成功，但是返回数据是空，重新请求，就一直走缓存，怎么清除该请求的缓存呢，您写的有个叫强制更新缓存，但是觉得不适合这种情况，我想要在我数据为空的时候，清除该请求的缓存，以便下次请求不会调用缓存

**Comment by zhangjiajia** [comment]
https://github.com/dake/TCNetwork 这个库不错，你可以去看看

**Comment by liujianying** [comment]
我也遇到相似的问题，现在出现去请求数据了，数据成功回调，取的竟然是缓存的数据，我也是醉了。不知道是我使用问题还是。。。

**Comment by Sunnyyoung** [comment]
@zhangjiajia @liujianying 看看服务器返回`HTTP Header`中的`Cache-Control`是多少

**Comment by liujianying** [comment]
HTTP/1.1 200 OK
Server	Apache-Coyote/1.1
Content-Type	application/json;charset=UTF-8
Transfer-Encoding	chunked
Date	Wed, 06 Jan 2016 01:46:48 GMT

**Comment by liujianying** [comment]
HTTP/1.1 200 OK
Server	Apache-Coyote/1.1
Content-Type	application/json;charset=UTF-8
Transfer-Encoding	chunked
Date	Wed, 06 Jan 2016 01:46:43 GMT
服务器没有返回Cache-Control这个字段

**Comment by xserver** [comment]
这个问题，带缓存的库都会遇上，这个需要使用者做一些保护。判读下载下来的数据是否正确，JSONValidator 就是干这事的看门狗。
