### ISSUE TITLE
AFN 3.0 already release , you guys come on.

### ISSUE THREAD

**Issue by zdrjson** [yuantiku/YTKNetwork#133]

**Comment by tangqiaoboy** [comment]
@lancy 搞一下？

**Comment by lancy** [comment]
@zdrzdr Upgrading to AFN 3.0 is a big deal, we don't have an upgrade plan recently, until we figure out why and how to do that.

@tangqiaoboy YTKNetwork 以及我们的上层应用比较大程度的依赖了 `AFHTTPRequestOperation` ，而AFNetworking 3.0 移除了 `AFURLConnectionOperation`、 `AFHTTPRequestOperation`和`AFHTTPRequestOperationManager`类，全面转移到了`NSURLSession`的APIs；这么做的一个原因是为了达到 session 配置分离的效果；YTKNetwork 支持的是 request 级别的配置分离，所以我暂时看不到迁移到 AFN 3.0 的好处；近期也不会有计划升级到 3.0；等开发 YTKNetwork 2.0 的时候再说吧；

**Comment by zjszyms** [comment]
https://github.com/DaZuo/NetworkByYala

这个不错，我也照着上面修改了一份！

**Comment by darkness5770** [comment]
实际上，AFNetworking之所以使用NSURLSession的原因是为了支持http2.0.........YTK要跟上时代啊......

**Comment by lancy** [comment]
@darkness5770 你说的对，Apple 全面的从 `NSURLConnection` 迁移到了 `NSURLSession` ，增加了包括 HTTP/2 (iOS 9+)，后台任务等功能的支持。但我们的确还没有类似的需求，而升级的工作量并不算小，所以近期内还没能安排时间进行升级。

如果你们的确有 HTTP/2 的需求，欢迎提 PR 帮助我们，或是 Folk 一份代码自行作修改，类似 @zjszyms 提到的。

Thanks.

**Comment by maojj** [comment]
暂时没有计划。  初步想法是 等 swift 版本时候支持。

**Comment by maojj** [comment]
AFN-3.x 分支已经开始开发了。

**Comment by maojj** [comment]
YTKNetwork 2.0  已发布，基于AFN 3.x， 已支持 carthage
