### ISSUE TITLE
YTKRequestMethodDelete failed, status code = 400

### ISSUE THREAD

**Issue by wenhaowang** [yuantiku/YTKNetwork#135]
Using AFNetworking (2.6.3)
Using YTKNetwork (0.5.0)

**Comment by zhanghaoios** [comment]
我也遇到了

**Comment by wenhaowang** [comment]
我也解决了, 使用YTKRequestMethodDelete的时候request HTTP boby是否要传参数, 如果是的话, 建议重写buildCustomUrlRequest

**Comment by lancy** [comment]
Delete 的时候走的 AFNetworking 默认的行为，看起来应该是会把 参数 放在 URL 的
