### ISSUE TITLE
可否考虑在config里在增加两个Block属性来统一处理发请求之前和请求完成后的事件？

### ISSUE THREAD

**Issue by liwenDeng** [yuantiku/YTKNetwork#136]
个人觉得可否在config里在增加两个Block属性来统一处理发请求之前和请求完成后的事件，这样可以处理发送请求时需要做的统一操作，比如显示和隐藏菊花。功能类似于 Ajax 里面的 ajaxStart()和ajaxStop()

**Comment by lancy** [comment]
我们项目内的所有 `Request` 类都会继承一个基类来实现相关需求；
例如 `APEBaseRequest` 继承自 `YTKRequest`；而所有的请求都会继承自 `APEBaseRequest`
