### ISSUE TITLE
对YTKNetworkAgent中的方法handleRequestResult 的一点疑问

### ISSUE THREAD

**Issue by XB-Paul** [yuantiku/YTKNetwork#137]
方法定义及实现
```
- (void)handleRequestResult:(AFHTTPRequestOperation *)operation {
    NSString *key = [self requestHashKey:operation];
    YTKBaseRequest *request = _requestsRecord[key];
    if (request) {
       ……//（省略）
    }
}
```

方法的调用
```
                request.requestOperation = [_manager GET:url parameters:param success:^(AFHTTPRequestOperation *operation, id responseObject) {
                    [self handleRequestResult:operation];
                }                                failure:^(AFHTTPRequestOperation *operation, NSError *error) {
                    [self handleRequestResult:operation];
                }];
```

疑问：为什么方法handleRequestResult: 中的YTKBaseRequest的实例对象是通过读取字典_requestsRecord来获取的，而不是通过方法传参直接传过去呢？在方法调用的地方都是可以拿到这个YTKBaseRequest实例对象的。对YTKBaseRequest实例对象加一个__block修饰之后，当作参数传递到方法handleRequestResult: 中，这种做法不可以吗？我想知道你们考虑的是什么细节方面？请赐教！请解惑！

另：将YTKBaseRequest的实例放在字典_requestsRecord中，方便在结束请求时找到对应的YTKBaseRequest实例，这点我觉得是可取的。

**Comment by lancy** [comment]
我猜测是历史原因，`YTKNetwork` 最早构建在 `ASIHttpRequest` 上，当时 `ASIHttpRequest` 应该是不支持 Block 回调的，所以会把 `Request` 存起来供回调的时候使用。

这个实现我认为并没有问题，所以也没有必要特意去修改

@tangqiaoboy 最早写了这部分，如果我猜的不对，可补充一下
