### ISSUE TITLE
关于JSONValidator

### ISSUE THREAD

**Issue by ivanyang1984** [yuantiku/YTKNetwork#138]
看了一下 例子中的 数据量比较少， 我们的接口数据量都略大， 如果要写这个 return  XXXCLASS 恐怕是要写死人了。  我觉得 这个 VALIDATOR  只需要验证 服务端 传给你的是否是空 就行了， 不允许 NIL NULL 等字符串 然后前面使用的时候 使用 对象映射DIC 的方式 在映射框架里 写类型转换会比较好。

**Comment by xserver** [comment]
1、JSON 映射Model 都不用你写转换；
2、强类型检查，避免协议定义 int 后台却给你 string；

好奇你们接口数据量有多大...我们的Model 都不大。。。顶多也就10来个属性，大的话，Model组合使用。

**Comment by lancy** [comment]
JSONValidator 可以只写需要的部分，不用全写上；比如只验证关键数据
