### ISSUE TITLE
关于打破循环引用

### ISSUE THREAD

**Issue by YindongW** [yuantiku/YTKNetwork#140]
在YTKBaseRequest中通过-(void)clearCompleteFilter来置空block打破循环引用。我想问如果在调用AFN的方法时使用的是__weak修饰的weakSelf，那是不是就不需要再置空block了，能否不引起循环引用。

**Comment by lancy** [comment]
YTKRequest 不支持重复使用，所以现在的处理方式是合理的

至于你说的应该不对，在 VC 持有 Request，Request 的 Block 又调用了 VC 的实际，调用 AFN 的时候使用 weak 并没有打破 `vc->request->completeBlock->vc` 的循环引用；持有 block 的是 request，和 AFN 无关；
