### ISSUE TITLE
YTKUrlFilterProtocol实现类和requestArgument中出现同名参数的问题

### ISSUE THREAD

**Issue by xilin** [yuantiku/YTKNetwork#144]
目前的实现里在`buildRequestUrl`时调用了filter，之后或是调用
```
NSString *filteredUrl = [YTKNetworkPrivate urlStringWithOriginUrlString:url appendParameters:param];
```
或是通过`AFHTTPRequestOperationManager`里的http方法添加param

如果filter和argument中出现同名字段key的话请求都会带上两个key=value

有什么推荐的处理方法不？

**Comment by maojj** [comment]
这个没处理，最好写filter时候自己避免，保证不重复。

**Comment by xilin** [comment]
filter和requestArgument是两个独立的存在，filter无法获得requestArgument的内容吧？这样应该保证不了重复问题？
