### ISSUE TITLE
Status Code = 0 的问题

### ISSUE THREAD

**Issue by junwangInChina** [yuantiku/YTKNetwork#147]
初次使用YTKNetwork，调用原来工程中的App的时候，发现在回调的地方
```
BOOL result = [request statusCodeValidator];
```
```
- (BOOL)statusCodeValidator {
    NSInteger statusCode = [self responseStatusCode];
    if (statusCode >= 200 && statusCode <=299) {
        return YES;
    } else {
        return NO;
    }
}
- (NSInteger)responseStatusCode {
    return self.requestOperation.response.statusCode;
}
```
这里返回的statusCode为0，导致框架中判断result＝NO，请求失败。
但是实际上请求是成功了，请求的数据也拿到了。

**Comment by youmoxiyou** [comment]
我也遇到了类似的问题。在做文件下载的时候，中断网络时返回的是200或者206，并不是失败状态码

**Comment by junwangInChina** [comment]
那请问你找到问题了么，怎么处理掉的？

**Comment by maojj** [comment]
statusCode 为 0，  请求是怎样成功的 ？

**Comment by yuanjianguo** [comment]
网络请求经常出现statusCode 为 0的状态，这是什么情况

**Comment by jxdwinter** [comment]
+1

**Comment by 844174844** [comment]
+1, 维护团队谁能出来解决一下?

**Comment by lancy** [comment]
`statusCode` 为大部分情况下都是请求没有正确发出的错，比如网络连接异常等

**Comment by 844174844** [comment]
今天又碰到一天statusCode=0的问题,同样的代码昨天还运行的好好的.
于是直接用AF去get百度, 405错误, 网上找到答案说重启模拟器. 我重启模拟器并没有什么卵用, 但是改用真机调试网络连接没有问题. 估计还是模拟器问题, 换一个模拟器或许就好了.

**Comment by junwangInChina** [comment]
但是开发的时候，调试使用真机不是太麻烦了么？

**Comment by 844174844** [comment]
好吧, 第三天遇到返回空值问题, statusCode=200, 但是object为NULL, 最后发现是封装的json解析器的问题, 当然这是服务器返回的json数据不够规范的原因, 解决办法:如果用cocoa的解析器就可以解析出来

**Comment by githhhh** [comment]
连续发起2、3个 YTKRequest请求，Request YTKRequest failed, status code = 0.  全部失败或只有一个请求成功，Request queue 不起作用？？？？？
