### ISSUE TITLE
pods 安装问题

### ISSUE THREAD

**Issue by Jerry-Yao** [yuantiku/YTKNetwork#148]
在使用pods 安装YTKNetwork时，会与本身安装过的AFNetworking版本冲突。

[!] Unable to satisfy the following requirements:

- `AFNetworking (= 3.0.4)` required by `Podfile`
- `AFNetworking (~> 2.0)` required by `YTKNetwork (0.6.0)`

求解...

**Comment by maojj** [comment]
YTKNetwork 暂不支持AFNetworking 3.0 ，所以如果要用 YTKNetwork 只能把 Podfile 中 AFNetworking 改成 ~> 2.0
