### ISSUE TITLE
Response Cache 返回错误

### ISSUE THREAD

**Issue by xserver** [yuantiku/YTKNetwork#152]
1、多个 Request （A、B、C）；
2、不同 RquestArgument；
3、开启 cacheTimeInSeconds；

现象：Request A 会返回 Request B 的缓存。

猜测：缓存写入错误。是线程错误，还是共享缓存错误？

--
##### 你们注释：共享缓存？

``` Objective-C
// 手动将其他请求的JsonResponse写入该请求的缓存
// 比如AddNoteApi, UpdateNoteApi都会获得Note，且其与GetNoteApi共享缓存，可以通过这个接口写入GetNoteApi缓存
- (void)saveJsonResponseToCacheFile:(id)jsonResponse {
```

##### 会不会是  AFHTTPRequestOperation 的 hash 返回值一样，导致返回错误 request ？
```Objective-C
- (NSString *)requestHashKey:(AFHTTPRequestOperation *)operation {
    NSString *key = [NSString stringWithFormat:@"%lu", (unsigned long)[operation hash]];
    return key;
}
```

**Comment by lancy** [comment]
A、B、C 三个请求是同时发出的还是分开发出的？
可以通过分别请求来判别是否是多线程问题；

缓存会按`- (NSString *)cacheFilePath`写入磁盘，其生成的规则依赖`- (NSString *)cacheFilePath`，如下：
```objc
- (NSString *)cacheFileName {
    NSString *requestUrl = [self requestUrl];
    NSString *baseUrl = [YTKNetworkConfig sharedInstance].baseUrl;
    id argument = [self cacheFileNameFilterForRequestArgument:[self requestArgument]];
    NSString *requestInfo = [NSString stringWithFormat:@"Method:%ld Host:%@ Url:%@ Argument:%@ AppVersion:%@ Sensitive:%@",
                                                        (long)[self requestMethod], baseUrl, requestUrl,
                                                        argument, [YTKNetworkPrivate appVersionString], [self cacheSensitiveData]];
    NSString *cacheFileName = [YTKNetworkPrivate md5StringFromString:requestInfo];
    return cacheFileName;
}
```

可以看到是包含了`requestArgument`的，可以在这些地方下断点来诊断问题。

另外注释的意思是说，可以手动调用`- (void)saveJsonResponseToCacheFile:(id)jsonResponse`方法来手动写入缓存，这里说的“共享缓存”可能描述不清，实际意义是说，UpdateNoteApi返回的Note，写入GetNoteApi，这样GetNoteApi就下次就不需要重新发请求获取了。

**Comment by xserver** [comment]
0、有同时，有分开，也有频繁发送多个请求，看情况；

1、断点：这个是很偶然才会发现的，打断点也没有用，我可以肯定的是，取缓存，取到别的 request；
```
api.ignoreCache = NO; // 『似乎』会导致这个问题出现
```

2、cacheFileName，我的 Argument 都带上不一样的 Command Number，所以 name 是不会重复的；

3、saveJsonResponseToCacheFile，可以手动覆盖 Cache；
