### ISSUE TITLE
设置忽略缓存/或强制刷新，还是会出现缓存的数据

### ISSUE THREAD

**Issue by wzi90921** [yuantiku/YTKNetwork#154]
非常感谢您们提供了这么方便易用的类库，在我们的使用过程中，出现了一些关于缓存的问题。。
设置了YTKRequest ignoreCache=yes；或者 调用 startWithoutCache 执行网络请求时，
-(void)requestCompleteFilter 在该方法里面打印返回数据，跟- (id)responseJSONObject 的数据不一样。
-(void)requestCompleteFilter返回的数据是最新的，- (id)responseJSONObject 返回的数据是之前的。
我估计应该是读取了缓存数据。

```
- (id)responseJSONObject {
    if (_cacheJson) {
        return _cacheJson;
    } else {
        return [super responseJSONObject];
    }
}

```
现在我们只能将 YTKRequest 的该方法注释掉。

**Comment by skyline75489** [comment]
当一个 request 实例使用两遍时会出现这种情况

**Comment by xx-li** [comment]
之前也碰到过这个问题，这个地方容易造成误解。对这种情况做处理会不会好点？

**Comment by skyline75489** [comment]
YTKNetwork 的设计不推荐一个 request 重复使用。新的在开发中的的版本中其实也处理了这种情况。以后大家应该不会再遇到这个问题了。
