### ISSUE TITLE
偶尔出现Status Code = 0

### ISSUE THREAD

**Issue by jxdwinter** [yuantiku/YTKNetwork#155]
阿里云的服务器,网站已经备案,没开https,但是偶尔会出现Status Code = 0的问题.出现几率低.
请求帮助.

**Comment by SuooL** [comment]
同样遇到了这个问题，请问这个问题大概是什么原因导致的呢？

**Comment by jxdwinter** [comment]
@SuooL 联系方式?我们交流下?

**Comment by ToBeEngineer** [comment]
这个问题我也发现了，Status Code＝0时，NSError的信息为NSURLErrorDomain Code=-1004 "Could not connect to the server."  是不是跟ATS有关？有时候调试运行后，所有请求都-1004，重新编译启动又好了，具体没有细看。仅供参考

**Comment by maojj** [comment]
参见 #147
