### ISSUE TITLE
API管理

### ISSUE THREAD

**Issue by pingguoilove** [yuantiku/YTKNetwork#158]
看了一下YTNetwork，感觉很不错，在AFNetworking上封装了一层，防止在工程中直接对AFNetworking依赖，以command模式来设计请求，小巧灵活。
但是有一个疑惑：每一个请求封装成一个类，多人协作的时候，如何管理这些API呢？例如如何在工程中组织这些Request类，统一放到一个文件夹下，还是分散放到各个业务模块下，当我需要用一个API请求的时候，我如何知道这个Request是否已经实现？
望解答

**Comment by maojj** [comment]
这个是仁者见仁智者见智的问题了。
我们是会根据业务需求分别管理，如 登录相关放一起，  首页相关，根据业务逻辑。是否已实现，需要开发同事多沟通。大家约定一致，就好查找。
