### ISSUE TITLE
YTKNetworkAgent线程安全

### ISSUE THREAD

**Issue by pingguoilove** [yuantiku/YTKNetwork#160]
[以下代码](https://github.com/yuantiku/YTKNetwork/blob/master/YTKNetwork/YTKNetworkAgent.m#L90)
```
if (request.requestSerializerType == YTKRequestSerializerTypeHTTP) {
        _manager.requestSerializer = [AFHTTPRequestSerializer serializer];
    } else if (request.requestSerializerType == YTKRequestSerializerTypeJSON) {
        _manager.requestSerializer = [AFJSONRequestSerializer serializer];
    }
```

在多个线程并发访问addRequest:接口的时候可能会引起serializer不正确吧？

**Comment by zhima** [comment]
你好，我在
`_manager.requestSerializer = [AFJSONRequestSerializer serializer];` 
这一句遇到了 EXC_BAD_ACCESS KERN_INVALID_ADDRESS 的崩溃，请问有知道原因的吗？

**Comment by angryapes** [comment]
我的项目也遇到了在多个线程并发访问addRequest:接口的时候 ，导致crash的情况，请问怎么解决？

**Comment by lancy** [comment]
这个地方的确有问题，我们这段时间正在想一个好的方案来解决；当前的多线程 workaround 方案，可以把 `[api start]` 都 dipatch 到一个串行队列执行

**Comment by pingguoilove** [comment]
@lancy 期待，可以学习下

**Comment by maojj** [comment]
fixed
