### ISSUE TITLE
如何做单元测试

### ISSUE THREAD

**Issue by AllanChen** [yuantiku/YTKNetwork#165]
如题：如何做Unit testing ????????

**Comment by Z-AnDong** [comment]
+1

**Comment by skyline75489** [comment]
See https://github.com/yuantiku/YTKNetwork/blob/AFN-3.X/YTKNetworkTests/YTKNetworkRequestTests.m

**Comment by ynot16** [comment]
链接失效了，请问有更新吗？

**Comment by ynot16** [comment]
https://github.com/yuantiku/YTKNetwork/blob/master/YTKNetworkTests/Test%20Cases/YTKNetworkRequestTests.m
