### ISSUE TITLE
AFNetwork已经更新到3.0，请问YTKNetwork 会支持AF的3.0么

### ISSUE THREAD

**Issue by hmilyyjm** [yuantiku/YTKNetwork#166]

**Comment by luoerming** [comment]
当然，毕竟他们从ASIHttpRequest 到AF只用两天，从AF2.0到3.0也就是半天的事情；

**Comment by techistoner** [comment]
不知道他们啥时候动手

**Comment by hmilyyjm** [comment]
现在苹果已经要求6-1以后提交 app store 的 app 必须兼容 ipv6 协议
 iOS 9 以后 NSURLSession和CFNetwork 的 api 兼容 ipv6，AFNetworking 需要 3.0 以上,
想知道，他们什么时候动手?

**Comment by Sunnyyoung** [comment]
参考仿了一个，加入了缓存等功能
[https://github.com/Sunnyyoung/SYNetwork.git](https://github.com/Sunnyyoung/SYNetwork.git)

**Comment by maojj** [comment]
#133
