### ISSUE TITLE
关于Apple要求必须支持IPV6的问题，使用现在版本的YTKNetwork会有问题吗？

### ISSUE THREAD

**Issue by Wingzki** [yuantiku/YTKNetwork#168]

**Comment by wjmwjmwb** [comment]
同问

**Comment by SuooL** [comment]
同问

**Comment by yehuaqiang** [comment]
同问

**Comment by LeeFengHY** [comment]
同问

**Comment by Qinzhao** [comment]
同问

**Comment by Wingzki** [comment]
我看了一下YTKNetwork依赖的AFNetworking2.5.4版本，AFNetworkReachabilityManager这个类里使用了sockaddr_in方法，在ipv6下应该用sockaddr_in6方法。如果YTK不提供更新的话，可以自行修改AF的代码。其他地方我没有发现不兼容ipv6的地方，如果大家发现了就提在这个issue上吧。

**Comment by Er01c** [comment]
『If you must check for network availability, avoid calling the SCNetworkReachabilityCreateWithAddress method. Call the SCNetworkReachabilityCreateWithName method and pass it a hostname instead.』

**Comment by maojj** [comment]
其实是否支持 IPV6 主要看 AFNetworking ， 本仓库中用 AFNetworking 不是 2.x 最新代码。
最好的方式还是 AFNetworking 更新， 相关讨论：https://github.com/AFNetworking/AFNetworking/issues/3496
3.0 分支有这部分改动可以对比一下，着急用的可以先手动改。

**Comment by ccxdd** [comment]
YTK现在用的是AF版本是2.6.3我把环境切到ipv6试了下是能支持的。

**Comment by Huang-Libo** [comment]
如果支持就太棒了

**Comment by snowking** [comment]
把 AFNetworkReachabilityManager 换成新的就可以了

**Comment by wtuyp** [comment]
可以在 Mac 上配置下 IPv6 无线共享测试下看是否支持，然后请使用 iOS9 系统。配置参与[这里](http://www.jianshu.com/p/632d995749e1#)
