### ISSUE TITLE
最新版本升级后，[request start] 后无法立即获得 requestOperation，需要获取上传文件进度时操作很别扭

### ISSUE THREAD

**Issue by EuanChan** [yuantiku/YTKNetwork#171]
旧版本使用时如果需要获取上传进度，在 `start` 完后设置上传进度回调 block 即可。
```
[request start];
[request.requestOperation setUploadProgressBlock:uploadHandler] 
```

新版本加入队列，需要额外等到 `requestOpertion`创建完成才能设置 uploadProgressBlock，而 BaseRequest 又缺少相关接口，需要额外用比较多的代码实现。

**Comment by maojj** [comment]
谢谢反馈， 已改成同步，并保证线程安全
