### ISSUE TITLE
缓存的归档解档操作会阻塞主线程

### ISSUE THREAD

**Issue by Huang-Libo** [yuantiku/YTKNetwork#174]
我在请求包含byte数组（是二进制的pdf，大小约10到30兆）的json时，发现YTKNetwork缓存请求回来的数据会阻塞主线程，UI直接卡住，如果我改用缓存策略为不缓存而是每次都从网络请求，就不会阻塞UI；我又用Instrument在真机上测了耗时，发现YTKNetwork的归档解档是放在主线程中执行的。我个人觉得IO操作还是放到子线程比较靠谱。

**Comment by Huang-Libo** [comment]
为何没人来看...

**Comment by maojj** [comment]
@lancy

**Comment by lancy** [comment]
建议大文件下载使用 resumableDownloadPath 接口

**Comment by Huang-Libo** [comment]
@lancy 🆗
