### ISSUE TITLE
关于公共参数过滤器，和请求参数加密的问题

### ISSUE THREAD

**Issue by sesameImmortals** [yuantiku/YTKNetwork#175]
1.通过YTKUrlArgumentsFilter类加上的参数，发给服务器端没收到。这个类中的参数是拼接到AFN前面的url里面的，而不是后面的param参数中的，post方式服务器那边接收不到。
2.我所有请求的参数转换成json格式，需要再对这个json进行一次加密，通过重写- (id)requestArgument{...}这个方法返回字典类型，并重写- (YTKRequestSerializerType)requestSerializerType这个方法，传递过去的参数确实是json，但是我无法拿到这个json字符串再加密。而不重写- (YTKRequestSerializerType)requestSerializerType，我直接在- (id)requestArgument{...}返回json字符串，服务器端接收到的参数类型是字典类型，会多出一个”=“号。
希望有经验的人士能给予我合适的解答。

**Comment by SuooL** [comment]
这个过程据我自己的了解是你要修改 AFN 的层面, YTK 在 具体的http请求封装中的 setBody 等阶段都是依赖 AFN 做的. 所以, 我的建议是你在 setBody 的阶段加密 JSON 串.

**Comment by SuooL** [comment]
你的加密需求, 我的处理方式是: 在 YTK 中, 要 post 提交 `application/json` 这种格式的数据, 需要重写 `- (YTKRequestSerializerType)requestSerializerType` 这个方法保证提交格式是 `application/json` , 然后在 AFN 中的 setBody 对应的封装阶段先对 JSON 串加密, 然后 setBody .

**Comment by lancy** [comment]
1. YTKUrlArgumentsFilter 如名字所说，就是用于在 Url 上加参数的；如果你希望在 requestArgument 中添加公共参数，可以通过继承一个业务基类实现
1. 如果需要这样的定制程度，建议重载 buildCustomUrlRequest

**Comment by sesameImmortals** [comment]
@SuooL   @lancy  非常感谢两位的耐心解答，当时因为无法解决我自己的网络请求的需求，就放弃了使用YTKNetWork，也确实是我当时没有找到YTK中合适的解决方案，现在已经找到其余的解决方案了。
