### ISSUE TITLE
request.responseStatusCode == 302 捕获不了

### ISSUE THREAD

**Issue by wjmwjmwb** [yuantiku/YTKNetwork#176]
404 等 都能正确捕获,但是当状态吗 = 302时, request.responseStatusCode = 200.这是bug?

**Comment by wjmwjmwb** [comment]
找到问题了, 是服务器给重定向了. 
问一下~ 能不能 捕捉到重定向之前的状态码~@maojj

**Comment by maojj** [comment]
这个问题我也不清楚。

**Comment by maojj** [comment]
查了下 AFNetworking, AFURLConnectionOperation 可以设置 block： setRedirectResponseBlock
```
- (void)setRedirectResponseBlock:(nullable NSURLRequest * (^)(NSURLConnection *connection, NSURLRequest *request, NSURLResponse *redirectResponse))block;
```

**Comment by xt-input** [comment]
@interface YTKNetworkAgent (Private)

- (AFHTTPSessionManager *)manager;
- (void)resetURLSessionManager;
- (void)resetURLSessionManagerWithConfiguration:(NSURLSessionConfiguration *)configuration;

- (NSString *)incompleteDownloadTempCacheFolder;

@end
猿题库的这个网络管理api是私有的！！
manager
