### ISSUE TITLE
APPLE要求支持IPV6，请问什么时候能更新AFNetworking最新版

### ISSUE THREAD

**Issue by hamilyjing** [yuantiku/YTKNetwork#177]

**Comment by maojj** [comment]
AFNetworking 2.x 官方还是只停留在 2.6.3， 一直关注着，等他们更新呢。

**Comment by wtuyp** [comment]
@maojj  2.6.3 支持 IPv6 呢

**Comment by yzxcool123** [comment]
现在已经有3.1.0了吧

**Comment by wushenchao** [comment]
af早就升级到3以上了

**Comment by maojj** [comment]
3.0 换 NSURLSession 了， YTKNetwork 只能用 2.x 版本。  现在 YTKNetwork 里面 AFNetworking 用的就是 2.6.3

**Comment by lytys** [comment]
YTKNetwork 现在支持ipv6吗？

**Comment by maojj** [comment]
#168  重复
