### ISSUE TITLE
请教：YTKRequest 类中的这段代码是不是有问题？？

### ISSUE THREAD

**Issue by niehaili** [yuantiku/YTKNetwork#180]
这样写不会有问题吗？
<img width="693" alt="pic" src="https://cloud.githubusercontent.com/assets/13791458/15881178/84704c66-2d66-11e6-94c4-4279cd949fc3.png">

**Comment by niehaili** [comment]
哦 错了  没问题 只是有点多余

**Comment by maojj** [comment]
不多余， 当 block 为 nil ，不判断会 crash。

**Comment by niehaili** [comment]
恩恩，我说的是这句： YTKRequest *strongSelf = self;当时是看错了
