### ISSUE TITLE
特定情况下responseJSONObject会始终返回缓存数据

### ISSUE THREAD

**Issue by Wingzki** [yuantiku/YTKNetwork#181]
对于有缓存的YTKRequest先调用start，之后再调用startWithoutCache，request的responseJSONObject会始终返回缓存。原因是调用startWithoutCache之前没有将_cacheJson置空，这应该是bug吧，还是就这么设计的？

**Comment by maojj** [comment]
YTKRequest 里面
```
- (void)startWithoutCache {
    [super start];
}
```

直接调用 super 发请求了，没有从 cacheJson 读的。

**Comment by Wingzki** [comment]
建议先按我说的流程测试一下，是调用request的responseJSONObject会始终返回缓存。

`- (id)responseJSONObject {
    if (_cacheJson) {
        return _cacheJson;
    } else {
        return [super responseJSONObject];
    }
}`

这个方法应经被复写了，只要_cacheJson不为空就会返回缓存，和是否调用[super start]无关。

**Comment by maojj** [comment]
抱歉，理解错了。 以为你是不同 request 对象。而实际你是同一个request 先 start 然后再startWithoutCache。 ？
一般不要复用 同一个 request， 发完请求后，如果需要再发，应该新建一个 request 对象
