### ISSUE TITLE
上传文件获取进度

### ISSUE THREAD

**Issue by wujunyang** [yuantiku/YTKNetwork#184]
请问YTKNetwork支持上传文件获取进度值么？

**Comment by hotwill07** [comment]
请问下载的进度，你如何处理的啊？ 我也遇到通用的问题，请赐教！

**Comment by maojj** [comment]
@hotwill07  下载可以用 
```
- (AFDownloadProgressBlock)resumableDownloadProgressBlock;
```

**Comment by hotwill07** [comment]
@maojj  已经解决了，谢谢！！

**Comment by hotwill07** [comment]
@wujunyang  可以在请求结束之后 ，加上一段代码就可以获取进度了，
TestUploadFileRequest *api = [[TestUploadFileRequest alloc] initWithFileName:@"1.mp4"];
    [api startWithCompletionBlockWithSuccess:^(__kindof HYBaseRequest *request) {
        NSLog(@"successfully......");
        NSLog(@"====%@",[[NSString alloc] initWithData:request.responseData encoding:NSUTF8StringEncoding]);
    } failure:^(__kindof HYBaseRequest *request) {
        NSLog(@"fail......");
    }];

    [api.requestOperation setUploadProgressBlock:^(NSUInteger bytesWritten, long long totalBytesWritten, long long totalBytesExpectedToWrite) {
        NSLog(@"%ld --- %lld --- %lld", bytesWritten,totalBytesWritten,totalBytesExpectedToWrite);
        NSLog(@"%lld%%", (long long)(1.0 * totalBytesWritten / totalBytesExpectedToWrite * 100));
    }];

**Comment by wujunyang** [comment]
@hotwill07  这种在结束之后才写setUploadProgressBlock  这样会不会造成重复上传？

**Comment by Huang-Libo** [comment]
@maojj @hotwill07 上传进度的获取能不能像下载进度（resumableDownloadProgressBlock）一样封装（取名resumableUploadProgressBlock如何？）

**Comment by maojj** [comment]
uploadProgressBlock 可以考虑呢，不过这个需求很少遇到，所以也就没有做。

**Comment by maojj** [comment]
确实有这个需求的话，可以 fork 一份，自己修改。

先关了这个 issue
