### ISSUE TITLE
Pod管理的YTKNetwork怎么添加插件？

### ISSUE THREAD

**Issue by Huang-Libo** [yuantiku/YTKNetwork#185]
猿题库提供的HUD插件（https://gist.github.com/lancy/4982d0f6f708133cc8e1#） 怎么添加到pod管理的YTKNetwork中？

**Comment by SuooL** [comment]
..我的解决方法可以自己封装一层 BaseRequest,然后需要用的时候加进去就好...因为不是所有的请求都需要 HUD 显示

**Comment by Huang-Libo** [comment]
为什么不直接在某个API里面直接加呢？可以贴你的代码看看么

**Comment by SuooL** [comment]
我就是直接在 API 初始化的时候加的,,,不过我的 API 初始化时集中在一个 BaseRequestManage 类里面完成的...就是我自己在 YTK 上有封装了一层，因为需要统一处理一些 API 回调的 （比如 token）。当然你在 API 里面直接加也是可以的

**Comment by Huang-Libo** [comment]
按照这种方式加，能在请求失败的时候给出hud提示吗

**Comment by SuooL** [comment]
请求失败也可以...具体看你的业务了.我的是请求失败没有数据会自己造一个 msg

**Comment by Huang-Libo** [comment]
@SuooL 在API里面是怎么写的？addAccessory方法里面的第二个参数该怎么传？我用的MBProgressHUD，能贴一段代码给我参考吗？

```
- (instancetype)init
{
    self = [super init];
    if (self) {
        MBProgressHUD *hud = [[MBProgressHUD alloc] init];
        [self addAccessory:[YTKAnimatingRequestAccessory accessoryWithAnimatingView:hud animatingText:@"小猿正在努力加载"]];

    }
    return self;
}
```

**Comment by SuooL** [comment]
这个是其中一个参考代码：
`    PMSellerAuthenAPI *request = [[PMSellerAuthenAPI alloc] initWithArgumentValueDictionary:dic];
    [request addAccessory:[YTKAnimatingRequestAccessory accessoryWithAnimatingText:@"努力提交信息中···"]];`
我在`YTKAnimatingRequestAccessory`的`requestWillStart`方法中，添加了自己封装的 HUD 显示方法。比如这样的语句`[WLAlertUtils showLoadingAlertView:_animatingText];`，具体的 HUD 封装则是在 HUD 类中。

**Comment by SuooL** [comment]
这里我把YTKAnimatingRequestAccessory的方法改造了一下，直接去了第一个参数，因为我的 HUD 风格都是统一的，就没有必要暴露给 API 层了，直接封装在了requestWillStart方法中。

**Comment by Huang-Libo** [comment]
@SuooL 我添加hud没有效果，我想看看你添加hud的代码。

**Comment by SuooL** [comment]
您方便可以直接把您的代码贴出来看下

**Comment by SuooL** [comment]
按照您的代码，添加了 HUD 之后，还需要在YTKAnimatingRequestAccessory类中的requestWillStart及requestWillStop中添加是 HUD 显示和隐藏的代码。不然不会显示你需要的添加的 HUD。这里的机制是会帮你处理何时显示和隐藏，但是具体显示什么，怎么显示，需要你自己来设置。

**Comment by Huang-Libo** [comment]
@SuooL 现在搞定了！之前一直搞不好原因有两个:
1. requestWillStart及requestWillStop方法没有实现，也就是需要在这两个方法里面调用自己的hud utils，之后ytk框架会自动调用requestWillStart及requestWillStop方法；
2.我误解了animatingView这个参数的意思。这个参数是指hud要被添加到的那个view，而我之前误解animatingView就是hud...

总之，非常感谢！
