### ISSUE TITLE
关于YTKBaseRequest (RequestAccessory) 作用

### ISSUE THREAD

**Issue by hotwill07** [yuantiku/YTKNetwork#186]
```
@interface YTKBaseRequest (RequestAccessory)

- (void)toggleAccessoriesWillStartCallBack;
- (void)toggleAccessoriesWillStopCallBack;
- (void)toggleAccessoriesDidStopCallBack;

@end
```
这个分类的实现，通过断点走的时候，直接跳过，请问作用是？谢谢

**Comment by Sunnyyoung** [comment]
插件机制，HUD提示可以扔这里来

**Comment by hotwill07** [comment]
@Sunnyyoung  HUD地址有不？再谢！

**Comment by Sunnyyoung** [comment]
@hotwill07 这个HUD插件机制是通用的，什么HUD都能用，详情：https://gist.github.com/lancy/4982d0f6f708133cc8e1

**Comment by hotwill07** [comment]
@Sunnyyoung  这个网址打不开啊，兄弟！

**Comment by Huang-Libo** [comment]
@Sunnyyoung 可以给一个插件集成Demo吗

**Comment by Huang-Libo** [comment]
@hotwill07 网址可以打开的，实在打不开你挂个VPN试试

**Comment by Huang-Libo** [comment]
@hotwill07 可以看看这个issue：https://github.com/yuantiku/YTKNetwork/issues/185

**Comment by maojj** [comment]
更新的 demo 代码  见 YTKAnimatingRequestAccessory 类
