### ISSUE TITLE
支持https请求吗？

### ISSUE THREAD

**Issue by guoshimeihua** [yuantiku/YTKNetwork#187]
最近在项目中，需要 接入https请求，同时兼容http请求。

**Comment by cru1se** [comment]
YTKNetworkConfig里面可以设置

**Comment by maojj** [comment]
支持的

**Comment by maojj** [comment]
let config = YTKNetworkConfig.sharedInstance()
        config.securityPolicy = AFSecurityPolicy(pinningMode: .Certificate)
