### ISSUE TITLE
有关断点续传，请教大神

### ISSUE THREAD

**Issue by hotwill07** [yuantiku/YTKNetwork#188]
断点续传代码写好了，但是有个问题：第一次下载的时候（我下的是视频42.1MB），是没问题的，进度条也是对的；当第二次下载的时候，1）进度条非常快速的就满了  2）点击取消/暂停按钮的时候 没反应； 当多次下载之后，文件就损坏了，求大神啊，多谢！

**Comment by maojj** [comment]
贴一下代码大家看看吧

**Comment by Huang-Libo** [comment]
@hotwill07 占位关注。贴代码看看吧

**Comment by lilongcnc** [comment]
@Huang-Libo  我没找到取消和暂停的api = =???? 你找到了吗?

**Comment by Huang-Libo** [comment]
@lilongcnc 在YTKBaseRequest里

**Comment by lilongcnc** [comment]
@Huang-Libo  start 和 stop????? /// remove self from request queue 和  append self to request queue从请求队列移除和追加????   这不对吧

**Comment by Huang-Libo** [comment]
@lilongcnc https://github.com/yuantiku/YTKNetwork/issues/194

**Comment by hotwill07** [comment]
//开始下载的方法
- (void)start {
    self.progressView.progress = 0.0;
    self.textView.text = @"";

    NSFileManager *fileManager = [NSFileManager defaultManager];
    if ([fileManager fileExistsAtPath:self.resumeRequest.resumableDownloadPath]) {
        [fileManager removeItemAtPath:self.resumeRequest.resumableDownloadPath error:nil];
    }

    [self.resumeRequest startWithCompletionBlockWithSuccess:^(__kindof HYBaseRequest *request) {
        NSLog(@"succefully...");
    } failure:^(__kindof HYBaseRequest *request) {
        NSLog(@"fail....");
    }];

    __weak typeof(self) weakSelf = self;
    [self.resumeRequest.requestOperation setDownloadProgressBlock:^(NSUInteger bytesRead, long long totalBytesRead, long long totalBytesExpectedToRead) {
        double progressValue = 1.0 * totalBytesRead / totalBytesExpectedToRead;
        double readMb = 1.0 * totalBytesRead / 1024 / 1024;
        double totalMb = 1.0 * totalBytesExpectedToRead / 1024 / 1024;
        NSString *tempText = [NSString stringWithFormat:@"下载进度:%.2lfMB / %.2lfMB \n",readMb,totalMb];
        dispatch_async(dispatch_get_main_queue(), ^{
            weakSelf.progressView.progress = progressValue;
            if (![weakSelf.textView.text containsString:tempText]) {
                weakSelf.textView.text = tempText;
            }
        });
    }];
}

//暂停的方法
- (void)pause {
    [self.resumeRequest stop];
}

//断点续传的代码
- (void)resume {
    [self.resumeRequest startWithCompletionBlockWithSuccess:^(__kindof HYBaseRequest *request) {
        NSLog(@"succefully...");
    } failure:^(__kindof HYBaseRequest *request) {
        NSLog(@"fail....");
    }];

    AFDownloadRequestOperation *operation = (AFDownloadRequestOperation *)self.resumeRequest.requestOperation;
    NSString *path = operation.tempPath;
    NSFileManager *fileManager = [NSFileManager defaultManager];
    signed long long fileSize = 0;
    if ([fileManager fileExistsAtPath:path]) {
        NSError *error = nil;
        NSDictionary *fileDict = [fileManager attributesOfItemAtPath:path error:&error];
        if (!error && fileDict) {
            fileSize = [fileDict fileSize];
        }
    }
    __weak typeof(self) weakSelf = self;
    [self.resumeRequest.requestOperation setDownloadProgressBlock:^(NSUInteger bytesRead, long long totalBytesRead, long long totalBytesExpectedToRead) {
        totalBytesRead += fileSize;
        totalBytesExpectedToRead += fileSize;
        double progressValue = 1.0 * totalBytesRead / totalBytesExpectedToRead;
        double readMb = 1.0 * totalBytesRead / 1024 / 1024;
        double totalMb = 1.0 * totalBytesExpectedToRead / 1024 / 1024;
        NSString *tempText = [NSString stringWithFormat:@"下载进度:%.2lfMB / %.2lfMB \n",readMb,totalMb];
        dispatch_async(dispatch_get_main_queue(), ^{
            weakSelf.progressView.progress = progressValue;
            if (![weakSelf.textView.text containsString:tempText]) {
                weakSelf.textView.text =  tempText;
            }
        });
    }];
}

//懒加载 HYResumeDownloadRequest
- (HYResumeDownloadRequest *)resumeRequest {
    if (!_resumeRequest) {
        _resumeRequest = [[HYResumeDownloadRequest alloc] initWithFileName:@"wKgDrVCYca7Sf6VzADfjEnQrWdU600.mp3"];
    }
    return _resumeRequest;
}

**Comment by maojj** [comment]
```
    [self.resumeRequest startWithCompletionBlockWithSuccess:^(__kindof HYBaseRequest *request) {
        NSLog(@"succefully...");
    } failure:^(__kindof HYBaseRequest *request) {
        NSLog(@"fail....");
    }];
```
 这一行之后  这个request 就已经启动了。 之后在设置可能就有问题了。 具体该怎么做暂时没想到。

**Comment by hotwill07** [comment]
@maojj 多谢，也再想想~~

**Comment by maojj** [comment]
最近想了下，  现有设计不能很好地满足你这个需求， 需要在build request 后并且是 start 前 设置 block，YTKNetwork 1.x 版本可能不会考虑这个需求了，你可以自己fork 一份，参考 resumableDownloadProgressBlock 的设计思路，自己加一个方法。

**Comment by jaybowong** [comment]
@hotwill07  40MB的文件还是不小，建议使用系统的NSURLSession进行断点下载和上传，因为它可以进行后台操作。NSURLSession是交给系统去下载，系统会帮你开一个进程去下载，即使你的应用闪退都不会影响。

Demo: [Simple Background Transfer](https://developer.apple.com/library/ios/samplecode/SimpleBackgroundTransfer/Introduction/Intro.html)
WWDC Session: [What’s New with Multitasking](https://developer.apple.com/videos/play/wwdc2013/204/)

**Comment by skyline75489** [comment]
基于  NSOperation 实现的断点续传，很大程度上受到 `AFDownloadRequestOperation` 自身实现的限制，并不能真正做到随心所欲的暂停和续传。

**Comment by Huang-Libo** [comment]
@skyline75489 原理能讲一下吗？

**Comment by skyline75489** [comment]
NSOperationQueue 启动之后是不存在真正意义上的暂停一说的，queue 的暂停只是会阻止后续任务的添加，已经开始的下载任务不会从中间突然停止。

`AFDownloadRequestOperation` 能做的仅仅是在文件下载的过程中进行暂存，错误之后可以从暂存文件当中恢复下载。

真正想随时暂停，随时恢复，可以考虑使用 `NSURLSessionDownloadTask` 的 `cancelByProducingResumeData:` 结合 resume 有关方法。

**Comment by Huang-Libo** [comment]
@skyline75489 分析的很透彻！ytk集成好afn-3.x之后应该会解决这类问题
