### ISSUE TITLE
headerFieldValueDictionary

### ISSUE THREAD

**Issue by teng555teng** [yuantiku/YTKNetwork#189]
能不能为每个请求 添加headerFieldValueDictionary  像添加YTKUrlFilter 那种方式

**Comment by Sunnyyoung** [comment]
继承`YTKRequest`写个基类就好了

**Comment by SuooL** [comment]
自己封装一层，连接 YTK 和自己的具体业务层就好了。

**Comment by teng555teng** [comment]
继承YTKRequest写个基类就好了 目前就是这么做的
