### ISSUE TITLE
关于获取请求成功后的结果

### ISSUE THREAD

**Issue by lilongcnc** [yuantiku/YTKNetwork#190]
您好,我在最近看你们这套框架的时候.进行测试,在结果返回成功后, 法相YTKBaseRequest对象的userInfo参数是空的,而且responseString这个参数是服务器返回的结果.   看了也可以根据request.responseData在JSON转换.但是AFN不是直接提供了字典的返回形式吗?
所以想请问下,userInfo用户信息?是代表什么呢???API中没有看到详细的注释
没有直接的NSDictionary形式的结果返回吗?YTKBaseRequest我没有找到

**Comment by maojj** [comment]
request.responseJSONObject

**Comment by lilongcnc** [comment]
楼主很感谢你的回答,但是request.responseJSONObject获取不到. 

请求结果如下:
2016-06-27 09:33:06.878 LLYTKNetworkTest0623[856:12407] 
LLYTKLoginApi successed-responseJSONObject:      (null)


2016-06-27 09:33:06.878 LLYTKNetworkTest0623[856:12407]
 LLYTKLoginApi successed-request.responseString:      {"flag":"1","errorMessage":"","data":{"AccountID":"A0C16050300001","MemberID":"JM0C1605030001","Name":"","Sex":"0","MobilePhone":"15801538221","Birthday":"2016-05-03","Email":"","City":"","Provice":"","Address":"","IDs":"230231199211188111","PostCode":"","Status":"1","Credit":"0.00","SoloCredit":"0.00","BusinessAreaID":"BA011411270001","HeadPhoto":"","P2PMemberID":"","P2PAccountID":"","IsPromotion":"1","SelfPromotionID":"12000018","Subs":[]}}


这是返回的结果.......我LLYTKLoginApi类和你们的返利YTKRegisterApi是一样的代码,而且没有对结果做类型判断的限制.你看responseJSONObject:返回的是 null

**Comment by maojj** [comment]
```
- (id)responseJSONObject {
    return self.requestOperation.responseObject;
}
```

responseJSONObject 其实是   self.requestOperation.responseObject，  AFHTTPRequestOperation 处理的，没有相关环境还代码，你这个问题的具体原因我也不清楚，可能需要调试下， 一般没做修改，服务端支持 JSON 的 content type 的话， 是没问题的，直接取 responseJSONObject 就可以的， 比如可以看下服务端设置的 content type 对不，  另外 responseSerializer 是否有修改。

**Comment by lilongcnc** [comment]
找到了原因,是在 content type没有设置.很感谢你的回复!!!

**Comment by maojj** [comment]
没有暴露出来，期望是返回 json 的。
默认的是 AFJSONResponseSerializer ，设置了 contentType
```
    self.acceptableContentTypes = [NSSet setWithObjects:@"application/json", @"text/json", @"text/javascript", nil];
```

**Comment by Sunnyyoung** [comment]
@lilongcnc 

参考 #131 的KVC方法
```objc
NSSet *contentTypeSet = [NSSet setWithObjects:@"application/json", @"text/plain", @"text/javascript", @"text/json",@"text/html",@"text/css", nil];
[[YTKNetworkAgent sharedInstance] setValue:contentTypeSet forKeyPath:@"_manager.responseSerializer.acceptableContentTypes"];
```

**Comment by lilongcnc** [comment]
灰常感谢 @Sunnyyoung @maojj 你们的回复!!! 手动赞
