### ISSUE TITLE
断点续传问题

### ISSUE THREAD

**Issue by lilongcnc** [yuantiku/YTKNetwork#191]
您好哈!
在使用GetImageApi中增加断点续传之后:
```
- (NSString *)resumableDownloadPath {
    NSString *libPath = [NSSearchPathForDirectoriesInDomains(NSLibraryDirectory, NSUserDomainMask, YES) objectAtIndex:0];
    NSString *cachePath = [libPath stringByAppendingPathComponent:@"Caches"];
    NSString *filePath = [cachePath stringByAppendingPathComponent:_imageId];
    return filePath;
}
```

去加载图片的时候,satr-block中request.responseData为空了.
```
  [imageApi startWithCompletionBlockWithSuccess:^(__kindof YTKBaseRequest *request) {
        NSLog(@"request.responseData:%@",request.responseData);
        UIImage *image = [UIImage imageWithData:request.responseData];

        
    } failure:^(__kindof YTKBaseRequest *request) {
        
    }];
```
请问,这个设计加了断点续传就要去本地沙河中加载?这个和断点续传有什么关联吗? 我自己的项目没有遇到断点续传,不是很了解

还有,就是这个断点例子不是完整,请问有完整的例子吗?

**Comment by Huang-Libo** [comment]
@lilongcnc 断点续传肯定得存沙盒嘛

**Comment by lilongcnc** [comment]
恩恩, 我的意思是不断点续传,可以直接通过request.responseData拿到下载的数据.但是加了- (NSString *)resumableDownloadPath {},开启断点续传之后,request.responseData就拿到的是空的了.  这样断点续传的情况下,直接拿不到,得去沙盒里边取,会不会挺麻烦的.

**Comment by Huang-Libo** [comment]
@lilongcnc 网络图片的下载与缓存为何不用SDWebImage

**Comment by lilongcnc** [comment]
......现在我是试着在看怎么使用猿题库的这套逻辑.

**Comment by maojj** [comment]
断点续传的逻辑是用的 AFDownloadRequestOperation 第三方库。 详细内容可以看源码。
当设置了 resumableDownloadPath 则会调用 AFDownloadRequestOperation 来下载， 
AFNetworking 的 outputStream默认 outputStreamToMemory， 也就是写内存。
```
- (NSOutputStream *)outputStream {
    if (!_outputStream) {
        self.outputStream = [NSOutputStream outputStreamToMemory];
    }

    return _outputStream;
}
```

而  AFDownloadRequestOperation 改为文件了
```
        self.outputStream = [NSOutputStream outputStreamToFileAtPath:tempPath append:isResuming];
```

AFDownloadRequestOperation 先下载到 tempPath ，下载完成后才 move 到 targetPath。 

断点续传就是考虑到文件很大， 不方便直接放内存，所以直接通过文件来存储。

所以 AFURLConnectionOperation 中 responseData 为空（读的内存 propertyForKey:NSStreamDataWrittenToMemoryStreamKey ）
```
- (void)connectionDidFinishLoading:(NSURLConnection __unused *)connection {
    self.responseData = [self.outputStream propertyForKey:NSStreamDataWrittenToMemoryStreamKey];

    [self.outputStream close];
    if (self.responseData) {
       self.outputStream = nil;
    }

    self.connection = nil;

    [self finish];
}
```

**Comment by lilongcnc** [comment]
真的是太感谢 @maojj 了!!!没想到得到你这么详细的回复~~~~看懂了!非常非常感谢!!!祝猿题库越来越好!!!
