### ISSUE TITLE
返回的结果都是 带 = 号的json

### ISSUE THREAD

**Issue by sunyazhou13** [yuantiku/YTKNetwork#192]
解析完数据每次都返回带=号的json 数据格式 是不是转成 字典就这样还是 怎么
怎么才能 返回  key : value 这种 json格式
{
    code = 200000;
    data =     (
                {
            addr = "\U5317\U4eac\U5e02\U671d\U9633\U533a\U671d\U9633\U8def";
            "area_id" = 110000;
            "city_id" = 110000;
            gid = 100;
            intro = "\U4ecb\U7ecd";
            lat = "100.02";
            lgt = "100.01";
            name = "CrossFit Met";
            "nat_id" = 86;
            "prov_id" = 110000;
            tel = 18888888888;
        },

**Comment by SuooL** [comment]
...这个先问你的后台 API 程序员是不是搞错了

**Comment by sunyazhou13** [comment]
没有  我测试过别人家的 都是一样的

**Comment by SuooL** [comment]
code 贴出来看一下吧

**Comment by sunyazhou13** [comment]
`@implementation GymsRequest {
    NSString *_cityId;
}

- (instancetype)initWithCityid:(NSString *)cityId
{
    self = [super init];
    if (self) {
        _cityId = cityId;
    }
    return self;
}
//请求的URL
- (NSString *)requestUrl
{
    return @"wechat/v1/gyms";
}

//请求的方法
- (YTKRequestMethod)requestMethod
{
    return YTKRequestMethodGet;
}

/// 请求的SerializerType
- (YTKRequestSerializerType)requestSerializerType
{
    return YTKRequestSerializerTypeJSON;
}

//请求参数
- (id)requestArgument
{
    return @{@"city_id":_cityId.length > 0?_cityId:@"110000"};
}

//请求的返回结果
- (NSDictionary *)grms
{
    NSDictionary *dict = [self responseJSONObject];
    return dict;
}`


###调试的json
`(lldb) po [result description]
{
    code = 200000;
    data =     (
                {
            addr = "\U5317\U4eac\U5e02\U671d\U9633\U533a\U671d\U9633\U8def";
            "area_id" = 110000;
            "city_id" = 110000;
            gid = 100;
            intro = "\U4ecb\U7ecd";
            lat = "100.02";
            lgt = "100.01";
            name = "CrossFit Met";
            "nat_id" = 86;
            "prov_id" = 110000;
            tel = 18888888888;
        },
                {
            addr = addr;
            "area_id" = 110105;
            "city_id" = 110000;
            gid = 47738052;
            intro = intro;
            lat = "100.01";
            lgt = "100.01";
            name = name;
            "nat_id" = 86;
            "prov_id" = 110000;
            tel = tel;
        },
                {
            addr = addr;
            "area_id" = 110105;
            "city_id" = 110000;
            gid = 48193691;
            intro = intro;
            lat = "100.01";
            lgt = "100.01";
            name = name;
            "nat_id" = 86;
            "prov_id" = 110000;
            tel = tel;
        },
                {
            addr = 523;
            "area_id" = 110105;
            "city_id" = 110000;
            gid = 52828091;
            intro = 623;
            lat = 1;
            lgt = 1;
            name = 123;
            "nat_id" = 86;
            "prov_id" = 110000;
            tel = 223;
        },
                {
            addr = "\U4e0a\U6d77xxxxxxxx";
            "area_id" = 310115;
            "city_id" = 310000;
            gid = 66119658;
            intro = "\U968f\U4fbf\U8bf4\U51e0\U53e5";
            lat = "31.280678143799896";
            lgt = "121.58015727996826";
            name = "test\U573a\U9986";
            "nat_id" = 86;
            "prov_id" = 310000;
            tel = 18652827731;
        },
                {
            addr = addr;
            "area_id" = 110105;
            "city_id" = 110000;
            gid = 74357192;
            intro = intro;
            lat = "100.01";
            lgt = "100.01";
            name = name;
            "nat_id" = 86;
            "prov_id" = 110000;
            tel = tel;
        }
    );
}
`

**Comment by sunyazhou13** [comment]
QQ  20145438  感谢 回复  联系QQ比较方便

**Comment by maojj** [comment]
可以看下 responseString 是不是 json格式的 string。 简单点  curl 一下。 看看返回的数据格式对不。不对的话 得找后台开发看下。
