### ISSUE TITLE
除了添加HUD，插件机制还能实现哪些实用/常用的功能？

### ISSUE THREAD

**Issue by Huang-Libo** [yuantiku/YTKNetwork#193]
@SuooL @maojj @tangqiaoboy 
最近使用了YTKNetwork的插件机制给request添加HUD，甚感方便，不知插件机制还能给我们提供哪些便利呢？

**Comment by maojj** [comment]
想到另外的一个： 错误信息统一处理。 比如 401 未登录等

**Comment by Huang-Libo** [comment]
@maojj 我偶然想到了提示用户网络加载的另一种方式：进入页面后自动下拉刷新，如果有缓存数据则先显示缓存。和集成HUD相比，还需要添加缓存逻辑和刷新后数据处理的逻辑。通过插件机制集成这个功能方便吗？

**Comment by maojj** [comment]
下拉刷新的 loading  要一起做的话比较麻烦了。下拉的loading 和 Networking 的loading
 分开处理倒是比较方便的。

**Comment by SpaceStar2016** [comment]
怎么样添加插件，求指教一下小弟 @Huang-Libo

**Comment by Huang-Libo** [comment]
@SpaceStar2016 参考：https://github.com/yuantiku/YTKNetwork/issues/185

**Comment by maojj** [comment]
Demo 工程里面已经有样例代码，  在 YTKNetworkDemo/Accessory 目录下
```
            //[YTKAlertUtils hideLoadingAlertView:_animatingView];
```
这里换自己的 HUD 等即可实现。
