### ISSUE TITLE
怎么给后台发送一个json 类型的参数？

### ISSUE THREAD

**Issue by QinKingHan** [yuantiku/YTKNetwork#196]
我把字典 转换为json ,我这边打印jsonString 是正常的json 数据
  NSData *data = [NSJSONSerialization dataWithJSONObject:dic options:kNilOptions error:nil];
 NSString *jsonString = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];

但发送到后台就 变乱码啦，请求头我也设置了 application/json;charset=UTF-8

**Comment by QinKingHan** [comment]
- (id)requestArgument {
    return @{ @"body": _body };
}
怎么把 body 这个key 去掉

**Comment by maojj** [comment]
正常设置 requestArgument， 然后改 requestSerializerType 为 json
```
- (YTKRequestSerializerType)requestSerializerType {
    return YTKRequestSerializerTypeJSON;
}
```

**Comment by wongwenlei** [comment]
请问，我按照这样做body字段还是没有取消啊，是还要设置什么吗

**Comment by QQzheng** [comment]
请问怎么传递的，我一直都是报错

**Comment by wongwenlei** [comment]
我是使用buildCustomUrlRequest方法重写请求，使用setHTTPBody搞定的
