### ISSUE TITLE
能让支持carthage吗？

### ISSUE THREAD

**Issue by xiafeng1** [yuantiku/YTKNetwork#197]
最近在使用carthage来管理第三方库，能否也支持carthage呢？

**Comment by maojj** [comment]
我抽时间弄一下

**Comment by maojj** [comment]
尝试了下失败了，原因有两个：
1. YTKNetwork 依赖 AFNetworking 2.x 版本，暂不支持 3.x 版本, 2.x 最新版本为2.6.3 不支持 carthage， 这个是主要原因
2. AFDownloadRequestOperation 也不支持 carthage。 虽然支持 cargthage 的时候可以将 AFDownloadRequestOperation 加入到 YTKNetwork 来生成 Framework 但是不好，可能别的地方也用到了。

所以  YTKNetwork 1.x 版本应该不会支持 carthage 了。 期待 YTKNetwork 2.0 吧

**Comment by maojj** [comment]
AFN-3.x 分支 支持了

**Comment by maojj** [comment]
YTKNetwork 2.0  已发布，基于AFN 3.x， 已支持 carthage
