### ISSUE TITLE
关于版本缓存

### ISSUE THREAD

**Issue by JessieHu** [yuantiku/YTKNetwork#198]
1. 按版本缓存, 什么时候去更新版本?  - (long long)cacheVersion; 这个方法重写的话, 不是写死了么? 请教教我. 最好有例子.
2. - (id)cacheSensitiveData; 这个方法如何使用? 请教教我. 最好有例子.
3. 如果修改了用户信息, 然后用这个方法saveJsonResponseToCacheFile:写入了获取信息的接口, 那么查看用户信息时, 如何判断用缓存还是拉取最新数据? 请教教我. 最好有例子.

**Comment by maojj** [comment]
1. cacheVersion 这个只针对你api 的返回值可能数据结构有更新，cache 的数据虽没有过期但已经不能用了，所以有这个设计。
每个版本应该是写死的。  例如： 1.0 版本的 app，某个api cacheversion 为1，  1.1 该api 返回结构未改，cacheversion 还是返回1。   但 2.0 的时候 api 返回结构改了， 所以  cacheversion 应该更新，例如 改为2. 这样再缓存未过期的时候 就能强制丢掉 1.x 版本api 缓存的旧数据。

2， 3， 这两个问题我不特别清楚   @lancy

**Comment by lancy** [comment]
1. cacheVersion 一般是服务端在其他地方返回的，重载的时候带上，如果 cacheVersion 和上次不一样，就会发请求。
2. cacheSensitiveData 是在 cacheVersion 的基础上，再加上一些敏感数据，例如，加上 userId，这样当 userId 变化的时候，即事 cacheVersion 没有变，也会重新发请求
3. YTKRequest: -(BOOL)isDataFromCache

**Comment by Huang-Libo** [comment]
@maojj @lancy 
cacheVersion应该是在实现每个API的时候重写的吧，为何又说是从服务端返回的呢？猿题库的客户端调用哪个版本的API是由客户端决定的还是服务端决定的？

另外我看高级教程里面有YTKUrlFilterProtocol可以为每个网络请求加上客户端的版本号作为参数，这个参数和cacheVersion有何联系？

**Comment by skyline75489** [comment]
@Huang-Libo  

1. `cacheVersion`是重载方法，不过不意味着是写死的。通过重载很容易可以实现把服务器返回值当中的某一个字段作为 `cacheVersion` 返回。这与调用什么 API 并无关系。
2. `YTKUrlFilterProtocol` 是作为请求方为了统一加入请求参数使用的，与 `cacheVersion` 也没有直接联系。

**Comment by Huang-Libo** [comment]
@skyline75489 秒懂，👍

**Comment by lilin87788** [comment]
@skyline75489  通过重载很容易可以实现把服务器返回值当中的某一个字段作为 cacheVersion 返回 这一句话 其实我哈是不是很理解，能具体说明一下吗
