### ISSUE TITLE
正常请求 但Finish request = null 

### ISSUE THREAD

**Issue by shengguoqiang** [yuantiku/YTKNetwork#199]
你好！@猿题库团队 我这边遇到了这样的问题：页面跳转时 常发现某个之前没有问题的请求，返回的时候出现 Finish request = null 的情况，不是偶现，将请求强行放入主线程之后，情况有所缓解，但还是会出现，想请教一下大神！

**Comment by maojj** [comment]
Finish request = null  是log 输出还是什么？

另外 贴下代码？
