### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by hamilyjing** [yuantiku/YTKNetwork#200]
0	PANewToapAPP	0x00000001017a249c	btg_signalHandler (in PANewToapAPP) (BTGCrashCatcher.m (Line 196)) + 24323228 
1	libsystem_platform.dylib	0x0000000180df193c	_sigtramp + 52 
2	CoreFoundation	0x000000018107a2c4	<redacted> + 148 
3	PANewToapAPP	0x0000000101588794	-[YTKNetworkAgent handleRequestResult:] (in PANewToapAPP) (YTKNetworkAgent.m (Line 264)) + 22120340 
4	PANewToapAPP	0x000000010158805c	__33-[YTKNetworkAgent ytk_addRequst:]_block_invoke.169 (in PANewToapAPP) (YTKNetworkAgent.m (Line 174)) + 22118492 
5	PANewToapAPP	0x000000010145eb34	__64-[AFHTTPRequestOperation setCompletionBlockWithSuccess:failure:]_block_invoke.31 (in PANewToapAPP) (AFHTTPRequestOperation.m (Line 131)) + 20900660 
6	libdispatch.dylib	0x0000000180bdd4bc	<redacted> + 24 
7	libdispatch.dylib	0x0000000180bdd47c	<redacted> + 16 
8	libdispatch.dylib	0x0000000180be2b84	_dispatch_main_queue_callback_4CF + 1844 
9	CoreFoundation	0x0000000181148d50	<redacted> + 12 
10	CoreFoundation	0x0000000181146bb8	<redacted> + 1628 
11	CoreFoundation	0x0000000181070c50	CFRunLoopRunSpecific + 384 
12	GraphicsServices	0x0000000182958088	GSEventRunModal + 180 
13	UIKit	0x000000018635a088	UIApplicationMain + 204 
14	PANewToapAPP	0x00000001013afec8	main (in PANewToapAPP) (main.m (Line 18)) + 20184776 
15	libdyld.dylib	0x0000000180c0e8b8	<redacted> + 4 

code：YTKBaseRequest *request = _requestsRecord[key];

**Comment by skyline75489** [comment]
哥这不是完整堆栈吧...

**Comment by Huang-Libo** [comment]
贴个代码看看呗@hamilyjing

**Comment by hamilyjing** [comment]
这个是通过Bugtags反馈的crash信息@skyline75489

**Comment by hamilyjing** [comment]
不知道贴啥代码@Huang-Libo

**Comment by skyline75489** [comment]
@hamilyjing  上面应该有崩溃的具体信息吧，就是崩溃原因

**Comment by zhuozhuo** [comment]
这个问题修复了么？也遇到了，次数统计还挺多。
