### ISSUE TITLE
测试发现断点续传下载功能无效?

### ISSUE THREAD

**Issue by liman123** [yuantiku/YTKNetwork#202]
#import <YTKNetwork/YTKNetwork.h>

    @interface DownloadRequest : YTKRequest

    @end

    #import "DownloadRequest.h"

    @implementation DownloadRequest

        - (NSString *)requestUrl {
            return @"http://wiki.lbsyun.baidu.com/cms/iossdk/sdk/BaiduMap_IOSSDK_v3.0_All.zip";
        }

       - (NSString *)resumableDownloadPath {
        return [[NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask,    YES) objectAtIndex:0] stringByAppendingPathComponent:@"test.zip"];
        }

        - (AFDownloadProgressBlock)resumableDownloadProgressBlock
        {
        return ^(AFDownloadRequestOperation *operation, NSInteger bytesRead, long long totalBytesRead, long long totalBytesExpected, long long totalBytesReadForFile, long long totalBytesExpectedToReadForFile) {
        
            float percentDone = totalBytesReadForFile/(float)totalBytesExpectedToReadForFile;
            NSLog(@">>>>>>>>> %f", percentDone);
            };
        }

    @end

测试时,等到我看到nslog达到0.5左右时,关闭了项目,然后再跑一次
发现nslog还是从0开始.... (真机9.3.3测试的)

**Comment by skyline75489** [comment]
`NSCachesDirectory` 不是可靠的存储路径，随时可能被清除。

**Comment by lileichuan** [comment]
- (NSString *)resumableDownloadPath {
    NSString *folderPath = Textbook_Folder(_textbook.ID);
    if (![[NSFileManager defaultManager]fileExistsAtPath:folderPath]) {
        [[NSFileManager defaultManager]createDirectoryAtPath:folderPath withIntermediateDirectories:YES attributes:nil error:nil];
    }
    NSString *downloadPath = [folderPath stringByAppendingPathComponent:_textbook.fileURL.lastPathComponent];
    return downloadPath;
}
测试，重新下载，不会断点续传。

**Comment by skyline75489** [comment]
YTKNetwork 2 基于系统 NSURLSessionDownloadTask 的 resume 功能，重写了断点续传功能。测试代码在这里 https://github.com/yuantiku/YTKNetwork/blob/master/YTKNetworkTests/YTKResumableDownloadTests.m

**Comment by songzeyao** [comment]
不要重新编译安装项目 关闭后打开即可 重新编译安装会改变你的downloadPath

**Comment by songzeyao** [comment]
不要重新编译安装项目,关闭后打开即可,重新编译安装会改变你的downloadPath

**Comment by skyline75489** [comment]
楼上 +1。重新编译会导致 Document 路径改变，也会导致之前存储的数据失效

**Comment by maojj** [comment]
先关了 有问题再reopen
