### ISSUE TITLE
什么时候能够适配3.0

### ISSUE THREAD

**Issue by jianjianhao** [yuantiku/YTKNetwork#204]

**Comment by skyline75489** [comment]
AFN-3.X 分支正在开发中，See https://github.com/yuantiku/YTKNetwork/tree/AFN-3.X

有兴趣可以把代码拉下了试用一下。

**Comment by maojj** [comment]
YTKNetwork 2.0  已发布，基于AFN 3.x

**Comment by Huang-Libo** [comment]
@maojj CocoaPods什么时候发布2.0版呢？这会搜索还是v1.3.0

**Comment by skyline75489** [comment]
请更新一下 pod 仓库

**Comment by maojj** [comment]
pod repo update 然后再搜

**Comment by Huang-Libo** [comment]
@skyline75489  pod repo update之后搜到了。另外，v1.0以下的CocoaPods还支持多久？

**Comment by maojj** [comment]
1.3.0 会一直可用的，给那些不想升级 2.0 的用户

**Comment by Huang-Libo** [comment]
升级到2.0之后感觉非常好，框架会识别多次发送的相同的request并作适当的处理，断点下载也更强大了，建议使用者都升升升！

**Comment by maojj** [comment]
@Huang-Libo 近期我们有两个 app 会升级到 2.0， 欢迎大家升级。
