### ISSUE TITLE
请求回调方法里面怎么打印完整的请求url包含参数的

### ISSUE THREAD

**Issue by xiaohuapunk** [yuantiku/YTKNetwork#205]
如题：我想在请求回调方法里面打印完整的请求url 含参数的？
(lldb) po request.requestOperation.response.URL 调试的时候po可以显示结果，但是request.requestOperation.response.URL这样直接访问url却报错，求解

**Comment by skyline75489** [comment]
贴下代码吧，怎么报的错

**Comment by xiaohuapunk** [comment]
没有报错，只是想打印一下完整的url（拼接好参数的url），request.requestOperation 我直接打印这个对象了，也可以拿到url

**Comment by skyline75489** [comment]
那可能是打印的时机不对，所以我感觉还是要贴下代码，没有代码不好看是哪里有问题

**Comment by ysk666666** [comment]
不是特别能理解你的需求。我们这边是在测试环境的下面，可以把post的参数可以以get的方式拼接，以方便有什么问题时发给服务端的同学查看。
下面说下我的实现：
YTKNetworkAgent.m中addRequest:方法加在最后调用一下以下方法就可以了。
`
-(NSString *)convertToURL:(AFHTTPRequestOperation *)op {
    NSString * baseURLString = op.request.URL.absoluteString;
    NSString * parametersURLString = [[NSString alloc] initWithData:op.request.HTTPBody encoding:NSUTF8StringEncoding];
    if (parametersURLString.length != 0) {
        if ([baseURLString rangeOfString:@"?"].location != NSNotFound) {
            baseURLString = [baseURLString stringByAppendingString:[NSString stringWithFormat:@"&%@",parametersURLString]];
        } else {
            baseURLString = [baseURLString stringByAppendingString:[NSString stringWithFormat:@"?%@",parametersURLString]];
        }
    }
    return baseURLString;
}
`
有兴趣可以在此处按照cURL规则拼接一下，打印出来也挺好的吧
不知道是否对你解决问题有什么帮助。

**Comment by maojj** [comment]
https://github.com/mattt/FormatterKit/blob/master/FormatterKit/TTTURLRequestFormatter.h#L41

可以用 matt 大神写的 TTTURLRequestFormatter
