### ISSUE TITLE
YTKBatchRequest 能否监听完成的请求数...

### ISSUE THREAD

**Issue by chx632996066** [yuantiku/YTKNetwork#209]
比如说要上传9张图片，然后装到YTKBatchRequest里，需要要显示正在上传1/9。。。正在上传2/9。。。

**Comment by maojj** [comment]
现有的 batchRequest 没有这个功能，如果需要，可以考虑写个 子类 加上相关逻辑。 
可以用 YTKBatchRequest.m 的私有变量 finishedCount
