### ISSUE TITLE
有没有迁移AFNetworking3.0的计划呢？

### ISSUE THREAD

**Issue by White8818** [yuantiku/YTKNetwork#210]
😊

**Comment by Sunnyyoung** [comment]
@White8818 
都不认真看的？https://github.com/yuantiku/YTKNetwork/tree/AFN-3.X

**Comment by White8818** [comment]
@Sunnyyoung 
😂确实没仔细看，三克油~我关issues

**Comment by maojj** [comment]
YTKNetwork 2.0  已发布，基于AFN 3.x
