### ISSUE TITLE
YTKBatchRequest 不能调用最后一个request的completeBlock

### ISSUE THREAD

**Issue by TuWei1992** [yuantiku/YTKNetwork#212]
RT, `YTKNetworkAgent` 的`handleRequestResult`方法中,  由于先执行了`delegate`的方法,  所以最后一个req的compBlock还没执行, 就被清理了, 同理, failureBlock 也一样

**Comment by maojj** [comment]
确实

**Comment by ysk666666** [comment]
这个问题是不是可以理解为：因为有失败的网络回调导致所有的request都stop了，导致时间较长的但是能成功的网络回调的delegate已经被置空了呢。
还有一个问题，需要 @maojj 确认一下，之前我有提交过一个pl，专门搞了成功和失败的属性变量来存储这个requestArray里面的成功和失败的网络回调，因为我理解的批量请求应该就是不论成功和失败都要走一遍（不能因为中途有失败的就停止接受其他的网络回调的结果了），然后再统一的处理。
还是我本身就理解错了这个Issues了？

**Comment by maojj** [comment]
这个 issue 是说 如果所有 request 都成功了，最后一个的 block 是不会执行的， 因为YTKNetworkAgent 先调用的 delegate 方法， 再调用的 block，  而delegate  batchRequest 则是清了 block， 所以在YTKNetworkAgent 调用block 的时候， block 已经没了就不会调用了。

**Comment by lancy** [comment]
`BatchRequset` 和 `ChainRequest` 最早由 @tangqiaoboy 设计；

我的理解： `BatchRequest` 和 `ChainRequest` 其实是接管了单个 `request` 的回调，并且在其中任何一个 `request` 失败的时候，立刻停止所有其他 `request`，并触发 `batchReqeustFailed`

从这个设计上来看，不应该在单个 `request` 中使用 `completionBlock`，我倾向于认为这不属于一个 bug，属于误用。
@tangqiaoboy 看一下？

**Comment by lancy** [comment]
对于这个 issue 所提到的情况，为了防止误用
我们目前计划移除对`BatchRequest`和`ChainRequest`中，单个`request`的回调支持。在当前的版本中，会接管单个`request`的`delegate`；之后的版本，会在启动时清理掉单个`request`的`completionBlock`，来维持和`delegate`一致的行为。

**Comment by maojj** [comment]
Done by 55d88ae20a6401fad176b31203fee8cb2fe749b4
