### ISSUE TITLE
请求失败的blcok里面怎么还会输出正确数据呢？

### ISSUE THREAD

**Issue by lwy121810** [yuantiku/YTKNetwork#215]
第一次使用YTK 真的有点懵逼啊 普通的网络请求 我是直接用一个继承自YTKRequest的类的对象调用startWithCompletionBlockWithSuccess方法 然后block走的是failure部分 但是还是有请求的数据打印出来啊 而且打印了request.requestOperationError信息为null 如果请求成功不是走Success部分么 代码是这样的:
```
WYURLCommon *reg = [[WYURLCommon alloc] init];
    reg.ignoreCache = YES;
    [reg startWithCompletionBlockWithSuccess:^(__kindof YTKBaseRequest *request) {
        id obj = request.responseJSONObject;
        NSLog(@"success ------- %@" , obj);
    } failure:^(__kindof YTKBaseRequest *request) {
        id obj = request.responseJSONObject;
        NSError *error = request.requestOperationError;
        NSLog(@"failure ------- %@ error --  %@" , obj , error);
    }];`
```

WYURLCommon继承自YTKRequest 重写了 
```
- (NSString *)requestUrl - (YTKRequestMethod)requestMethod
- (YTKRequestSerializerType)requestSerializerType
```
方法

**Comment by skyline75489** [comment]
失败不一定是网络请求失败，看这种情况应该是序列化失败了

**Comment by maojj** [comment]
以及 jsonValidate 失败也会这样

**Comment by lwy121810** [comment]
恩 解决了 我重写了- (id)jsonValidator方法 但是一开始不明白这个方法是干嘛的 直接返回一个字典
在这个方法里面应该返回的类型应该是跟接口数据的类型是一样的吧 而且字段应该是数据里包含的一个字段（不知道有没有理解错误） 接口里返回的是数组 我还是返回了字典 所以出了错误 现在已经好了 谢谢

**Comment by lwy121810** [comment]
还有一点就是如果因为网络或者其他问题出现解析错误 错误信息是在failure里打印request.requestOperationError信息么？

**Comment by maojj** [comment]
@lwy121810  jsonValidator 大致是你理解的那样， 用于检查返回数据的结构。 一个 对应的 key，name 要一致。 value 就是对应的类型，可能有嵌套。

response 序列化失败的错误信息是 AFN 做的， 我也没细看，可以去查下。

**Comment by lancy** [comment]
目前还有一些错误没有包含在 `request.error` 里面，包括 `jsonValidator` 失败，后续会优化

**Comment by lwy121810** [comment]
嗯嗯 谢谢了

**Comment by gank0326** [comment]
还有我把返回的responseString放在网页里验证是标准的json格式啊，为什么还会失败

**Comment by lwy121810** [comment]
看看你验证格式方法是不是写错了 我的是- (id)jsonValidator方法里面返回数据类型错误了 我的情况是接口数据返回的类型是数组 我在- (id)jsonValidator返回了字典类型 还有就是看下返回字段是否正确

**Comment by maojj** [comment]
#227 有详情， @gank0326 问题的原因 是 `content-type` 的问题 ， 已解决
