### ISSUE TITLE
请问unacceptable content-type: text/html 如何处理?

### ISSUE THREAD

**Issue by HongWeiChen** [yuantiku/YTKNetwork#216]
大意如上,公司的接口一般都要求text/html的content-Type 但是AF已经被YTK封装在里头了.无法对这个做出修改

**Comment by SuooL** [comment]
一个解决方案是 可以使用 `buildCustomUrlRequest` 定制 API 请求.

**Comment by skyline75489** [comment]
或者像 #131 里面一样用 KVC，不过并不推荐。还是服务器端尽量返回正确的类型比较好。

**Comment by kkkelicheng** [comment]
改一下源码吧...
AFJSONSerialization 里面
立马见效..
