### ISSUE TITLE
YTKNetworkPrivate.h不再暴露，YTKUrlFilterProtocol该怎么使用？

### ISSUE THREAD

**Issue by Huang-Libo** [yuantiku/YTKNetwork#217]
在高级教程中，YTKUrlFilterProtocol里面有调用YTKNetworkPrivate的方法：
```
 [YTKNetworkPrivate urlStringWithOriginUrlString:originUrl appendParameters:_arguments]
```
请问这个该怎么做出改变呢？

**Comment by skyline75489** [comment]
建议实现自己的一套 URL 工具类来进行 URL 拼接等操作。`urlStringWithOriginUrlString:appendParameters` 这个方法的实现可以作为参考实现。

**Comment by Huang-Libo** [comment]
@skyline75489 那YTKNetwork统一加版本号的功能就不能再使用了，需要自己写？以后有其他新的计划吗？

**Comment by skyline75489** [comment]
YTKUrlFilterProtocol 本身只是一个接口，没有限定内部的实现。YTKNetworkPrivate 里的这个拼接 URL 方法也只是做了一个把参数拼接到 URL 后面的工作，因此完全可以自己实现类似的工具类来做这个操作。

为了兼容 iOS7，现在 YTKNetworkPrivate 里的实现其实是有些别扭的（因为要避开使用 NSURLQueryItem）。并且这里面的实现也不保证不会变更。因此对于使用者来说，自己维护一个具有类似功能的工具类是更好的选择。

**Comment by Huang-Libo** [comment]
@skyline75489 分析的很好👍

**Comment by skyline75489** [comment]
文档的更新后续会跟进
