### ISSUE TITLE
如何统一在requestUrl路径中添加版本号？

### ISSUE THREAD

**Issue by Huang-Libo** [yuantiku/YTKNetwork#219]
猿题库的客户端应该是通过客户端传参数来确定调用哪个接口的，并可以通过filter很方便地统一加上参数。如果版本信息放在url路径中，有没有什么方法可以比较方便地做统一设置呢？

**Comment by maojj** [comment]
路径中统一设置版本号等信息可以利用 ``` YTKUrlFilterProtocol ```
在 YTKNetworkConfig 里面 添加 urlFilters

例如 url 里面写个{version} :  http://www.yuantiku.com/{version}/users/info
自定义 YTKUrlFilter 实现
```
- (NSString *)filterUrl:(NSString *)originUrl withRequest:(YTKBaseRequest *)request {
    // 替换 originUrl 中的 {version}， 并返回
}
```
