### ISSUE TITLE
在MVVM中，网络请求和HUD绑定后(使用YTKAnimatingRequestAccessory)，如何避免在viewModel层引入UIKit？

### ISSUE THREAD

**Issue by Huang-Libo** [yuantiku/YTKNetwork#220]
按照MVVM的设计，viewModel层不应该出现UIKit相关的内容，但是网络请求需要写在viewModel中，而此时我们要把网络请求和透明指示层绑定起来，就必须把UIView对象传入到viewModel中以绑定网络请求，此时就必须引入UIKit。请问这种情境有解决方案吗？

**Comment by lancy** [comment]
把 VM 和请求绑定不就好了？

YTKAnimatingRequestAccessory 只是一个样例；你可以自己定制自己的 accessory。

P.S. 这个 issue 涉及到的设计问题，和 YTKNetwork 关系不是很大，就不在这里继续讨论了。
