### ISSUE TITLE
YTKRequest _cache 有个bug

### ISSUE THREAD

**Issue by wzi90921** [yuantiku/YTKNetwork#221]
前提开启缓存
```
UserApi *api = [UserApi new]
if([api cacheJson]){
 .....
}
[api start];
```
[api cacheJson] 这句代码会让 YTKRequest _cache有值。
[api start];该代码执行完毕后，会掉[self responseJSONObject]获取返回对象
源代码中
```
- (id)responseJSONObject {
    if (_cacheJson) {
        return _cacheJson;
    } else {
        return [super responseJSONObject];
    }
}
```
这样的话，会返回_cache 的内容，而不是最新返回的 [super responseJSONObject]数据
YTKRequest 在这里个文件里面，没有找到在请求回来后，对cache值的更新，或者置空。

我修改了源码
```
- (void)saveJsonResponseToCacheFile:(id)jsonResponse {
    if ([self cacheTimeInSeconds] > 0 && ![self isDataFromCache]) {
        _cacheJson = jsonResponse;====添加了改代码
        NSDictionary *json = jsonResponse;
        if (json != nil) {
            [NSKeyedArchiver archiveRootObject:json toFile:[self cacheFilePath]];
            [NSKeyedArchiver archiveRootObject:@([self cacheVersion]) toFile:[self cacheVersionFilePath]];
        }
    }
}
```

是否我的理解有误，还是其他的原因。我的修改方案的是否合理可行。。
希望能得到回复

**Comment by skyline75489** [comment]
新的 YTKNetwork 2.0 中已经重写了 cache 这部分逻辑，可以处理这种情况了。

同时，不建议重用同一个 Request 实例多次进行请求。

**Comment by lancy** [comment]
YTKNetwork 被设计为一个 request 只能使用一次；所以使用了 `cacheJson` 之后，这个 request 被认为已经使用，理论上不应该继续调用 `start`；

2.0 版本对这部分逻辑进行了修改；现在可以使用 `startWithoutCache` 进行 cache 的清理并发出请求；

**Comment by wzi90921** [comment]
刚刚更新了2.0的版本，这个版本 Request 怎么获取到 cache，cacheJSON 之类的属性都放在.m文件，并没有暴露出来

**Comment by skyline75489** [comment]
正常做 start，然后取 responseJSONObject 。或者手动调用 loadCache，然后取 responseJSONObject

**Comment by wzi90921** [comment]
为什么2.0版本。
#import "YTKNetworkPrivate.h"
#import <YTKNetwork/YTKNetworkPrivate.h>
这两种写法都引用不了你们这个文件，其他文件都可以正常引用。。
在我们的代码中 需要用到 YTKNetworkPrivate 封装的某些方法

**Comment by maojj** [comment]
之所以叫 Private 其实就是不想给外面用的，可能随时改动。Pod 描述里面没有把它公开。

**Comment by wzi90921** [comment]
不好意思了，问题比较多。。
我更新了2.0之后，所有请求都返回404，在1.3的时候，是正常的，是否用法改变了吗。指导文档里面没有更新

**Comment by skyline75489** [comment]
所有的请求？能不能贴一下具体的错误，把 request.error 打印出来

**Comment by wzi90921** [comment]
move failed:Request failed: unacceptable content-type: text/html
content-type我的接口应该是text/json, 或者application/json。
我们使用默认的
- (YTKResponseSerializerType)responseSerializerType {
    return YTKResponseSerializerTypeJSON;
}
怎么会变成 text/html

**Comment by skyline75489** [comment]
看 error 就是返回的 content_type 不对的原因了，可以抓包看一下具体的响应

**Comment by wzi90921** [comment]
Request 哪里可以配置，应该是新版本的默认值做了修改。。

**Comment by skyline75489** [comment]
Request 的配置相对于 1.x 来说没有做改动，包括响应处理也是跟 1.X 的行为是类似的。

**Comment by maojj** [comment]
返回数据的 `content-type` 是服务端设置的， JSON 数据返回值是 `text/html` 的话， 需要服务端改下。
