### ISSUE TITLE
更新了2.0版本后，所有请求都返回404，是不是其他人也有遇到这种情况

### ISSUE THREAD

**Issue by wzi90921** [yuantiku/YTKNetwork#222]

**Comment by skyline75489** [comment]
请帖一下具体的报错信息

**Comment by jiao808813** [comment]
我也遇到了，不过把baseUrl改成如下形式就好了，点com后面除了端口号不要加别的东西！
YTKNetworkConfig *config = [YTKNetworkConfig sharedConfig];   
    config.baseUrl = @"http://www.xxxxx.com";

**Comment by wzi90921** [comment]
@skyline75489 真的可以了。。
这个是啥限制呢

**Comment by wzi90921** [comment]
试出了两种不会报错的配置url方法
baseUrl:  http://example.com
requestUrl:   /v1/foo
-------------------------
baseUrl:  http://example.com/v1/         (最后面的斜杠可加可不加)
requestUrl:   foo        (不可以斜杠开头,不然拼出来的url是：http://example.com/foo,)

知识点
NSURL *baseURL = [NSURL URLWithString:@"http://example.com/v1/"];

[NSURL URLWithString:@"foo" relativeToURL:baseURL];
// http://example.com/v1/foo

[NSURL URLWithString:@"foo?bar=baz" relativeToURL:baseURL];
// http://example.com/v1/foo?bar=baz

[NSURL URLWithString:@"/foo" relativeToURL:baseURL];
// http://example.com/foo

[NSURL URLWithString:@"foo/" relativeToURL:baseURL];
// http://example.com/v1/foo

[NSURL URLWithString:@"/foo/" relativeToURL:baseURL];
// http://example.com/foo/

[NSURL URLWithString:@"http://example2.com/" relativeToURL:baseURL];
// http://example2.com/

**Comment by lancy** [comment]
https://github.com/yuantiku/YTKNetwork/blob/master/BasicGuide.md

**Comment by Huang-Libo** [comment]
@lancy 目前我是这样写的
```
baseUrl: http://example.com/v1/ (最后面的斜杠可加可不加)
requestUrl: foo (不可以斜杠开头,不然拼出来的url是：http://example.com/foo
```
接下来的版本还支持这种写法吗

**Comment by skyline75489** [comment]
从设计上讲，`baseUrl` 应该只包含 host，也就是 `www.example.com` 这部分。不过使用你提到的这种方法也能够拼接出正确的的 URL，只要注意 `requestUrl` 不要加 /。

这个限制的来源也是上面提到的苹果对于 `relativeToURL:baseURL` 这个方法的实现。
