### ISSUE TITLE
在8.1上崩溃 dyld: Symbol not found: _NSURLSessionTaskPriorityDefault

### ISSUE THREAD

**Issue by keepyounger** [yuantiku/YTKNetwork#223]
日志如下
dyld: Symbol not found: _NSURLSessionTaskPriorityDefault
  Referenced from: /Users/lixy/Library/Developer/CoreSimulator/Devices/8C39E637-60EC-4DE9-BE8C-D8B14E367D2D/data/Containers/Bundle/Application/B413FFCA-2A5A-47AE-AA35-F4B85B58E280/yfw.app/Frameworks/YTKNetwork.framework/YTKNetwork
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.1.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation
 in /Users/lixy/Library/Developer/CoreSimulator/Devices/8C39E637-60EC-4DE9-BE8C-D8B14E367D2D/data/Containers/Bundle/Application/B413FFCA-2A5A-47AE-AA35-F4B85B58E280/yfw.app/Frameworks/YTKNetwork.framework/YTKNetwork

**Comment by skyline75489** [comment]
感谢反馈，看样子是苹果内部 Framework 的一个 bug。请问是使用 Carthage 还是 Pod 安装的？

**Comment by skyline75489** [comment]
http://stackoverflow.com/questions/24043532/dyld-symbol-not-found-nsurlauthenticationmethodclientcertificate-when-trying 

这里提供的解决方案是调整依赖 Framework 的顺序

**Comment by keepyounger** [comment]
恩 找到解决方案了 添加 cfnetwork framework 到YTKNetwork (貌似添加到项目工程里面无效) [参考](https://github.com/onevcat/Kingfisher/pull/78)

**Comment by keepyounger** [comment]
谢谢，不过最好的解决方案，好像是在pod里面指明需要CFNetwork 
![880b6128-a516-4e54-8125-f9dde0d332cc](https://cloud.githubusercontent.com/assets/6264752/18341933/12931dc8-75df-11e6-9766-a46473cde906.png)

**Comment by maojj** [comment]
下个版本 2.0.1 会带上。

**Comment by maojj** [comment]
2.0.1 已发， fixed

**Comment by wmfgithub** [comment]
我使用的是carthage 安装的，最新版本还是没有解决8.x真机崩溃的问题。_NSURLSessionTaskPriorityDefault
  Referenced from: /private/var/mobile/Containers/Bundle/Application/9261DC58-1CD8-40BC-8BE7-FD5284A36E7F/chehou.app/Frameworks/YTKNetwork.framework/YTKNetwork
  Expected in: /System/Library/Frameworks/Foundation.framework/Foundation
 in /private/var/mobile/Containers/Bundle/Application/9261DC58-1CD8-40BC-8BE7-FD5284A36E7F/chehou.app/Frameworks/YTKNetwork.framework/YTKNetwork
