### ISSUE TITLE
2.x版如何让缓存永不过期？

### ISSUE THREAD

**Issue by jiao808813** [yuantiku/YTKNetwork#225]
1.x版的cacheJson只要cacheTimeInSeconds>0就永远能取到值，而2.x版的responseObject，responseData还是会过期，是要把cacheTimeInSeconds设为非常大才行么？

**Comment by lancy** [comment]
嗯，设一个超大的值，比如十年或者 NSIntegerMax

**Comment by jiao808813** [comment]
恩，cacheTimeInSeconds设为NSIntegerMax了。

我发现了个2.x新的问题，Demo中
    GetUserInfoApi *api = [[GetUserInfoApi alloc] initWithUserId:userId];
    if ([api loadCacheWithError:nil]) {
        NSDictionary *messageA = [api responseJSONObject];
        NSLog(@"messageA = %@", messageA);
    }
    [api startWithCompletionBlockWithSuccess:^(YTKBaseRequest *request) {
                NSDictionary *messageB = [request responseJSONObject];
        NSLog(@"messageB = %@", messageB);
    } failure:^(YTKBaseRequest *request) {
        NSLog(@"failed");
    }];
执行UpdateUserInfoApi（有个更新信息接口）后，发现GetUserInfoApi获得messageA和messageB永远都是第一次请求的数据并不会更新。

然后我又换个方法
    GetUserInfoApi *api = [[GetUserInfoApi alloc] initWithUserId:userId];
    if ([api loadCacheWithError:nil]) {
        NSDictionary *messageA = [api responseJSONObject];
        NSLog(@"messageA = %@", messageA);
    }
    GetUserInfoApi *apiIgnoreCache= [[GetUserInfoApi alloc] initWithUserId:userId];
    apiIgnoreCache.ignoreCache = YES;
    [apiIgnoreCache startWithCompletionBlockWithSuccess:^(YTKBaseRequest *request) {
                NSDictionary *messageB = [request responseJSONObject];
        NSLog(@"messageB = %@", messageB);
    } failure:^(YTKBaseRequest *request) {
        NSLog(@"failed");
    }];
messageA和messageB 倒是更新了，但是无网络的情况下（status code = 0, error = 似乎已断开与互联网的连接）请求两次后messageA会被清空，请问如何解决?1.x版本就不会这样子。

**Comment by jiao808813** [comment]
简单点的意思就是如何在即使请求报错(例如断网的情况下)也不会清空缓存？

**Comment by skyline75489** [comment]
这里不是断网导致的清理缓存，而是 `ignoreCache` 设置为 YES 导致的。

**Comment by skyline75489** [comment]
把 `ignoreCache` 设置为 YES 会导致内部调用 `startWithoutCache`，现在的设计是一旦执行 `startWithoutCache` 就会清理掉缓存。

**Comment by jiao808813** [comment]
可是正如我所说，如果不设置ignoreCache = YES,按照第一种方式每次请求结果都是第一次缓存的数据(cacheTimeInSeconds = NSIntegerMax,因为我要永久保存)

**Comment by skyline75489** [comment]
我其实不太理解你这儿的具体需求是什么？

**Comment by jiao808813** [comment]
需求很简单，永远都有一份缓存保留以备断网

**Comment by skyline75489** [comment]
这样的需求跟 YTK 现在的设计是有些不相符的。现在的设计当中 cacheTime 过期之后才会更新，手动更新就认为是不再需要旧的 cache，于是进行清理。永远都有一份缓存，就意味着既要保留旧的 cache ，又要每次更新不删除。目前没有暴露这样的 接口出来。可以手动在子类中实现一个这样的接口，替代使用 `startWithoutCache`。

**Comment by jiao808813** [comment]
恩，那我知道暂时怎么解决了，多谢了呢

**Comment by lancy** [comment]
这个问题我们还要再商议一下，是改回和 1.x 行为一致，还是保持 2.x 的现状。

**Comment by maojj** [comment]
改成跟 1.x 一致  see 7a44fca1068888b5b8da9844e494c35689b8f34f
