### ISSUE TITLE
5. CFNetwork需要显示加为依赖来避免 iOS 8.1 上的 Crash

### ISSUE THREAD

**Issue by wzi90921** [yuantiku/YTKNetwork#226]
我已经在  General--Linked Frameworks and Libraries 里面添加 了CFNextwork
在项目中 #import <CFNetwork/CFNetwork.h>

为什么还是YTKNetworkAgent
            default:
                request.requestTask.priority = NSURLSessionTaskPriorityDefault;
                break;
这句代码Crash。
是否我添加的方式有问题

**Comment by skyline75489** [comment]
See #223

**Comment by maojj** [comment]
2.0.1 已发， fixed

**Comment by huipengo** [comment]
不用pod，将YTKNetwork植入项目里面，按着先移除CFnetwork，再添加了CFNetwork，改变了顺序，status也改成了optional还是会crash，何解？
