### ISSUE TITLE
接口直接走到失败的block，但是responseString是对的

### ISSUE THREAD

**Issue by gank0326** [yuantiku/YTKNetwork#227]
使用方法 startWithCompletionBlockWithSuccess
直接进了failure:^(YTKBaseRequest *request) 的block
 
Request MSRequest failed, status code = 200, error = (null)
(lldb) po request.responseString
{"status":0,"msg":"ok","data":{"pageNo":"1","rows":"20","total_nums":"285","list":[{"tid":"379","city":"北京","type":"0","keyword":"全部

**Comment by gank0326** [comment]
https://github.com/yuantiku/YTKNetwork/issues/215
看了一下这个，但是我在老版本上会成功啊，也没有重写了- (id)jsonValidator方法

**Comment by gank0326** [comment]
还有我把返回的responseString放在网页里验证是标准的json格式啊，为什么还会失败

**Comment by gank0326** [comment]
跟了下代码，responseString 在这里序列化失败了！
 case YTKResponseSerializerTypeJSON:
                    request.responseObject = [self.jsonResponseSerializer responseObjectForResponse:task.response data:request.responseData error:&serializationError];
                    request.responseJSONObject = request.responseObject;
                    break;
但是老版本可以啊，这边我也没做过任何改动，是不是新的序列方法有问题呢？

**Comment by skyline75489** [comment]
有可能是返回的 ContentType 错误了

**Comment by gank0326** [comment]
现在是text/html  ，我怕让服务器改了会影响线上版本。这个可以客户端自己改？

**Comment by gank0326** [comment]
@"NSLocalizedDescription" : @"Request failed: unacceptable content-type: text/html"	
key	__NSCFConstantString *	@"NSLocalizedDescription"
value	__NSCFString *	@"Request failed: unacceptable content-type: text/html"


这种报错，老版本的猿题库可以解析的

**Comment by gank0326** [comment]
是因为新版本这个设置无效了吗？
YTKNetworkAgent *agent = [YTKNetworkAgent sharedAgent];
    [agent setValue:[NSSet setWithObjects:@"application/json", @"text/plain", @"text/javascript", @"text/json",@"text/html",@"text/css", nil]

**Comment by gank0326** [comment]
除了上面说的kvc设置，我还能怎么设置上
manager.responseSerializer.acceptableContentTypes = [manager.responseSerializer.acceptableContentTypes setByAddingObject:@"text/html"];

**Comment by maojj** [comment]
个人觉得最好还是服务器按标准写对 contentType，  测一下以前的客户端。

**Comment by skyline75489** [comment]
`YTKNetworkAgent` 有一个私有的 `- (AFHTTPSessionManager *)manager` 方法，可以试着调用一下。还是推荐服务器改成正确的返回 Content-Type，这样更加严谨

**Comment by gank0326** [comment]
谢谢两位大神，我决定让服务器改！
