### ISSUE TITLE
YTKNetwork 2.1.0版本中，用iP地址作为BaseURL请求失败

### ISSUE THREAD

**Issue by originalix** [yuantiku/YTKNetwork#232]
在1.3.0版本中 类似于 `http://192.168.12.240:8090`这样的BaseUrl是可以正常请求的

而在今天升级了2.1.0版本后，这样的BaseURL请求失败，我也仔细看了之前的issues和新的文档。

配置BaseUrl的时候只能用Host地址，那么请问用ip地址请求的该怎么解决呢

**Comment by originalix** [comment]
error = unsupported URL

**Comment by originalix** [comment]
解决了

**Comment by XDB-Chang** [comment]
@originalix 请问你是怎么解决的？
