### ISSUE TITLE
统一为网络请求加上一些参数

### ISSUE THREAD

**Issue by ly92** [yuantiku/YTKNetwork#235]
在2.0版本中，YTKNetworkPrivate.h 将会成为私有头文件，所有依赖于此头文件的方法将不再可用。
那么按照“YTKNetwork 使用高级教程”里面说的“YTKUrlFilterProtocol 接口”不能使用了？如何统一为网络请求加上一些参数呢？

**Comment by ly92** [comment]
yuantiku所给出的demo上的解决方式：

就是将 [YTKNetworkPrivate urlStringWithOriginUrlString:originUrl appendParameters:_arguments];这个方法提取出来放在自己建立的类文件里面，详情参考demo，希望能够帮助大家。


- (NSString *)urlStringWithOriginUrlString:(NSString *)originUrlString appendParameters:(NSDictionary *)parameters {
    NSString *filteredUrl = originUrlString;
    NSString *paraUrlString = [self urlParametersStringFromParameters:parameters];
    if (paraUrlString && paraUrlString.length > 0) {
        if ([originUrlString rangeOfString:@"?"].location != NSNotFound) {
            filteredUrl = [filteredUrl stringByAppendingString:paraUrlString];
        } else {
            filteredUrl = [filteredUrl stringByAppendingFormat:@"?%@", [paraUrlString substringFromIndex:1]];
        }
        return filteredUrl;
    } else {
        return originUrlString;
    }
}

- (NSString *)urlParametersStringFromParameters:(NSDictionary *)parameters {
    NSMutableString *urlParametersString = [[NSMutableString alloc] initWithString:@""];
    if (parameters && parameters.count > 0) {
        for (NSString *key in parameters) {
            NSString *value = parameters[key];
            value = [NSString stringWithFormat:@"%@",value];
            value = [self urlEncode:value];
            [urlParametersString appendFormat:@"&%@=%@", key, value];
        }
    }
    return urlParametersString;
}

- (NSString*)urlEncode:(NSString*)str {
    return AFPercentEscapedStringFromString(str);
}


建议yuantiku的作者能过几时更新帮助文件

**Comment by skyline75489** [comment]
文档后续会更新，感谢关注 😄
