### ISSUE TITLE
request.responseJSONObject将原始json中的null转换成了"<null>"

### ISSUE THREAD

**Issue by Huang-Libo** [yuantiku/YTKNetwork#237]
我本想用jsonValidator来验证后台返回的json的合法性：json中有一个字段在有值的时候是字符串类型，无值的时候是null类型，但是发现该字段为null时jsonValidator一直检验通过。后来我打印request.responseJSONObject发现null被转换成了`"<null>"`。请问为什么默认要把null转换为`"<null>"`？

**Comment by skyline75489** [comment]
这是 `NSJSONSerialization` 的行为，与 YTK 或者 AFN 都没有关系。而且实质上 null 是以 `NSNull` 的形式存储的，并不是字符串，只是 NSLog 打印出来显示为 `<null>`。
