### ISSUE TITLE
替换2.0后,编译时出现错误

### ISSUE THREAD

**Issue by wjmwjmwb** [yuantiku/YTKNetwork#238]
`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AFDownloadRequestOperation", referenced from:
      objc-class-ref in libYTKNetwork.a(YTKNetworkAgent.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by skyline75489** [comment]
试试 Clean & Build

**Comment by wjmwjmwb** [comment]
试过了,不行.甚至pod 删除 都不行. 我在研究一下.貌似不是YTKNetworking的问题. 因为用32位机的时候,pod所有的类库都出问题了.....

**Comment by skyline75489** [comment]
看起来像是 Arch 没配置好。

**Comment by MrGuys** [comment]
我也出现了这个问题，楼主怎么解决的啊

**Comment by hllGitHub** [comment]
1. Clean & Build 如果没效果再尝试第二种方案
2. cd ~/Library/Developer/Xcode/DerivedData，清除对应的缓存数据，再重新运行或者重复第一步即可
