### ISSUE TITLE
在AFNetworking3.0.0版本下报错

### ISSUE THREAD

**Issue by jianjianhao** [yuantiku/YTKNetwork#239]
<img width="748" alt="bc754116-d061-4ce2-a05f-b5e264d31f41" src="https://cloud.githubusercontent.com/assets/12797357/18903725/4c6783a0-858d-11e6-9895-1ab290c724d0.png">
AFNetworking3.1.0没问题

**Comment by skyline75489** [comment]
目测是 AFN 3.1 才暴露出的这两个接口， @lancy  是改一下实现还是提一下依赖的版本？

**Comment by lancy** [comment]
如果 3.1 和 3.0 系统要求是一致的，同时 3.1 向下兼容的话，我觉得直接升依赖版本比较好。
