### ISSUE TITLE
现在的YTKNetwork的版本是多少？ 我看readme说是有2.x 但是我在pod上搜索到的是1.3.0版本

### ISSUE THREAD

**Issue by lwy121810** [yuantiku/YTKNetwork#245]
rt，我是想把AFN升到3.x版本的 ，还有就是如何打印完整的url？我现在是把YTKNetworkConfig的baseUrl和YTKBaseRequest的requestArgument 拼接起来

**Comment by Sunnyyoung** [comment]
@lwy121810 
执行`pod repo update`之后再`pod search YTKNetwork`
可以通过`request.originalRequest.URL.absoluteString`获取完整URL String

**Comment by skyline75489** [comment]
Thanks @Sunnyyoung 

Closed for now.

**Comment by lwy121810** [comment]
恩 已经升到2.0.1版本了 并把1.3.0升级到2.x版本的错误改了 但是在请求数据的时候会请求失败 在1.3.0是能请求成功的 错误信息是Error Domain=com.alamofire.error.serialization.response Code=-1016 "Request failed: unacceptable content-type: text/html" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7f8d0b922d20> 该在哪里添加acceptableContentTypes类型？

**Comment by SuooL** [comment]
content-type 建议让服务端修改为正确的...YTK 没有暴露这个修改的接口

**Comment by Sunnyyoung** [comment]
@lwy121810 @SuooL 
建议服务端修改返回类型，毕竟`text/html`是不规范的。
实在不行，参考 #131 通过KVC修改。

**Comment by lwy121810** [comment]
服务端修改的话应该怎么修改？ 后台不在我们这 交流起来可能没那么方便 还有就是用kvc的话[[YTKNetworkAgent sharedAgent] setValue:contentTypeSet forKeyPath:@"_manager.responseSerializer.acceptableContentTypes"];应该在哪里配置？ 我是在appdelete里面在配置了baseUrl之后就配置的 可是还是报这个错误

**Comment by lwy121810** [comment]
而且遇到一个好奇葩的问题 我在用1.x版本的时候解析我们的登录接口 能够解析成功 并且返回值正确 但我把ytk升级到2.0.1之后 因为没有设置content-type成功 会报上面的错误信息 所以我直接用的afn解析的 也是能解析成功 但是返回值跟用ytk1.x版本的返回值是相反的... 不理解了... 求大神帮忙*—*
