### ISSUE TITLE
请问使用YTK1.x版本的话会影响上架不 上架的话需要升级到2.x版本么？

### ISSUE THREAD

**Issue by lwy121810** [yuantiku/YTKNetwork#246]
rt 还有一个就是重写了buildCustomUrlRequest 但是返回nil的话 设置的requestUrl requestArgument还是有效的是吧

**Comment by skyline75489** [comment]
Github is not a place for technical support .Please refer to the latest documentation.

Github 不是提供技术支持的地方，请查阅最新文档。
