### ISSUE TITLE
url项目名截掉了

### ISSUE THREAD

**Issue by teng555teng** [yuantiku/YTKNetwork#247]
YTKNetworkConfig *config = [YTKNetworkConfig sharedConfig];
  config.baseUrl = @"http://192.168.4.210:8080/lxx";

发送请求是时lxx 不见了

**Comment by skyline75489** [comment]
See https://github.com/yuantiku/YTKNetwork/blob/master/Docs/2.0_MigrationGuide_cn.md#url-%E6%8B%BC%E6%8E%A5
