### ISSUE TITLE
请问 服务器是text/html类型的，在2.版本下怎么配置?

### ISSUE THREAD

**Issue by MrGuys** [yuantiku/YTKNetwork#250]
请问 服务器是text/html类型的，在2.版本下怎么配置?

**Comment by WeiweiYuan810** [comment]
```
        //设置可接受的数据类型
        YTKNetworkAgent *agent = [YTKNetworkAgent sharedAgent];
        NSSet *acceptableContentTypes = [NSSet setWithObjects:@"application/json", @"text/json", @"text/javascript", @"text/plain", @"text/html", @"text/css", nil];
        NSString *keypath = @"jsonResponseSerializer.acceptableContentTypes";
        @try {
            [agent setValue:acceptableContentTypes forKeyPath:keypath];
        } @catch (NSException *exception) {
            NSLog(@"%@", exception);
        } @finally {
            
        }
```

**Comment by skyline75489** [comment]
@WeiweiYuan810  Thansk. Duplicate of #216  and/or #233. Closed

**Comment by KFAaron** [comment]
也可以这样：
先设置rquest的responseSerializerType为YTKResponseSerializerTypeHTTP：
- (YTKResponseSerializerType)responseSerializerType {
    return YTKResponseSerializerTypeHTTP;
}
然后把返回的data转成json数据：
NSError *jsonError = nil;
        id jsonResponse = [NSJSONSerialization JSONObjectWithData:request.responseData options:NSJSONReadingMutableContainers error:&jsonError];
