### ISSUE TITLE
YTKUrlFilterProtocol可以为get请求统一加上参数，那么post请求如何统一加参数呢？

### ISSUE THREAD

**Issue by blackchena** [yuantiku/YTKNetwork#252]
还有 统一给header加上公用key value 又需要怎么实现呢？现在我是继承了YTKRequest实现的

**Comment by skyline75489** [comment]
Refer to https://github.com/yuantiku/YTKNetwork/blob/master/YTKNetwork/YTKBaseRequest.h#L315 and https://github.com/yuantiku/YTKNetwork/blob/master/YTKNetwork/YTKBaseRequest.h#L319
