### ISSUE TITLE
返回结果，如何处理公共参数。

### ISSUE THREAD

**Issue by iphone5s** [yuantiku/YTKNetwork#254]
所有返回结果 的code。要判断 code = -1的情况。如果登录失效 则注销登录。。 怎么统一检查所有接口的返回code

**Comment by skyline75489** [comment]
`requestCompleteFilter`

**Comment by skyline75489** [comment]
本身 YTKNetwork 的设计倾向于使用 HTTP 返回码来确定请求的成功与否，自定义 code 的判断可以去继承 YTKRequest 自己实现一个基类的方法
