### ISSUE TITLE
DELETE方法需要传入参数时出错

### ISSUE THREAD

**Issue by hahaChaoRen** [yuantiku/YTKNetwork#257]
使用YTKRequestMethodDELETE时需要传入json参数,报status code = 400错误.

**Comment by skyline75489** [comment]
使用的具体代码，以及如何知道不是服务器端错误的？

**Comment by hahaChaoRen** [comment]
`- (YTKRequestMethod)requestMethod {
    return YTKRequestMethodDELETE;
}

- (YTKRequestSerializerType)requestSerializerType {
    return YTKRequestSerializerTypeJSON;
}

- (id)requestArgument {
    NSMutableArray *msgIds = [NSMutableArray array];
    for (MsgItem *msg in _messages) {
        [msgIds addObject:msg.sid];
    }
    NSDictionary *parameter = @{@"messageIds":msgIds};
    return parameter;
}`
原来使用ASI时,使用delete方法传json参数需要设置haveBuiltPostBody=yes,不知道是不是和这有关.

**Comment by skyline75489** [comment]
@lancy  我刚查了下资料，按道理 DELETE 这种方法，就不应该有参数 😓

**Comment by hahaChaoRen** [comment]
我查了下,也这样说...但是后台要求这么传...但想想如果做批量删除的话,传个数组是比较方便...
之前用的ASI设置haveBuiltPostBody=yes就可以传过去...

**Comment by lancy** [comment]
@skyline75489 所以是 AFN 禁止了 DELETE 方法传body？

**Comment by skyline75489** [comment]
感觉是未定义的行为，怎么实现都不算错

**Comment by skyline75489** [comment]
@hahaChaoRen  直接使用 AFNetworking 是什么结果？

**Comment by hahaChaoRen** [comment]
一样的也是报400的错误  看了下afn代码  好像afn的get  put  delete不允许传body 直接将参数拼在url后面...

**Comment by skyline75489** [comment]
那就跟 YTKNetwork 关系不大了。

Not our problem. Won'fix.

**Comment by skyline75489** [comment]
那就跟 YTKNetwork 关系不大了。

Not our problem. Won'fix.

**Comment by DevQC** [comment]
需要修改这里
<img width="737" alt="image" src="https://user-images.githubusercontent.com/15279159/103164227-72be1280-4843-11eb-84c3-635557ca764b.png">
的配置

**Comment by DevQC** [comment]
AFURLRequestSerialization 文件里面这个属性把里面的Delete移除就可以

/**
 HTTP methods for which serialized requests will encode parameters as a query string. `GET`, `HEAD`, and `DELETE` by default.
 */
@property (nonatomic, strong) NSSet <NSString *> *HTTPMethodsEncodingParametersInURI;
