### ISSUE TITLE
使用缓存问题

### ISSUE THREAD

**Issue by xuanyi0627** [yuantiku/YTKNetwork#259]
更新新版本后使用缓存，设置了缓存时间
```
- (NSInteger)cacheTimeInSeconds {
    return 180;
}
```
然后调用
```
LoadGuyListApi *load = [[LoadGuyListApi alloc] initWithPage:1];
    if ([load loadCacheWithError:nil]) {
        // [load responseJSONObject]
    }
```
缓存有，但是发现在时间内并没有做新的网络请求。
请问这个怎么回事。

**Comment by tangqiaoboy** [comment]
参见 https://github.com/yuantiku/YTKNetwork/blob/master/Docs/ProGuide_cn.md 上的说明，你需要在加载缓存后，再调用一次 start 方法。在缓存有效期内，start 方法会直接返回结果，不会真正发网络请求。

**Comment by xuanyi0627** [comment]
怎么可以既拿到缓存又发出真正的请求？

**Comment by skyline75489** [comment]
`startWithoutCache` 可以用来无视缓存发送请求，请求成功后会更新缓存。

请提问前先阅读有关[文档](https://github.com/yuantiku/YTKNetwork/tree/master/Docs) 和 代码注释[文档](http://cocoadocs.org/docsets/YTKNetwork/2.0.1/)，Github 不是做技术支持的地方 。
