### ISSUE TITLE
关于 url 最后 斜杠的拼接

### ISSUE THREAD

**Issue by wangweijia** [yuantiku/YTKNetwork#260]
2.x 版本（我用了pod 上最新的）
在 YTKNetworkAgent.m中的
`- (NSString *)buildRequestUrl:(YTKBaseRequest *)request`
127行
```
    if (baseUrl.length > 0 && ![baseUrl hasSuffix:@"/"]) {
        url = [url URLByAppendingPathComponent:@""];
    }
```
实在不明白为什么要在最后添加 一个斜杠。。。

我遇到的问题是 当我 下载一个文件的时候url 例如：
`http://fs.xxx.com/3/xxxxxxxx.amr`
最终的处理效果是：
`http://fs.xxx.com/3/xxxxxxxx.amr/`
我觉得这个最后的斜杠完全没有必要，而且我那服务器是无法识别这个带斜杠的url的。

这个斜杠是有什么特殊用途才刻意添加上去的吗？？？？

**Comment by skyline75489** [comment]
See https://github.com/yuantiku/YTKNetwork/blob/master/Docs/2.0_MigrationGuide_cn.md#url-%E6%8B%BC%E6%8E%A5

`baseURL` 应该只包含 Host 部分。
