### ISSUE TITLE
YTKNetwork如何更新缓存

### ISSUE THREAD

**Issue by shine0007** [yuantiku/YTKNetwork#262]
比如用户信息 按时间缓存内容 但是我更新我的用户信息后 如何更新缓存？

**Comment by Huang-Libo** [comment]
在你的request子类中重写：

```
- (id)cacheSensitiveData {
    return _userInfo;
}
```

**Comment by skyline75489** [comment]
Github 不是提供技术支持的地方，issue 只负责处理 YTKNetwork 本身的问题， 有关使用的问题请仔细阅读 [开发文档](https://github.com/yuantiku/YTKNetwork/tree/master/Docs) 以及 [程序文档](http://cocoadocs.org/docsets/YTKNetwork/2.0.2/)

**Comment by shine0007** [comment]
@skyline75489 你更新缓存的方法 文档里没有详细介绍。 基本文档和高级文档都看过了。

**Comment by skyline75489** [comment]
由于功能较多，教程内容无法全面涵盖，具体内容以 [程序注释文档](http://cocoadocs.org/docsets/YTKNetwork/) 为准

**Comment by shine0007** [comment]
@skyline75489 我就一个问题，我的分页数据 按时间缓存后 再不过期的情况下 我新发布一个分页数据 如何加入到缓存里 让我的分页列表数据更新？一直没找到解决方案。

**Comment by shine0007** [comment]
帮忙能不能解决下这个困难。

**Comment by lancy** [comment]
@Huang-Libo 的回答是对的，可以用`cacheSensitiveData`来标示

**Comment by shine0007** [comment]
谢谢 但是我在文档里无法找到有关cacheSensitiveData的用法 能不能提供个参考给我们开发者。非常喜欢YTKNetwork这个网络库。 但是缓存更新 一直同步最新数据 一直在这个库中 一直我得不到正确的解决方式。求帮助。

**Comment by skyline75489** [comment]
See http://cocoadocs.org/docsets/YTKNetwork/2.0.2/Classes/YTKRequest.html#properties `cacheSensitiveData`
