### ISSUE TITLE
如何统一设置 http header ?

### ISSUE THREAD

**Issue by Huang-Libo** [yuantiku/YTKNetwork#263]
在给后台接口传版本号时，经常把这个参数写在 http header 里面，并且 YTKNetwork 已经有了相应的接口去实现这个功能：

```
- (NSDictionary<NSString *,NSString *> *)requestHeaderFieldValueDictionary;
```

我的问题是，由于每个 request 都需要在 header 里面添加这个参数（而且版本号都是一样的），有没有更便捷的方法为所有 request 添加这个参数？

**Comment by maojj** [comment]
可以写个父类处理。

**Comment by Huang-Libo** [comment]
@maojj
在自己的 request 类和 YTKRequest 之间加一个类？这个方式挺好，不过如果能像 YTKUrlFilterProtocol 那样为所有接口统一参数，会更好

**Comment by skyline75489** [comment]
Header 作为 HTTP 协议的一部分，是有自己的语义的。在我看来，如非必要应尽量避免使用 Header。

**Comment by maojj** [comment]
我们一般用 config 把公共参数 写到 url 后面的普通参数里面。

**Comment by Huang-Libo** [comment]
@maojj 把版本号通过“ url 路径”或“ url 参数”返回给后台比较常见，也很好用。不过在某些情境中，版本号放在header中更好。这个 issue 有可能无关技术，而是设计模式。
@skyline75489 版本号放 header 中是一些后端猿友给的建议，以适应 RESTFUL 接口。

**Comment by dengV** [comment]
在分类里面hook
