### ISSUE TITLE
关于图片上传的提问

### ISSUE THREAD

**Issue by DamonRao** [yuantiku/YTKNetwork#264]
运行demo里的uploadImageAPi时，上传也不成功返回的结果时Null，
其中添加了这几个覆盖方法：

```
-(void)requestCompleteFilter{
    NSLog(@"upload success!!!");
}
-(void)requestFailedFilter{
    NSLog(@"upload filed!!!");
}
- (YTKRequestSerializerType)requestSerializerType {
    return YTKRequestSerializerTypeJSON;
}
- (YTKResponseSerializerType)responseSerializerType {
    return YTKResponseSerializerTypeJSON;
}
-(id)requestArgument{
    return nil;
}
```

**Comment by skyline75489** [comment]
Demo 目前只是展示库的用法，代码本身是不可用的

**Comment by DamonRao** [comment]
我自己新建一个工程，把demo的uploadImageApi代码考过来，运行都没有反应啊，这个uploadImageApi里的设置方法是不对的吗

**Comment by SuooL** [comment]
能给点具体的代码吗?

**Comment by DamonRao** [comment]
就是把get改成上传图片啊，- (void)sendBatchRequest {
    NSString *img1=@"1.png";
     NSString *img2=@"2.png";
     NSString *img3=@"3.png";
   UploadImageApi *a = [[UploadImageApi alloc] initWithImage:GetImage(img1)];
    UploadImageApi *b = [[UploadImageApi alloc] initWithImage:GetImage(img2)];
    UploadImageApi *c = [[UploadImageApi alloc] initWithImage:GetImage(img3)];

    YTKBatchRequest *batchRequest = [[YTKBatchRequest alloc] initWithRequestArray:@[a, b, c]];
    [batchRequest startWithCompletionBlockWithSuccess:^(YTKBatchRequest *batchRequest) {
        NSLog(@"succeed");
        NSArray *requests = batchRequest.requestArray;
        UploadImageApi *a = (UploadImageApi *)requests[0];
        UploadImageApi *b = (UploadImageApi *)requests[1];
        UploadImageApi *c = (UploadImageApi *)requests[2];
        // deal with requests result ...
        NSLog(@"%@, %@, %@", a, b, c);
    } failure:^(YTKBatchRequest *batchRequest) {
        NSLog(@"failed");
    }];
}

**Comment by DamonRao** [comment]
输出UploadAPI reponseImage为空值
