### ISSUE TITLE
为什么YTKRequest和YTKBatchRequest都支持block回调，而YTKChainRequest却不支持呢？

### ISSUE THREAD

**Issue by WeiweiYuan810** [yuantiku/YTKNetwork#265]

**Comment by skyline75489** [comment]
Duplicate of #266 . Closed

**Comment by xilin** [comment]
这俩问题不算duplicate吧？关注点不一样。这个问题是为啥YTKChainRequest只给了delegate方法没给`startWithCompletionBlockWithSuccess:failure:`
