### ISSUE TITLE
YTKNetwork在我清理缓存的时候清理不掉，有办法吗？

### ISSUE THREAD

**Issue by shine0007** [yuantiku/YTKNetwork#267]
NSString *directoryPath=[NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES) firstObject];
   NSArray *subpaths = [[NSFileManager defaultManager] contentsOfDirectoryAtPath:directoryPath error:nil];

```
    for (NSString *subPath in subpaths) {
        NSString *filePath = [directoryPath stringByAppendingPathComponent:subPath];
        [[NSFileManager defaultManager] removeItemAtPath:filePath error:nil];
    }
    //返回主线程
    dispatch_async(dispatch_get_main_queue(), ^{
        block();
    });
```

发现清理不掉YTKNetwork缓存的文字信息。如何操作？可以完全删除

**Comment by skyline75489** [comment]
缓存不在 Cache 里，See https://github.com/yuantiku/YTKNetwork/blob/master/YTKNetwork/YTKRequest.m#L388
