### ISSUE TITLE
关于断点续下时的缓存文件

### ISSUE THREAD

**Issue by guibin1989** [yuantiku/YTKNetwork#268]
看了一下源码，下载请求在出现错误时会把之前下的数据写到incompleteDownloadTempPathForDownloadPath中，但是没看到有任何地方去删除这些数据。如果这个请求错误之后直接被cancel掉了，是不是这个缓存就一直在这里了？

**Comment by skyline75489** [comment]
存放距离是临时文件夹，不会一直存在

**Comment by guibin1989** [comment]
@skyline75489 所以存放目录不是一个稳定位置，可能过几天后就没有了。我本来想拿来做大文件的下载管理器，看来不太适合。
还有我之前查了一点关于NSTemporary​Directory的资料，还是建议用完就删掉的，因为系统的自动删除是没法预计的。
[http://nshipster.com/nstemporarydirectory/](http://nshipster.com/nstemporarydirectory/)

**Comment by skyline75489** [comment]
YTKNetwork 的断点续传主要受到 [AFDownloadRequestOperation](https://github.com/steipete/AFDownloadRequestOperation) 的影响，目前只支持比较简单的续传操作，没有做复杂的下载续传管理等。
