### ISSUE TITLE
请求不通接口

### ISSUE THREAD

**Issue by 5jiao1yuan** [yuantiku/YTKNetwork#270]
Request FCLogin failed, status code = 0, error = unsupported URL

**Comment by Sunnyyoung** [comment]
`error = unsupported URL`
你哪里看不懂

**Comment by skyline75489** [comment]
Github 不是提供技术支持的地方，issue 只负责处理 YTKNetwork 本身的问题， 有关使用的问题请仔细阅读 [开发文档](https://github.com/yuantiku/YTKNetwork/tree/master/Docs) 以及 [程序文档](http://cocoadocs.org/docsets/YTKNetwork)。

**Comment by 5jiao1yuan** [comment]
尊敬的猿题库同行们你们好：
					前几天看到你们的网络框架写的挺好，我想加入到我们的新项目中，但是遇到了一个问题，你们的文档我觉得有问题所以在这里叨扰。

					在/Docs <https://github.com/yuantiku/YTKNetwork/tree/master/Docs>/ProGuide_cn.md文件中
				YTKUrlFilterProtocol 接口

- (NSString *)filterUrl:(NSString *)originUrl withRequest:(YTKBaseRequest *)request {

    return [YTKUrlArgumentsFilter urlStringWithOriginUrlString:originUrl appendParameters:_arguments];
}



这个方法调用报错，仔细查看这个urlStringWithOriginUrlString:originUrl appendParameters:_arguments
方法不是YTKUrlArgumentsFilter而是YTKNetworkPrivate类的方法，但是这个类又没有在#import "YTKNetwork.h"
中，所以我想加入公共参数没法实现。

望兄弟们提供技术支持，小白不胜感激！

**Comment by 5jiao1yuan** [comment]
小白电话17718321685，邮箱就是这个

发自我的 iPhone
