### ISSUE TITLE
requestFailedFilter 回调 

### ISSUE THREAD

**Issue by SuooL** [yuantiku/YTKNetwork#274]
问题描述 Issue Description
请求明明成功获取到了数据，但是却回调了 requestFailedFilter ，请问是为什么呢？
![image](https://cloud.githubusercontent.com/assets/6235813/20051477/2ca20620-a50a-11e6-9cb1-2e0d30a2606e.png)

现在出现的问题是同一个请求获取到同样的数据，有时回调requestCompleteFilter，有时回调requestFailedFilter 。

**Comment by wzi90921** [comment]
我也遇到同样的问题
