### ISSUE TITLE
缓存使用问题

### ISSUE THREAD

**Issue by wang542413041** [yuantiku/YTKNetwork#276]
### 提出问题前请先确认完成了下列几项步骤 New Issue Checklist

* [x] 我已经阅读过 [贡献指南](CONTRIBUTING.md) I have read and understood the [CONTRIBUTING guide](CONTRIBUTING.md)
* [x] 我已经阅读过 [程序文档]((http://cocoadocs.org/docsets/YTKNetwork)) I have read the [Documentation](http://cocoadocs.org/docsets/YTKNetwork)
* [x] 我已经证实这个问题来源于 YTKNetwork 本身，而不是其所依赖的 [AFNetworking](https://github.com/AFNetworking/AFNetworking) I have confirmed that this issue is caused by YTKNetwork, not [AFNetworking](https://github.com/AFNetworking/AFNetworking)
* [x] 我已经在项目的 [问题列表](https://github.com/yuantiku/YTKNetwork/issues) 中搜索过并且没有找到类似问题 I have searched for a similar issue in the [project](https://github.com/yuantiku/YTKNetwork/issues) and found none

### 问题描述 Issue Description

请给出所提出问题的详尽描述，包括具体的错误信息，打印的堆栈等等，以及重现此问题的具体步骤。

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by wang542413041** [comment]
#import "MyPageApi.h"

@interface MyPageApi ()
@property (copy, nonatomic) NSString *dvc_id;
@property (copy, nonatomic) NSString *dvc_info;
@property (copy, nonatomic) NSString *mem_no;
@end

@implementation MyPageApi

- (id)initWithDvc_id:(NSString *)dvc_id dvc_info:(NSString *)dvc_info mem_no:(NSString *)mem_no {
    if (self = [super init]) {
        _dvc_id = dvc_id;
        _dvc_info = dvc_info;
        _mem_no = mem_no;
    }
    return self;
}

- (NSString *)requestUrl {
    return @"/api/mypage/mypage";
}

- (id)requestArgument {
    return @{@"dvc_id": _dvc_id,
             @"dvc_info": _dvc_info,
             @"mem_no": _mem_no};
}

- (YTKRequestMethod)requestMethod {
    return YTKRequestMethodGET;
}

- (YTKRequestSerializerType)requestSerializerType {
    return YTKRequestSerializerTypeHTTP;
}

- (YTKResponseSerializerType)responseSerializerType {
    return YTKResponseSerializerTypeHTTP;
}

//此处返回一个大于0的时间，由于时间过短会超过验证时间，所以设置了一天的缓存时间
- (NSInteger)cacheTimeInSeconds {
    return 24*60*60;
}


----------------------------分割线-----------------------------
 MyPageApi *api = [[MyPageApi alloc] initWithDvc_id:dvc_id dvc_info:dvc_info mem_no:mem_no];
    NSError *loadCacheError = nil;
    if ([api loadCacheWithError:&loadCacheError]) {
        id obj = [NSJSONSerialization JSONObjectWithData:[api responseData] options:NSJSONReadingMutableContainers error:nil];
        if ([obj[k_rtn_cd] isEqualToString:k_rtn_cd_100]) {
            //1.成功
            self.myinfoModel = [[REMyPageModel alloc] initWithDictionary:obj[k_rtn_data] error:nil];
            [self.myTableView reloadData];
            [self loginParam];
        } else if ([obj[k_rtn_cd] isEqualToString:k_rtn_cd_000]) {
            //2.崩溃
        } else if ([obj[k_rtn_cd] isEqualToString:k_rtn_cd_400]) {
            //3.检查服务通知
        } else if ([obj[k_rtn_cd] isEqualToString:k_rtn_cd_500]) {
            //4.APP强制升级
        }
    }
    if (loadCacheError) {
        NSString *errStr = [NSString stringWithFormat:@"%@", loadCacheError];
        Alert(errStr);
    }
    [api startWithoutCache];//下载数据没有缓存
    [api startWithCompletionBlockWithSuccess:^(__kindof YTKBaseRequest * _Nonnull request) {
        id obj = [NSJSONSerialization JSONObjectWithData:request.responseData options:NSJSONReadingMutableContainers error:nil];
        NSLog(@"我的界面信息\n%@", obj);
    } failure:^(__kindof YTKBaseRequest * _Nonnull request) {
        [[MaterialHUD sharedHud] hidden];
    }];

//缓存获取的数据
{
    "rtn_cd" = 100;
    "rtn_data" =     {
        "pnt_amt" = "9365.799999999999";
    };
    "rtn_msg" = SUCCESS;
}

//再次请求获得的数据
{
    "rtn_cd" = 100;
    "rtn_data" =     {
        "pnt_amt" = "9365.799999999999";
    };
    "rtn_msg" = SUCCESS;
}

问题：我对数据开启了缓存处理，缓存时间为1天。当我每次使用startWithBlock的时候，如何对数据进行更新？为什么我每次取出来的数据都是我缓存的数据。和高级使用教程中所介绍的数据获取结果不一致，关于这一点我很费解。

**Comment by wang542413041** [comment]
在实际开发中，有一些内容可能会加载很慢，我们想先显示上次的内容，等加载成功后，再用最新的内容替换上次的内容。也有时候，由于网络处于断开状态，为了更加友好，我们想显示上次缓存中的内容。这个时候，可以使用 YTKReqeust 的直接加载缓存的高级用法。

具体的方法是直接使用 YTKRequest 的 - (BOOL)loadCacheWithError: 方法，即可获得上次缓存的内容。当然，你需要把 - (NSInteger)cacheTimeInSeconds 覆盖，返回一个大于等于 0 的值，这样才能开启 YTKRequest 的缓存功能，否则默认情况下，缓存功能是关闭的。

以下是一个示例，我们在加载用户信息前，先取得上次加载的内容，然后再发送请求，请求成功后再更新界面：

- (void)loadCacheData {
    NSString *userId = @"1";
    GetUserInfoApi *api = [[GetUserInfoApi alloc] initWithUserId:userId];
    if ([api loadCacheWithError:nil]) {
        NSDictionary *json = [api responseJSONObject];
        NSLog(@"json = %@", json);
        // show cached data
    }
    [api startWithCompletionBlockWithSuccess:^(YTKBaseRequest *request) {
        NSLog(@"update ui");
    } failure:^(YTKBaseRequest *request) {
        NSLog(@"failed");
    }];
}


这个方法，并不会更新数据。下载下来的数据还是缓存的数据。对此表示很费解。麻烦大神答疑。
如果返回时间大于0，那么下载的时候会在时间内部进行下载。我的api再次请求 并没有真正的进行数据请求，导致我Load完缓存数据后，下载的还是缓存数据。对此非常费解

**Comment by wangyoung0618** [comment]
我也遇到了这个情况，不知道该怎么解决。缓存机制感觉有问题的样子

**Comment by wang542413041** [comment]
项目中大量使用了猿题库这个面向对象的网络API。也只是实现了和AFN相近的功能，甚至有的时候想使用URLCache却不知道如何下手。建议如果使用程度不是很严重的话，更换回AFN。或者基于AFN简单封装的相应开源文件。

**Comment by lancy** [comment]
`loadCacheWithError` 本身不会影响缓存是否过期的判断；所以即使手动读出缓存，在请求启动的时候，仍然会对本地存在的缓存进行过期判断；如果想强制忽略本地缓存；需要使用`startWithoutCache`或`ignoreCache`

更详细的内容请阅读相关文档；
