### ISSUE TITLE
关于YTKNetwork与HTTPDNS库，在HTTPS环境下需要验证证书的问题

### ISSUE THREAD

**Issue by HongWeiChen** [yuantiku/YTKNetwork#282]
项目中有使用到AliCloud的HTTPDNS网络库，HTTPS下需要设置证书，但是除了自定义NSURLRequest紫外，好像没有其他方式可以解决。
YTKNetwork有提供相关的方法吗，还是我只能使用原生的方式去解决？

**Comment by HongWeiChen** [comment]
不知道这样是否能明白，还没吃饭，头晕脑胀，搞了一天.

**Comment by pandaApe** [comment]
@HongWeiChen  我们也要搞了，你有解决吗？

**Comment by skyline75489** [comment]
大体看了一下，如果只是需要设置 NSURLSessionConfiguration 的话，YTKNetwork 2.0.2 已经暴露出来有关接口 cfabe700f2430e4d9c3403a9ce6f0718e659b442

**Comment by pandaApe** [comment]
@HongWeiChen  如果项目可能的话，暂时用下面这个方面, 握手时不进行域名验证
```objc
    AFSecurityPolicy *plicy = [AFSecurityPolicy defaultPolicy];
    plicy.validatesDomainName = NO;
    [YTKNetworkConfig sharedConfig].securityPolicy = plicy;
```
