### ISSUE TITLE
ios 8.2奔溃

### ISSUE THREAD

**Issue by FutureChen** [yuantiku/YTKNetwork#283]
request.requestTask.priority = NSURLSessionTaskPriorityDefault;

运行就崩溃在这里行，没有什么提示信息。

**Comment by huipengo** [comment]
me too

**Comment by skyline75489** [comment]
See #223

**Comment by huipengo** [comment]
I not use pod, don't work

**Comment by skyline75489** [comment]
我们没有打算支持非 CocoaPods 或 Carthage 的引入方式，此问题是苹果框架本身的 bug，请查询 [bugreport.apple.com](https://bugreport.apple.com/) 获得技术支持。
