### ISSUE TITLE
YTKNetworkAgent报错:_block_invoke ,请问这个怎么解决

### ISSUE THREAD

**Issue by callmewenxi** [yuantiku/YTKNetwork#287]
使用1.x版本,线上大量报这个错,大概是0.3%左右,不知道是什么问题
[YTKNetworkAgent handleRequestResult:]/Users/Callmewenxi/nonoliveIos/Pods/YTKNetwork/YTKNetwork/YTKNetworkAgent.m: line 238
 __30-[YTKNetworkAgent addRequest:]_block_invoke.154 /Users/Callmewenxi/nonoliveIos/Pods/YTKNetwork/YTKNetwork/YTKNetworkAgent.m: line 156

**Comment by lancy** [comment]
1.x 版本已经不再维护；
