### ISSUE TITLE
初始化一个全局的 request ， 在成功的Block回调中，再次发起该request 的请求无回调

### ISSUE THREAD

**Issue by zhaoxuezhi** [yuantiku/YTKNetwork#289]
例如如下代码 ：
- (void)beginRequest
{
    if(_index == 5) {
        return;
    }
    [self.request startWithCompletionBlockWithSuccess:^(__kindof HLJBaseRequest * _Nonnull request) {
        _index ++;
        NSLog(@"请求成功----- \n");
        [self beginRequest];
        
    } failure:^(__kindof HLJBaseRequest * _Nonnull request) {
        
    }];  
}

第二次发起请求时回调不回来， 发现式 Agent 类 handleRequestResult: 对  _requestsRecord 字典的处理逻辑导致的，注释掉 removeRequestFromRecord ／ clearCompletionBlock 这两个方法就ok了， 请核实问题并修复， 谢谢

**Comment by skyline75489** [comment]
Request 被设计为只能使用一次的，所以这个行为是预期的。
