### ISSUE TITLE
加载下一页？

### ISSUE THREAD

**Issue by ynot16** [yuantiku/YTKNetwork#291]
如果有加载下一页的需求，库好像没有开发类似接口？

**Comment by ynot16** [comment]
我想的是，在原来加载第一页的API中，新添个是否加载更多的全局标记，根据这个标记来决定请求的参数

**Comment by ynot16** [comment]
但是是否在YTKBaseRequest里面统一提供加载更多的接口会更好？

**Comment by Huang-Libo** [comment]
这种业务逻辑跟网络请求库没关系吧

**Comment by lancy** [comment]
业务需求不在网络库支持的范围；
