### ISSUE TITLE
关于在viewdidload中请求失败的问题

### ISSUE THREAD

**Issue by C-Create** [yuantiku/YTKNetwork#293]
您好，最近在使用YTKNetwork框架，遇到一点问题，如下：
在viewdidload方法中写网络请求方法，会提示如下问题，缺少baseurl，但是我已经在appdelegate中有配置，然而，在viewwillappear方法中写网络请求的话，是可以正常请求到数据的
Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x61800004c600 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=//后缀地址, NSErrorFailingURLKey=//后缀地址, NSLocalizedDescription=unsupported URL}

这是什么问题呢？

### 提出问题前请先确认完成了下列几项步骤 New Issue Checklist

* [ ] 我已经阅读过 [贡献指南](CONTRIBUTING.md) I have read and understood the [CONTRIBUTING guide](CONTRIBUTING.md)
* [ ] 我已经阅读过 [程序文档]((http://cocoadocs.org/docsets/YTKNetwork)) I have read the [Documentation](http://cocoadocs.org/docsets/YTKNetwork)
* [ ] 我已经证实这个问题来源于 YTKNetwork 本身，而不是其所依赖的 [AFNetworking](https://github.com/AFNetworking/AFNetworking) I have confirmed that this issue is caused by YTKNetwork, not [AFNetworking](https://github.com/AFNetworking/AFNetworking)
* [ ] 我已经在项目的 [问题列表](https://github.com/yuantiku/YTKNetwork/issues) 中搜索过并且没有找到类似问题 I have searched for a similar issue in the [project](https://github.com/yuantiku/YTKNetwork/issues) and found none

### 问题描述 Issue Description

请给出所提出问题的详尽描述，包括具体的错误信息，打印的堆栈等等，以及重现此问题的具体步骤。

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by C-Create** [comment]
解决了

**Comment by leasontou** [comment]
解决了，你就不能说下是啥问题？
