### ISSUE TITLE
在 Github Trending 中看到了一个类似 YTKNetwork 的库

### ISSUE THREAD

**Issue by Huang-Libo** [yuantiku/YTKNetwork#294]
目前在 Obj-C 趋势中排第二，看了一下这个库的 Read me，感觉和 YTKNetwork 的用法非常像，不知道那个库的作者有没有用过 YTKNetwork 呢。地址 https://github.com/kangzubin/XMNetworking

**Comment by lancy** [comment]
看了一下，有一些相似的地方，也有一些独特的地方，感觉也不错；
