### ISSUE TITLE
使用这个库怎么配置HTTPS请求

### ISSUE THREAD

**Issue by YWHelp** [yuantiku/YTKNetwork#295]

**Comment by Connerli** [comment]
@YWHelp 接口还是很明显的，你先看下怎么适配AFN，因为YTK是基于AFN框架进行封装的，然后看下YTKNetworkConfig 和YTKNetworkAgent类源码，应该就明白怎么配置了。

**Comment by YWHelp** [comment]
@Connerli   AFN中提供了AFSecurityPolicy这个类是可以设置安全策略的，我应该需要在YTKNetworkConfig这个类中修改一下securityPolicy属性的初始值。
