### ISSUE TITLE
怎样去适配阿里云HTTPDNS

### ISSUE THREAD

**Issue by Shannon-Yang** [yuantiku/YTKNetwork#296]
现在我项目中需要适配https，并且适配阿里云的HTTPDNS，https中如果我添加了阿里云的HTTPDNS，无法通过验证，不能请求，得到“domain不匹配”错误，查看了阿里云的官方文档，给出的方案是需要在NSURLSession中的

`- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task
didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge
 completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential * __nullable credential))completionHandler
{ }`

方法中拿http的header的host，阿里云的适配解决方案：   [https://help.aliyun.com/document_detail/30143.html?spm=5176.doc30143.3.2.fpWt5D](url)
因为我项目用了YTKNetwork  但是YTKNetwork没有相应的方法或者属性去设置，我如何在YTKNetwork中适配HTTPDNS？

**Comment by Huang-Libo** [comment]
可以直接看 AFN 是怎么解决的

**Comment by Shannon-Yang** [comment]
@Huang-Libo 我在AFN中搜到关于httpdns的只有这个链接[https://github.com/AFNetworking/AFNetworking/issues/2954]()，不过貌似都需要改源码才行，有没有一种可行的方法不需要改源码的  🙏🙏

**Comment by skyline75489** [comment]
HTTPDNS 本身就属于比较高级的需求，YTKNetwork 本身没有提供这样的支持。
