### ISSUE TITLE
请求不能写在ViewDidLoad里？

### ISSUE THREAD

**Issue by leasontou** [yuantiku/YTKNetwork#297]
为什么请求不能写在viewDidLoad里？报Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" 。
但是同样的请求放在viewWillAppear就没问题，为何？

**Comment by Huang-Libo** [comment]
连网络请求也要堆到控制器里了么...

**Comment by leasontou** [comment]
总共没几个页面的app，还要搞一堆mvp，mvvm的话，不觉得蛋疼么？

**Comment by lancy** [comment]
请求可以卸载任何地方；
按报错来看，应该是 url 写错了，请检查一下

**Comment by leasontou** [comment]
同一个api，不可能是url问题

**Comment by skyline75489** [comment]
也可能是 `YTKNetworkConfig` 配置的时机问题

**Comment by Richard1900** [comment]
需要注意，baseURL 配置需要早于 window 初始化之前调用。
你遇到的情况可能是先初始化了window，首页加载，viewdidload 中调用网络请求时，baseURL 还没有配置成功。
