### ISSUE TITLE
问个命名规范的问题

### ISSUE THREAD

**Issue by Regansun** [yuantiku/YTKNetwork#298]
为什么基类是baseRequest，可Demo里继承于baseRequest的子类却叫Api？
这有什么具体说法吗？

**Comment by lancy** [comment]
没什么特别的，
基类叫 baseRequest 是继承 iOS 的规范，例如 `NSUrlRequest` 等；
而 API 只是我们猿题库的命名规范而已，API 特指由服务端提供的接口；
