### ISSUE TITLE
如何配置两个服务器地址...

### ISSUE THREAD

**Issue by hahaChaoRen** [yuantiku/YTKNetwork#299]
也就是不同接口走不同服务器...

**Comment by Huang-Libo** [comment]
主要的服务器使用 BaseUrl, 次要的那个你直接在 request 里面写完整的 url 即可

**Comment by hahaChaoRen** [comment]
好吧  也是这样做的

**Comment by lancy** [comment]
重载`YTKBaseRequest`中的`baseUrl`能覆盖 config 中的`baseUrl`
