### ISSUE TITLE
AFNetWorkingManager.responseSerializer.acceptableContentTypes在YTKNetwork中怎么设置呢？

### ISSUE THREAD

**Issue by JaceFu** [yuantiku/YTKNetwork#30]
AFNetWorkingManager.responseSerializer.acceptableContentTypes在YTKNetwork中怎么设置呢？

**Comment by ShrinkLynn** [comment]
我添加了个AFJSONResponseSerializer+htmlSupport扩展，复写了

**Comment by ShrinkLynn** [comment]
@implementation AFJSONResponseSerializer(htmlSupport)
- (instancetype)init {
    self = [super init];
    if (!self) {
        return nil;
    }
    self.acceptableContentTypes = [NSSet setWithObjects:@"application/json", @"text/json", @"text/javascript", @"text/html",nil];
    return self;
}

**Comment by wangjiebo** [comment]
`直接把manager暴露（readonly）出来` 同意+1

**Comment by xilin** [comment]
请求暴露 +1
