### ISSUE TITLE
post 请求 raw

### ISSUE THREAD

**Issue by NXZXing** [yuantiku/YTKNetwork#301]
你好，在发送post请求的时候，一般的格式是form-data,如果请求格式是raw，该如何设置呢？

**Comment by FelixMLians** [comment]
你怎么解决的？
`- (YTKRequestSerializerType)requestSerializerType {
    return YTKRequestSerializerTypeJSON;
}`

我加了这个还是不行啊

**Comment by NXZXing** [comment]
重写里面  buildCustomUrlRequest 这个方法，具体代码如下：
- (NSURLRequest *)buildCustomUrlRequest {
    
    //请求参数
    NSDictionary *parma = @{@"key1" : @"value1",
                            @"key2" : @"value1"
                            };
    
    NSMutableURLRequest *requst = [[AFJSONRequestSerializer serializer]
                                   requestWithMethod:@"POST"
                                   URLString:@"请求链接"
                                   parameters:nil
                                   error:nil];
    
    NSError *error;
    NSData *dataFromDict = [NSJSONSerialization dataWithJSONObject:parma
                                                           options:NSJSONWritingPrettyPrinted
                                                             error:&error];
    
    requst.timeoutInterval = 30;
    
    //设置请求头，根据自己后台情况而定
    [requst setValue:@"application/json; encoding=utf-8" forHTTPHeaderField:@"Content-Type"];
    [requst setValue:@"application/json" forHTTPHeaderField:@"Accept"];
    
    
    [requst setHTTPBody:dataFromDict];
    
    return requst;
    
}

**Comment by JiaLiangoooo** [comment]
`- (NSURLRequest *)buildCustomUrlRequest {
    
    NSDictionary *params = @{
                             @"user_id": @"1234",
                             @"user_name": @"111"
                             };

    NSMutableURLRequest *request = [[AFHTTPRequestSerializer serializer] requestWithMethod:@"POST" URLString:[self requestUrl] parameters:params error:nil];

    return request;
}
`

**Comment by shevakuilin** [comment]
- (NSURLRequest *)buildCustomUrlRequest {
    NSMutableURLRequest *request = [[AFJSONRequestSerializer serializer] requestWithMethod:@"POST" URLString:[NSString stringWithFormat:@"%@/%@", self.baseUrl, self.requestUrl] parameters:self.requestArgument error:nil];
    request.allHTTPHeaderFields = self.requestHeaderFieldValueDictionary;
    return request;
}

 最简单的解决方案是这样，其余的按照平常的写法写就可以了
