### ISSUE TITLE
CFNetwork警告

### ISSUE THREAD

**Issue by wendymylove** [yuantiku/YTKNetwork#304]
请问各位会不会遇到这个警告：
24600: CFNetwork internal error (0xc01a:/BuildRoot/Library/Caches/com.apple.xbs/Sources/CFNetwork_Sim/CFNetwork-808.1.4/Loading/URLConnectionLoader.cpp:304)
有遇到的朋友或是老师请告诉我原因和解决方法，please～～～

**Comment by zhou963215** [comment]
同样的问题..楼主解决了么

**Comment by wendymylove** [comment]
没有啊

**Comment by zhou963215** [comment]
我找到问题了.我这边是重写了SDWebImageDownloader的headersFilter的block块.实现了图片网址不变.刷新图片的功能,然后就除权这个304.也不算bug,应该是sd里面的图片轮询.证明是最新的图片.没有什么大的问题. http://blog.csdn.net/lizhilin_vip/article/details/53185423
