### ISSUE TITLE
报Invalid status code的问题

### ISSUE THREAD

**Issue by lhm12520** [yuantiku/YTKNetwork#305]
使用AFNetworking发送请求时，可以通过，但使用YTKNetwork时，却报如下的错误 Error Domain=com.yuantiku.request.validation Code=-8 "Invalid status code" UserInfo={NSLocalizedDescription=Invalid status code}

**Comment by skyline75489** [comment]
https://github.com/yuantiku/YTKNetwork/blob/master/YTKNetwork/YTKNetworkAgent.m#L74

**Comment by TuWei1992** [comment]
我后台如果返回数据的就是500错误怎么办?

**Comment by skyline75489** [comment]
重载 statusCodeValidator];

**Comment by shaozhe-chen** [comment]
我也会发生这个问题啊，但是你给的链接，我没看懂怎么处理，求解释。

**Comment by chuckern** [comment]
我也没有看懂啊....
别这么处理啊, 解释一下是什么意思啊

**Comment by edward19931023** [comment]
人家不是说了么，在YTKBaseRequest中有个方法- (BOOL)statusCodeValidator;。
自己实现的时候重载一下，因为父类的方法中有默认实现。自己在子类重载一下

**Comment by orangeren** [comment]
error - Error Domain=com.yuantiku.request.validation Code=-8 "Invalid status code" UserInfo={NSLocalizedDescription=Invalid status code}


天啦噜，我没有看懂，有看懂的吗，解释一下。
