### ISSUE TITLE
请求头"text/html"

### ISSUE THREAD

**Issue by lhm12520** [yuantiku/YTKNetwork#306]
使用AFNetwork请求正常，而在使用YTKNetwork请求时报如下错误：
NSLocalizedDescription = "Request failed: unacceptable content-type: text/html";
最后是修改了AFHTTPResponseSerializer.m，在该类的acceptableContentTypes中添加了text/html才通过，但是通过抓包分析，使用AFNetwork请求时，请求头的Content-type是application/json，而使用YTKNetwork时却是text/html，不知道是什么原因导致这个问题，该如何统一？

**Comment by skyline75489** [comment]
YTKNetwork 并没有设置特殊的请求头，请确认问题来自 YTKNetwork 本身

**Comment by yiwei19850813** [comment]
有同样的问题 @lhm12520 ，请问解决了吗

**Comment by yangcaimu** [comment]
@lhm12520 @yiwei19850813 是不是在继承 `YTKRequest` 的子类中把 `responseSerializerType` 改成了 `YTKResponseSerializerTypeXMLParser` 导致的。

**Comment by yiwei19850813** [comment]
@yangcaimu 不是的。我是通过这样修改的
 case YTKResponseSerializerTypeJSON:
                request.responseObject = [self.jsonResponseSerializer responseObjectForResponse:task.response data:request.responseData error:&serializationError];
                request.responseJSONObject = request.responseObject;
                // 修改，正常情况下是不会出错的，只是后台返回@"text/html"
                if (request.responseObject == nil) {
                    serializationError = nil;
                }
                break;

这样的话，如果后台返回的是一张image，然后content-type:text/html。就可以通过
 UIImage *image = [UIImage imageWithData:operation.responseData];这种方法来解决，operation就是返回的request

**Comment by skyline75489** [comment]
#288

**Comment by kaicodedocument** [comment]
其实这个因为YTK在封装AFNetworking之后，把请求头内容作了覆盖，你可以看他源代码的父类，导致Text/Json等数据类型丢失了。

所以你在项目中进行自己的抽象的时候，可以重写`jsonResponseSerializer.acceptableContentTypes`就可以了:

先封装一个方法:

`#pragma mark 覆盖内容配置

- (void)converContentTypeConfig{
    YTKNetworkAgent *agent = [YTKNetworkAgent sharedAgent];
    NSSet *acceptableContentTypes = [NSSet setWithObjects:@"application/json", @"text/json", @"text/javascript", @"text/plain", @"text/html", @"text/css", nil];
    NSString *keypath = @"jsonResponseSerializer.acceptableContentTypes";
    [agent setValue:acceptableContentTypes forKeyPath:keypath];
}
`

然后在抽象类Engine或者YTKRequest中Init方法掉用即可. 
至于数据类型添加你想要即可，上面基本是接口通信中常用的
