### ISSUE TITLE
ios9系统下Domain=NSURLErrorDomain Code=-1004 "未能连接到服务器。"

### ISSUE THREAD

**Issue by Gaoronghua** [yuantiku/YTKNetwork#308]
之前用AFN也是有这样的问题，不知道是不是应该配置什么，但是这个在iOS8和iOS10上都没有问题，不知道为什么这个会有问题。请帮忙解答一下。

**Comment by techistoner** [comment]
我也碰到了类似的 报错是Error Domain=kCFErrorDomainCFNetwork Code=-1005  url中含有冒号 不知道有没有关系。
