### ISSUE TITLE
加密结果解析问题

### ISSUE THREAD

**Issue by geng199200** [yuantiku/YTKNetwork#310]
请教一下猿题库的大大们，我司接口返回数据都有加密，请求成功，在 handleRequestResult 方法里数据解析的时候，因为有加密，解析不出来json数据，就给我抛出来一个失败，走了failure方法，请问该怎么解决。 @tangqiaoboy @medopaw

**Comment by skyline75489** [comment]
有这种加密的响应的，建议还是内部维护一个 fork 比较稳

**Comment by lancy** [comment]
继承一个业务基类，把`responseSerializerType`设为`HTTP`，在`requestCompletePreprocessor`中把`responseData`解密为`decodedResponseData`，在手动 parse 成 `decodedResponseJSONObject`.

**Comment by liuzhaoyong** [comment]
if (error) {
        succeed = NO;
        requestError = error;
    } else if (serializationError) {
        succeed = NO;
        requestError = serializationError;
    } else {
        succeed = [self validateResult:request error:&validationError];
        requestError = validationError;
    }

这里还会对返回码进行校验，加解密还没有进行解密就已经进行返回码判断了
