### ISSUE TITLE
-viewWillAppear 和 -viewDidLoad 中调用相同的网络请求，errCode=200并请求失败。

### ISSUE THREAD

**Issue by zhangqifan** [yuantiku/YTKNetwork#315]
### 提出问题前请先确认完成了下列几项步骤 New Issue Checklist

* [x] 我已经阅读过 [贡献指南](CONTRIBUTING.md) I have read and understood the [CONTRIBUTING guide](CONTRIBUTING.md)
* [x] 我已经阅读过 [程序文档]((http://cocoadocs.org/docsets/YTKNetwork)) I have read the [Documentation](http://cocoadocs.org/docsets/YTKNetwork)
* [x] 我已经证实这个问题来源于 YTKNetwork 本身，而不是其所依赖的 [AFNetworking](https://github.com/AFNetworking/AFNetworking) I have confirmed that this issue is caused by YTKNetwork, not [AFNetworking](https://github.com/AFNetworking/AFNetworking)
* [x] 我已经在项目的 [问题列表](https://github.com/yuantiku/YTKNetwork/issues) 中搜索过并且没有找到类似问题 I have searched for a similar issue in the [project](https://github.com/yuantiku/YTKNetwork/issues) and found none

### 问题描述 Issue Description

请给出所提出问题的详尽描述，包括具体的错误信息，打印的堆栈等等，以及重现此问题的具体步骤。

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

在 -viewWillAppear 和 -viewDidLoad 中调用了同样的网络请求（完全相同的参数、路径、请求方式等），其中，在前者中调用的直接走 failure block ，截获 errorCode == 200 。
后取消了 -viewDidLoad 中的请求，只走 - viewWillAppear 中的请求，问题同上。

**Comment by y1024** [comment]
请问解决了吗？

**Comment by y1024** [comment]
分析了下原因，我这边的情况是 同一个model，连续发2个请求，当第一个请求回调后，
[_requestsRecord removeObjectForKey:@(request.requestTask.taskIdentifier)];
taskIdentifier虽然是不唯一的，但是value指向同一个value。所以导致第二个请求回来的时候，导致request = null。所以会出现这样的情况。

**Comment by skyline75489** [comment]
YTKRequest 在设计上是只能使用一次的
