### ISSUE TITLE
并发线程数大于 1 的情况下，频繁请求和终止网络请求时会报 double free 错误

### ISSUE THREAD

**Issue by icyleaf** [yuantiku/YTKNetwork#32]
目前场景是在搜索情况下，再不同类型进行快速网络请求搜索，切换的时候我们会把当前的请求终止并启动新线程，如果非常快速点击的情况下，可能会因为 stop 请求报 double free 的崩溃错误。

如果把并发线程数改为 1 就没有这个问题。

**Comment by tangqiaoboy** [comment]
你在stop后，应该将stop的网络请求实例设置成nil。不应该在多线程下多次调用一个网络请求的stop方法。

**Comment by BaiCanLin** [comment]
我并没有设置缓存时间 或者 我设置缓存过期时间为 3秒  为什么一定要退出App后数据才会重新刷新，下拉刷新数据不会更新的

**Comment by tangqiaoboy** [comment]
@BaiCanLin 和我的库没有关系吧？感觉是你自己下拉刷新相关逻辑没写好。
