### ISSUE TITLE
我要批量上传5张图片,要取消其中的一条,但其他的还是需要继续上传,这样使用YTKBatchRequest就会让其他的图片都取消掉

### ISSUE THREAD

**Issue by SurpassRabbit** [yuantiku/YTKNetwork#325]
如题,评价功能,要批量上传5张图片,要取消其中一张,使用YTKBatchRequest的stop功能,会让整个其他4张图片也都失败,但可能已经上传成功了.这样会导致用户流量的浪费,  @tangqiaoboy  @maojj  我翻看了之前issues,但最后也没有提出解决的方式. 

还有图片上传的进度应该是刚需的属性吧. 为什么没有添加呢?

**Comment by tangqiaoboy** [comment]
YTKBatchRequest 设计的方式和你的需求不一致，你可以自己定制实现一个你这种需求的 BatchRequest，代码量应该很小的。

**Comment by RabbitDream** [comment]
取消一个请求的功能,我马上就去试试. 但现在上传进度的问题,不知道具体怎么处理了. 

我查看了YTK的源码,发现在`YTKNetworkAgent`的446行调用的是

```
dataTask = [_manager dataTaskWithRequest:request
                           completionHandler:^(NSURLResponse * __unused response, id responseObject, NSError *_error) {
                               [self handleRequestResult:dataTask responseObject:responseObject error:_error];
                           }];
```

但如果需要调用到进度条方法需要使用下面这个方法, 如果我要实现上传进度的功能,是不是需要改底层的源码呢?

```
[_manager dataTaskWithRequest:request uploadProgress:^(NSProgress * _Nonnull uploadProgress) {
     
    } downloadProgress:^(NSProgress * _Nonnull downloadProgress) {
        
    } completionHandler:^(NSURLResponse * _Nonnull response, id  _Nullable responseObject, NSError * _Nullable error) {
       
    }];
```

**Comment by RabbitDream** [comment]
取消一个请求的功能.修改`YTKBatchRequest`之后还是没有成功,  不知道原因所在. @tangqiaoboy  翻看了Issues, 发现很多人都在求我说的两个功能, 取消单个请求和进度.   这两个功能YTK内部就真的不能提供一下吗?

**Comment by skyline75489** [comment]
@RabbitDream 代码本身是开源的，如果有需求可以 fork
