### ISSUE TITLE
求助：关于networkActivityIndicatorVisible的支持，怎么完美嵌入

### ISSUE THREAD

**Issue by chinesemanbobo** [yuantiku/YTKNetwork#326]
能否支持下`networkActivityIndicatorVisible`的使用，利用`AFNetworkActivityIndicatorManager`的`enabled`属性，或者利用系统的都可以！！！

把这个属性添加到对应的`XX Request`类中，方便调用！！！

谢！

**Comment by skyline75489** [comment]
Github 不是技术支持论坛，issue 仅用于解决 YTKNetwork 本身存在的问题。
