### ISSUE TITLE
说好的 cacheTimeInSeconds 大于等于0就能开启缓存的呢

### ISSUE THREAD

**Issue by shaozhe-chen** [yuantiku/YTKNetwork#337]
- (void)saveResponseDataToCacheFile:(NSData *)data {
    if ([self cacheTimeInSeconds] > 0 && ![self isDataFromCache]) {
        if (data != nil) {
            @try {
                // New data will always overwrite old data.
                [data writeToFile:[self cacheFilePath] atomically:YES];

                YTKCacheMetadata *metadata = [[YTKCacheMetadata alloc] init];
                metadata.version = [self cacheVersion];
                metadata.sensitiveDataString = ((NSObject *)[self cacheSensitiveData]).description;
                metadata.stringEncoding = [YTKNetworkUtils stringEncodingWithRequest:self];
                metadata.creationDate = [NSDate date];
                metadata.appVersionString = [YTKNetworkUtils appVersionString];
                [NSKeyedArchiver archiveRootObject:metadata toFile:[self cacheMetadataFilePath]];
            } @catch (NSException *exception) {
                YTKLog(@"Save cache failed, reason = %@", exception.reason);
            }
        }
    }
}

([self cacheTimeInSeconds] > 0 条件判断，没有等于0哇

**Comment by ios9developer** [comment]
默认是-1，一般设置大于0s开启缓存。如果等于0s开启缓存，缓存0s,这个需求貌似不合理吧，一点浅见。
- (NSInteger)cacheTimeInSeconds {
    return -1;
}
