### ISSUE TITLE
您好，如何获取断点续传文件下载进度呢，没有找到进度回调入口。

### ISSUE THREAD

**Issue by JackyMaus** [yuantiku/YTKNetwork#340]
您好，最近项目要做个多个文件断点续传功能，网络模块用的你们的这个，看了下支持断点续传，但是没有找到进度回调的入口，没有办法显示进度，这个怎么处理呢。

**Comment by xiaohuapunk** [comment]
`/* 下载最新版本 */
    BMUpdateBundlejsRequest *updateJSApi = [[BMUpdateBundlejsRequest alloc] initWithDownloadJSUrl:urlString];
    
    /* 统计接口时间 */
    [BMAppMonitor monitorApiRequestStartWithRequest:updateJSApi];
    
    updateJSApi.resumableDownloadProgressBlock = ^(NSProgress *progress) {
        
        WXLogInfo(@"\n 下载进度>>>> 文件总大小：%lld 已下载：%lld",progress.totalUnitCount,progress.completedUnitCount);
        
#if DebugVersion == 1
        [SVProgressHUD showProgress:((float)progress.completedUnitCount / (float)progress.totalUnitCount) status:@"js资源文件更新中..."];
#endif
        
    };
`

**Comment by skyline75489** [comment]
@xiaohuapunk Thanks.

**Comment by StonesMaa** [comment]
谢谢啦，我自己写了一个，不过感觉没必要，之前没仔细看，没找到，马上改回来。
