### ISSUE TITLE
设置HTTPS以后，在下面这里这里崩溃

### ISSUE THREAD

**Issue by aimm** [yuantiku/YTKNetwork#341]
for (NSData *certificateData in self.pinnedCertificates) {
                [pinnedCertificates addObject:(__bridge_transfer id)SecCertificateCreateWithData(NULL, (__bridge CFDataRef)certificateData)];
            }
![251400cf-98ef-44ee-aad0-5abc97a9d452](https://cloud.githubusercontent.com/assets/18607226/26290293/0bbe1584-3ed9-11e7-9187-bc2e53524a31.png)

**Comment by skyline75489** [comment]
Not our problem. Closed
