### ISSUE TITLE
【断点续传】改进的建议

### ISSUE THREAD

**Issue by xiaohuapunk** [yuantiku/YTKNetwork#347]
使用断点续传的功能时，发现当双击home键退出app，然后在打开app，断点续传是不起作用的（依然从0开始下载），然后看了一下源码发现只有在 `requestDidFailWithRequest` 时才会将之前已经缓存的数据配置信息 `resumeData` 保存到 `../tmp/Incomplete`目录下，每次下载任务开启时都会去这个目录下找对应的 `resumeData`然后判断数据是否存在，存在就继续下载，不存在就重新下载。

改进1：当 `UIApplicationWillResignActiveNotification` （双击 home 键会调用的通知）时，也做一下保存当前下载数据 `resumeData`的操作，下次app重启就可以继续使用之前缓存的数据继续下载了。

改进2：保存 `resumeData`时最后路径拼接的是 `resumableDownloadPath`的md5值，这里设计的有点不合理，如果我同一时间有多个下载任务，并且文件都放在同一个目录下，那么就无法区分各种对应的 `resumeData`了，所以建议 使用 url的md5值作为文件的标示位置信息；

以上是我的一点想法，不知道这样是否合理，还请各位指正 谢谢！

**Comment by skyline75489** [comment]
1. 为了保持框架的轻量特性，以及和 1.0 版本的行为保持一致，没有加过多复杂的断点续传逻辑，这里的坑本身就比较多，想要实现的很完美需要引入很多逻辑。
2. 这个确实是设计上的一个问题，有改善空间
