### ISSUE TITLE
设置缓存请求超时时间后，当请求成功的时候，缓存是如何生存的？

### ISSUE THREAD

**Issue by liangang** [yuantiku/YTKNetwork#35]
我设置了缓存时间，当我再次发送同样地请求的时候，判断缓存不存在，代码又发送了一次请求，不知道为什么....

**Comment by tangqiaoboy** [comment]
show me the code.

**Comment by liangang** [comment]
-----------------------------调用-------------------
#import "ViewController.h"
#import "YTKBatchRequest.h"
#import "YTKChainRequest.h"
#import "GetImageApi.h"
#import "GetUserInfoApi.h"
#import "RegisterApi.h"

@interface ViewController ()<YTKChainRequestDelegate>

@end

@implementation ViewController
- (void )test
{
    GetUserInfoApi *api = [[GetUserInfoApi alloc]initWithUserId:@"1"];
    [api startWithCompletionBlockWithSuccess:^(YTKBaseRequest *request) {
        NSLog(@"%@",request.requestOperation.responseString);
    } failure:^(YTKBaseRequest *request) {
        NSLog(@"11111");
    }];
}

- (void)loadCacheData {
    
       GetUserInfoApi *api = [[GetUserInfoApi alloc] initWithUserId:@"1"];
    //    [api start];
    if ([api cacheJson]) {
        NSDictionary *json = [api cacheJson];
        NSLog(@"json = %@", json);
        // show cached data
    }
    [api startWithCompletionBlockWithSuccess:^(YTKBaseRequest *request) {
        NSLog(@"update ui");
        NSLog(@"%@",request.requestOperation.responseString);
    } failure:^(YTKBaseRequest *request) {
        NSLog(@"failed");
    }];
}

- (void)viewDidLoad {
    [self test];
    [self loadCacheData];
    [super viewDidLoad];
}
@end
-----------------------------------------缓存超时设置-------------------------------
#import "GetUserInfoApi.h"
@implementation GetUserInfoApi
..................
- (NSInteger)cacheTimeInSeconds {
    return 60 * 3*3;
}
@end

第一次运行  [self test];请求成功，第二次 [self loadCacheData];请求相同，但是判断缓存不存在

**Comment by tangqiaoboy** [comment]
你的服务器返回数据不是json吗？现在缓存只能针对json数据。
可以用 request.responseJson 来取得数据。

**Comment by tangqiaoboy** [comment]
你把 NSLog(@"%@",request.requestOperation.responseString); 改成 NSLog(@"%@",request.responseJSONObject); 试试

**Comment by tangqiaoboy** [comment]
另外你不用手工判断 `cacheJson` 数据，正常调 `startWithCompletionBlockWithSuccess` 即可。它会在有缓存的时候，自动将数据放到 responseJSONObject 返回，而不再发送网络请求。
这样Controller就不用关心网络请求到底有没有发送了，只管显示数据就行。

**Comment by liangang** [comment]
问题找到了....YTKNetwork的缓存只支持content type 为application/json 而我请求的content type 是text/html 所以失败....

**Comment by liangang** [comment]
![11](https://cloud.githubusercontent.com/assets/4946579/5641115/b88dc358-966c-11e4-8fd1-1de61ec78729.png)
加入这一句 缓存成功.  不知道会不会有什么影响..

**Comment by tangqiaoboy** [comment]
嗯，我们现在只支持 application/json 的格式。之前也没想到很多朋友 Restful api返回的居然不是json格式。

**Comment by liangang** [comment]
我们的返回是json格式的....但是content type 是text/HTML.....

**Comment by BaiCanLin** [comment]
好像没有发现有开启状态栏菊花的～ [[AFNetworkActivityIndicatorManager sharedManager]setEnabled:YES]; 这句话应该在哪里写呢

**Comment by tangqiaoboy** [comment]
直接在appDelegate里面的启动成功的回调`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions`中写即可。
