### ISSUE TITLE
不支持HTTPMethodsEncodingParametersInURI

### ISSUE THREAD

**Issue by glary** [yuantiku/YTKNetwork#350]
### 提出问题前请先确认完成了下列几项步骤 New Issue Checklist

* [x] 我已经阅读过 [贡献指南](CONTRIBUTING.md) I have read and understood the [CONTRIBUTING guide](CONTRIBUTING.md)
* [x] 我已经阅读过 [程序文档]((http://cocoadocs.org/docsets/YTKNetwork)) I have read the [Documentation](http://cocoadocs.org/docsets/YTKNetwork)
* [x] 我已经证实这个问题来源于 YTKNetwork 本身，而不是其所依赖的 [AFNetworking](https://github.com/AFNetworking/AFNetworking) I have confirmed that this issue is caused by YTKNetwork, not [AFNetworking](https://github.com/AFNetworking/AFNetworking)
* [x] 我已经在项目的 [问题列表](https://github.com/yuantiku/YTKNetwork/issues) 中搜索过并且没有找到类似问题 I have searched for a similar issue in the [project](https://github.com/yuantiku/YTKNetwork/issues) and found none

### 问题描述 Issue Description

此框架不支持设置HTTPMethodsEncodingParametersInURI吗

**Comment by yuyangdexue** [comment]
HTTPMethodsEncodingParametersInURI 默认不支持post 请求，服务器拿不到参数，请问你是怎么解决的
