### ISSUE TITLE
为什么更新ytk以后上传的代码报错

### ISSUE THREAD

**Issue by wz1383691** [yuantiku/YTKNetwork#353]
更新了ytk 2.0.3以后，
- (AFConstructingBlock)constructingBodyBlock {
    return ^(id<AFMultipartFormData>formData) {
        if(_files){
            print(@"我有图片");
            NSData *data = UIImageJPEGRepresentation(_files, 0.8);
            NSString *name = @"image_ios_01.png";
            NSString *formKey = @"bankCard";
            NSString *type = @"image/jpeg";
            [formData appendPartWithFileData:data name:formKey fileName:name mimeType:type];
        }
    };
}

formData显示找不到方法，我单独引用AFMultipartFormData之后才可以使用，这是什么原因呢，之前的ytk版本我也没有单独引用这个就可以使用。

**Comment by skyline75489** [comment]
#243
