### ISSUE TITLE
token 被转义

### ISSUE THREAD

**Issue by duckls** [yuantiku/YTKNetwork#355]
token =  mm@WjwqJjs9J 
放在 
`  YTKUrlArgumentsFilter *versionFilter = [YTKUrlArgumentsFilter filterWithArguments:@{@"token":token}];
    [config addUrlFilter:versionFilter];`

被转义成 token= mm%40WjwqJjs9J
断天调试 AFQueryStringPair  URLEncodedStringValue 这函数
afn 3.1版本

**Comment by skyline75489** [comment]
只要放在 URL 当中的内容就一定会被 urlencode，与框架无关。
