### ISSUE TITLE
cacheTimeInSeconds>0时可以缓存，此处有Bug

### ISSUE THREAD

**Issue by hupfei** [yuantiku/YTKNetwork#356]
cacheFileName是以URL加请求参数md5后获取的，但是同一个URL请求，参数可能不一样，比如参数为当前时间，此时的md5值显然是不一样的，这样就找不到缓存内容。希望能完善一下

**Comment by zymxxx** [comment]
CMCacheDirectoryPathFilterProtocol

**Comment by hupfei** [comment]
@zymxxx 什么意思？

**Comment by zymxxx** [comment]
CMCacheDirectoryPathFilterProtocol用这个协议可以过滤一些参数去存储缓存的。

**Comment by hupfei** [comment]
@zymxxx 搞清楚了  重载- (id)cacheFileNameFilterForRequestArgument:(id)argument这个方法就行了，YTKCacheDirPathFilterProtocol并不是处理这个的

**Comment by zymxxx** [comment]
@hupfei 嗯，给错方法了，尴尬。
