### ISSUE TITLE
调用YTKNetworkAgent中的-cancelRequest方法无法获取断点下载的描述数据

### ISSUE THREAD

**Issue by arKenLee** [yuantiku/YTKNetwork#357]
在 `YTKNetworkAgent` 类中的 `-cancelRequest` 方法中，`[request.requestTask cancel]` 并没有判断 task 是否是 `NSURLSessionDownloadTask`类。导致取消下载时 `-requestDidFailWithRequest:error:` 获取不到断点描述数据 `NSURLSessionDownloadTaskResumeData`。

希望在取消请求时加上判断，如果是 `NSURLSessionDownloadTask` 调用`-cancelByProducingResumeData:` ，其他情况才调用 `-cancel`。

**Comment by skyline75489** [comment]
See #292

**Comment by skyline75489** [comment]
Closed by #292
