### ISSUE TITLE
你好，我想问下并发请求数比较大情况下的问题？

### ISSUE THREAD

**Issue by Xq-MyGithub** [yuantiku/YTKNetwork#359]
你好，在使用YTKNetwork的时候，通过formdata上传数据时，如果并发数超过四个  第五个就处于等待状态，但是仍旧会走超时时间，如果在超时时间内 前面四个都没有完成，那么第五个和第六个就会超时，我想问下YTKNetwork在并发请求的时候有做类似队列处理么？

**Comment by skyline75489** [comment]
AFNetworking problem. Closing.
