### ISSUE TITLE
请求重试建议

### ISSUE THREAD

**Issue by Baichenghui** [yuantiku/YTKNetwork#360]
### 提出问题前请先确认完成了下列几项步骤 New Issue Checklist

* [ ] 我已经阅读过 [贡献指南](CONTRIBUTING.md) I have read and understood the [CONTRIBUTING guide](CONTRIBUTING.md)
* [ ] 我已经阅读过 [程序文档]((http://cocoadocs.org/docsets/YTKNetwork)) I have read the [Documentation](http://cocoadocs.org/docsets/YTKNetwork)
* [ ] 我已经证实这个问题来源于 YTKNetwork 本身，而不是其所依赖的 [AFNetworking](https://github.com/AFNetworking/AFNetworking) I have confirmed that this issue is caused by YTKNetwork, not [AFNetworking](https://github.com/AFNetworking/AFNetworking)
* [ ] 我已经在项目的 [问题列表](https://github.com/yuantiku/YTKNetwork/issues) 中搜索过并且没有找到类似问题 I have searched for a similar issue in the [project](https://github.com/yuantiku/YTKNetwork/issues) and found none

### 问题描述 Issue Description

当一个请求失败时，是否能做一次重试请求？

**Comment by zhang28602** [comment]
你自己不会写个定时器重新跑一下嘛？

**Comment by Baichenghui** [comment]
我还真不会通过写一个定时器，然后重跑一下来解决这个问题，请指教？大神

**Comment by skyline75489** [comment]
Won't fix.

**Comment by qxc122** [comment]
我也不会写，坐等
