### ISSUE TITLE
-999 已取消 一个没有参数的get请求，超时没改过，默认的是60s

### ISSUE THREAD

**Issue by gank0326** [yuantiku/YTKNetwork#361]
Error Domain=NSURLErrorDomain Code=-999 "已取消" UserInfo={NSErrorFailingURLKey=https://apitest.homeba.com.cn/api/banners, NSLocalizedDescription=已取消, NSErrorFailingURLStringKey=https://apitest.homeba.com.cn/api/banners}

**Comment by skyline75489** [comment]
Not our problem. Closing.
