### ISSUE TITLE
为什么我批量下载视屏的时候返回的是成功我却找不到我下载的文件夹

### ISSUE THREAD

**Issue by 17671621757** [yuantiku/YTKNetwork#364]
YTKBatchRequest *batchRequest = [[YTKBatchRequest alloc] initWithRequestArray:requestArray];
        [batchRequest startWithCompletionBlockWithSuccess:^(YTKBatchRequest * _Nonnull batchRequest) {
            NSArray *requests = batchRequest.requestArray;
            HomeAdsVideoRequest *request = (HomeAdsVideoRequest *) requests[0];
            NSLog(@"%@",request);
        } failure:^(YTKBatchRequest * _Nonnull batchRequest) {
        }];
成功后的打印
-[CycleScrollViewModel lc_initialize]_block_invoke [第33行] 💕 <HomeAdsVideoRequest: 0x1701648c0>{ URL: http://renren2.maoyun.tv/ads/jike15s.mp4 } { method: GET } { arguments: (null) }

这是请求类
@interface HomeAdsVideoRequest : YTKRequest
- (instancetype)initWinthUrl:(NSString *)url;
@end

@implementation HomeAdsVideoRequest
{
    NSString *_url ;
}
- (instancetype)initWinthUrl:(NSString *)url {
    if (self = [super init]) {
        _url = url;
    }
    return self;
}
- (NSString *)requestUrl {
    return _url;
}

- (NSString *)resumableDownloadPath {
    NSString *libPath = [NSSearchPathForDirectoriesInDomains(NSLibraryDirectory, NSUserDomainMask, YES) objectAtIndex:0];
    NSString *cachePath = [libPath stringByAppendingPathComponent:@"AdsVideoCache"];
//    NSString *filePath = [cachePath stringByAppendingPathComponent:_url];
    return cachePath;
}

**Comment by github641** [comment]
-resumableDownloadPath方法中返回的路径，需要你自己先创建文件夹。
AFURLSessionManager类中，下载完毕，将缓存写入指定文件夹的方法是-moveItemAtURL：toURL：error：
- (void)URLSession:(NSURLSession *)session
      downloadTask:(NSURLSessionDownloadTask *)downloadTask
didFinishDownloadingToURL:(NSURL *)location
{
    NSError *fileManagerError = nil;
    self.downloadFileURL = nil;

    if(self.downloadTaskDidFinishDownloading) {
        self.downloadFileURL = self.downloadTaskDidFinishDownloading(session, downloadTask, location);
        if (self.downloadFileURL) {
//           BOOL suc =
            [[NSFileManager defaultManager] moveItemAtURL:location toURL:self.downloadFileURL error:&fileManagerError];
            
//            NSLog(@"写入指定的地址:%@成功了吗：%@ error:%@", self.downloadFileURL, @(suc), fileManagerError);

            if (fileManagerError) {
                [[NSNotificationCenter defaultCenter] postNotificationName:AFURLSessionDownloadTaskDidFailToMoveFileNotification object:downloadTask userInfo:fileManagerError.userInfo];
            }
        }
    }
}

可以参考demo：
 https://github.com/github641/YTKDownloadAd.git

**Comment by skyline75489** [comment]
Usage. Closing.
