### ISSUE TITLE
遇到多服务器的情况要怎么处理 ？就是有多个baseUrl 的情况？

### ISSUE THREAD

**Issue by iCoobin** [yuantiku/YTKNetwork#368]
如果是大项目，后台服务化部署，不同的业务归属不同的服务器，app端组件化开发，不同的业务组件使用的baseUrl不同，但业务组件都用YTKNetwork来做依赖开发，这要怎么弄呢？

**Comment by Sunnyyoung** [comment]
@iCoobin 继承`BaseRequest`，重写`baseUrl`方法。

**Comment by iCoobin** [comment]
哦，谢谢




发自网易邮箱大师
在2017年08月09日 12:15，Sunnyyoung 写道：

@iCoobin 继承BaseRequest，重写baseUrl方法。
