### ISSUE TITLE
接口签名校验怎么弄？

### ISSUE THREAD

**Issue by iCoobin** [yuantiku/YTKNetwork#369]
例如，一般接口都会防止他人调用，增加了一些验证规则来确定接口是自己的app调用的并且验证请求的参数在传输过程中没有被修改，会将所有的请求参数加上一个key和时间戳进行md5，然后将md5添加到请求头中，服务器端根据参数与md5值进行校验。同一个服务器的所有接口的检验规则一样。iOS端使用YTKRequest的时候要怎么弄呢？

**Comment by MQL9011** [comment]
我也有这个问题,  除了重写整个请求头, 有单独增加请求头中字段的方法吗?
