### ISSUE TITLE
有针对发送请求被拦截做特殊处理吗？

### ISSUE THREAD

**Issue by lilongcnc** [yuantiku/YTKNetwork#377]
您好。
我使用框架的时候， 用charles进行请求拦截，打算模拟后台数据，拦截返回给客户端。 但是猿题库这边是失败的。不能正常收到我自定义的后台数据。 同样的所有条件，我直接使用AFN就可以收到我模拟的数据。请问， YTK有特殊处理吗？

**Comment by lancy** [comment]
没有对这方面有处理，是可以正常使用 charles 拦截的；
