### ISSUE TITLE
多个文件下载, 下载列表怎么实现暂停下载, 继续下载呢.  

### ISSUE THREAD

**Issue by huicuihui** [yuantiku/YTKNetwork#378]
没有暂停的方法,  只有在断网下载失败的情况下, 已下载的内容才会写入文件. 
    // Save incomplete download data.
    NSData *incompleteDownloadData = error.userInfo[NSURLSessionDownloadTaskResumeData];
    if (incompleteDownloadData) {
        [incompleteDownloadData writeToURL:[self incompleteDownloadTempPathForDownloadPath:request.resumableDownloadPath] atomically:YES];
    }
如果是stop的话  再次下载不会续传  因为没有文件存在.  只有afn下载的临时文件.tmp

**Comment by skyline75489** [comment]
如果有需要可以自行实现，YTKNetwork 目前不提供这个功能
