### ISSUE TITLE
使用版本2.0.3 发现responseString是空的，不知道问题出在哪里？

### ISSUE THREAD

**Issue by LiuDao27** [yuantiku/YTKNetwork#379]
使用2.0.3 代码如下 
ShiGuangWuNetHandle *laughHandle = [[ShiGuangWuNetHandle alloc] initWithUrl:@"/Auth/loadingImg.html" RegisterApiMethod:RequestMethodGet];
    [laughHandle startWithCompletionBlockWithSuccess:^(YTKBaseRequest *request) {
      
    } failure:^(YTKBaseRequest *request) {
        
    }]; 
发现 request.responseString和 request.responseJSONObject 都没有返回数据。然后我试了下1.3.0的有数据 不知道这是什么问题导致的？

**Comment by skyline75489** [comment]
#250 #288
