### ISSUE TITLE
YTKNetwork 如何在一个统一的地方输出request构造之后的url

### ISSUE THREAD

**Issue by thuai** [yuantiku/YTKNetwork#38]
因为使用requestUrl和requestArgument构造url所以，不知道到底请求的url是什么？想统一log出来看下

```
- (NSString *)requestUrl
{
    return @"/auth/login";
}
- (id)requestArgument
{
    return @{
             @"Account": _account,
             @"Password": _passwd
             };
}
```

目前我的做法是在YTKNetworkAgent的addRequest：方法中打印出来

```
YTKRequestMethod method = [request requestMethod];
NSString *url = [self buildRequestUrl:request];
NSLog(@"url => %@", url);
```

**Comment by tangqiaoboy** [comment]
感觉你现在的做法应该可以～

**Comment by thuai** [comment]
这个做法是可行的。但是不知道你们在实践过程中是否有更好的做法么？

**Comment by tangqiaoboy** [comment]
我一般是打开charles，所有目标网址的网络请求都截获并且json都格式化好了。

**Comment by tangqiaoboy** [comment]
关于charles，我的新书有完整的介绍，博客上也有部分介绍：http://blog.devtang.com/blog/2013/12/11/network-tool-charles-intr/

**Comment by thuai** [comment]
你的书已经在路上。。不日将到手。

**Comment by wtuyp** [comment]
哈哈，我是这样，差不多，把参数也打印出来。
YTKRequestMethod method = [request requestMethod];
    NSString *url = [self buildRequestUrl:request];
    id param = request.requestArgument;
    DELogShort(@"网络请求地址 = %@ \n 参数 = %@", url, param);

**Comment by huangbaoyu** [comment]
# ifdef DEBUG_MODE
    DDLogInfo(@"URL = %@ \n Result = %@", [self  curlCommandLine] , self.responseString);
# endif

- (NSString *)curlCommandLine {
    NSMutableString *curl = [[NSMutableString alloc] init];
    if ([self requestMethod] == YTKRequestMethodPost) {
        [curl appendString:@"curl -X POST -H 'Content-Type: application/json; charset=utf-8'"];
        [curl appendString:@" "];
        [curl appendString:[NSString stringWithFormat:@"'%@'", [self buildRequestUrl]]];
        [curl appendString:@" "];
        [curl appendString:@"-d"];
        NSDictionary *dict = [self requestArgument];
        [curl appendString:[NSString stringWithFormat:@"'%@'", [dict jsonString]]];
    } else if ([self requestMethod] == YTKRequestMethodGet){
        NSMutableString *url = [[NSMutableString alloc] init];
        [url appendString:[NSString stringWithFormat:@"%@?", [self buildRequestUrl]]];
        NSDictionary *dict = [self requestArgument];
        for (NSString *key in [dict allKeys]) {
            [url appendString:[NSString stringWithFormat:@"%@=%@&", key, [dict valueForKey:key]]];
        }
        
        [curl appendString:[NSString stringWithFormat:@"curl '%@'", [url substringToIndex:[url length] - 1]]];
        [curl appendString:@"-H 'Content-Type: application/json; charset=utf-8'"];
    }
    return curl;
}
