### ISSUE TITLE
缓存那部分代码貌似有点问题

### ISSUE THREAD

**Issue by ynot16** [yuantiku/YTKNetwork#380]
```
- (void)loadCacheData {
    NSString *userId = @"1";
    GetUserInfoApi *api = [[GetUserInfoApi alloc] initWithUserId:userId];
    if ([api loadCacheWithError:nil]) {
        NSDictionary *json = [api responseJSONObject];
        NSLog(@"json = %@", json);
        // show cached data
    }
    [api startWithCompletionBlockWithSuccess:^(YTKBaseRequest *request) {
        NSLog(@"update ui");
    } failure:^(YTKBaseRequest *request) {
        NSLog(@"failed");
    }];
}
```

在已经设置了`cacheTimeInSeconds `大于0的情况下，无论是`loadCacheWithError `，还是`startWithCompletionBlockWithSuccess `，都会直接读缓存内容，所以是否不会实现到update ui的效果？

**Comment by ynot16** [comment]
是否应该在成功读取缓存后，设置`ingoreCache `为YES，再去发请求？

**Comment by lancy** [comment]
如果要忽略缓存，强制发请求就设置 ignoreCache = YES

**Comment by ynot16** [comment]
我的意思是你们文档的那部分代码是不是表述错误了。[https://github.com/yuantiku/YTKNetwork/blob/master/Docs/ProGuide_cn.md#显示上次缓存的内容](url)

**Comment by Huang-Libo** [comment]
你既然已经设置了 cacheTimeInSeconds 大于 0, startWithCompletionBlockWithSuccess 当然不会真正发送请求了. 只有缓存过期才会真正发送请求. 

而文档中描述的情景是, 在缓存未过期并且网络很慢时, 先显示缓存的内容. 如果你有其他情景需要实现, 可以自己通过设置  ignoreCache 来实现.
