### ISSUE TITLE
上传图片总是报错是为什么啊，按着官方demo来的 

### ISSUE THREAD

**Issue by BIBiBI12** [yuantiku/YTKNetwork#382]
#import "UpHeadImageApi.h"

@implementation UpHeadImageApi{
    UIImage * _image;
}

- (id)initWithImage:(UIImage *)image{
    self = [super init];
    if (self) {
        _image = image;
    }
    return self;
}

- (NSString *)requestUrl {
    return upHeadImageRequest;
}
- (AFConstructingBlock)constructingBodyBlock {
    return ^(id<AFMultipartFormData> formData) {
        NSData *data = UIImageJPEGRepresentation(_image, 0.9);
        NSString *name = @"91zqx";
        NSString *formKey = @"file";
        NSString *type = @"image/jpeg";
        [formData appendPartWithFileData:data name:formKey fileName:name mimeType:type];
    };
}

ps：官方的好像是没有要求传参数，我这多传了一个token，token直接通过正常的传参的方式传的

**Comment by BIBiBI12** [comment]
崩溃了，不想用afnetworking实现，项目里全用的ytknetkworking

**Comment by Huang-Libo** [comment]
代码格式化一下, 看的累

**Comment by BIBiBI12** [comment]
找到原因了，data.name = @"image.png"   之前都是直接写的data.name = @"iamge"

自己的原因，框架很好用,支持
