### ISSUE TITLE
YTKNetWork怎么设置acceptableContentTypes属性为Text/html，没找到的说----手动尴尬

### ISSUE THREAD

**Issue by lk415064460** [yuantiku/YTKNetwork#383]
### 提出问题前请先确认完成了下列几项步骤 New Issue Checklist

* [x] 我已经阅读过 [贡献指南](CONTRIBUTING.md) I have read and understood the [CONTRIBUTING guide](CONTRIBUTING.md)
* [x] 我已经阅读过 [程序文档]((http://cocoadocs.org/docsets/YTKNetwork)) I have read the [Documentation](http://cocoadocs.org/docsets/YTKNetwork)
* [x] 我已经证实这个问题来源于 YTKNetwork 本身，而不是其所依赖的 [AFNetworking](https://github.com/AFNetworking/AFNetworking) I have confirmed that this issue is caused by YTKNetwork, not [AFNetworking](https://github.com/AFNetworking/AFNetworking)
* [ ] 我已经在项目的 [问题列表](https://github.com/yuantiku/YTKNetwork/issues) 中搜索过并且没有找到类似问题 I have searched for a similar issue in the [project](https://github.com/yuantiku/YTKNetwork/issues) and found none

### 问题描述 Issue Description

请给出所提出问题的详尽描述，包括具体的错误信息，打印的堆栈等等，以及重现此问题的具体步骤。

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by Huang-Libo** [comment]
https://github.com/yuantiku/YTKNetwork/issues/250

**Comment by lk415064460** [comment]
OK Ths

**Comment by lk415064460** [comment]
现在请求的话设置了

    NSSet *acceptableContentTypes = [NSSet setWithObjects:@"application/json", @"text/json", @"text/javascript", @"text/plain", @"text/html", @"text/css", nil];
    NSString *keypath = @"jsonResponseSerializer.acceptableContentTypes";
    @try {
        [agent setValue:acceptableContentTypes forKeyPath:keypath];
    } @catch (NSException *exception) {
        NSLog(@"%@", exception);
    } @finally {
        
    }
这个，但是请求出现了
 Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set   
Json数据格式解析不正确

**Comment by skyline75489** [comment]
Not our issue. Closed.

**Comment by UnicomMrLee** [comment]
这个问题你是怎么解决的兄弟
