### ISSUE TITLE
YTKNetwork中如何设置responseSerializer.acceptableContentTypes

### ISSUE THREAD

**Issue by jzy673378715** [yuantiku/YTKNetwork#384]
### 提出问题前请先确认完成了下列几项步骤 New Issue Checklist

* [ ] 我已经阅读过 [贡献指南](CONTRIBUTING.md) I have read and understood the [CONTRIBUTING guide](CONTRIBUTING.md)
* [ ] 我已经阅读过 [程序文档]((http://cocoadocs.org/docsets/YTKNetwork)) I have read the [Documentation](http://cocoadocs.org/docsets/YTKNetwork)
* [ ] 我已经证实这个问题来源于 YTKNetwork 本身，而不是其所依赖的 [AFNetworking](https://github.com/AFNetworking/AFNetworking) I have confirmed that this issue is caused by YTKNetwork, not [AFNetworking](https://github.com/AFNetworking/AFNetworking)
* [ ] 我已经在项目的 [问题列表](https://github.com/yuantiku/YTKNetwork/issues) 中搜索过并且没有找到类似问题 I have searched for a similar issue in the [project](https://github.com/yuantiku/YTKNetwork/issues) and found none

### 问题描述 Issue Description

请给出所提出问题的详尽描述，包括具体的错误信息，打印的堆栈等等，以及重现此问题的具体步骤。

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by guishengx** [comment]
由于YTKNetworkAgent中的responseSerializer为私有属性，没有提供设置方法，所以只能使用AFHTTPResponseSerializer设置的默认acceptableContentTypes。如果服务器不按套路来，就要验证出错。目前看来只能自己改了。

**Comment by Huang-Libo** [comment]
" 我已经在项目的 问题列表 中搜索过并且没有找到类似问题?"

**Comment by jzy673378715** [comment]
看了问题列表中类似的问题，只能暂时性使用一下，对于text/html等类型，还是不支持啊，这个感觉不是很友好，目前算是解决了
