### ISSUE TITLE
希望能够支持request作为成员变量

### ISSUE THREAD

**Issue by bxyfighting** [yuantiku/YTKNetwork#391]
有时候需要在request中管理数据，所以把request作为了成员变量。发现当网络错误时，request.error = error; 但是网络成功后并没有设置回request.error = nil; 导致request请求成功，request.error仍然返回非空值，希望能够提供支持request作为成员变量的情况。

**Comment by skyline75489** [comment]
每个 request 被设计为只能使用一次的

**Comment by bxyfighting** [comment]
我设计分页API的时候，希望API能够管理页数变量并提供loadNextPage和loadPreviousPage方法，在内部调用start方法。把request作为成员变量的过程中并没有发现其它问题，只是这个error置nil问题，在成功回调中简单的加个request.error = nil; 就可以支持多次使用，多好，而且我的这种设计应该也是合理的，希望能够说服你，如果您觉得只支持一次使用就可以了，麻烦回复一下，我就修改API了或其它方式。多谢！
