### ISSUE TITLE
对请求的参数排序，然后 md5加密下，再把加密结果当做一个参数，怎么操作呀

### ISSUE THREAD

**Issue by LiberalChen** [yuantiku/YTKNetwork#399]
对请求的参数排序，然后 md5加密下，再把加密结果当做一个参数传进去，我用 
    [config addUrlFilter:urlFilter]; 方法设置了一些全局参数，我想对所有的参数排序一下，怎么做呢？

**Comment by bluesky0109** [comment]
@LiberalChen 最终是如何实现的能分享下吗？ 如何做到对代码最小化入侵 对所有参数排序然后算出加密参数 最后放到请求中？

**Comment by LiberalChen** [comment]
`- (NSString *)filterUrl:(NSString *)originUrl withRequest:(YTKBaseRequest *)request {
    
    NSMutableDictionary *parameters = [_arguments mutableCopy];
    [request.requestArgument enumerateKeysAndObjectsUsingBlock:^(id  _Nonnull key, id  _Nonnull obj, BOOL * _Nonnull stop) {
        [parameters setObject:obj forKey:key];
    }];
    
    NSMutableDictionary *arguments = [_arguments mutableCopy];
    arguments[@"sign"] = [self createMD5Sign:parameters];
    
    return [self urlStringWithOriginUrlString:originUrl appendParameters:arguments];
}`

**Comment by LiberalChen** [comment]
在YTKUrlArgumentsFilter类里改了改，代码如上
