### ISSUE TITLE
关于断点续传，现在只有一个start方法，每次都重新下载，如何从上一个进度继续下载呢？

### ISSUE THREAD

**Issue by liangang** [yuantiku/YTKNetwork#41]
![ewkr daha dj1h 0 7tn1f](https://cloud.githubusercontent.com/assets/4946579/5890868/fa08d0cc-a4ac-11e4-94da-8f4033a2bed6.jpg)
覆盖了这个方法，但是不知道怎么从上次的进度继续下载，只看到一个start方法
希望大神告知

**Comment by liangang** [comment]
![d_ 88i5t9si ny rfq olv7](https://cloud.githubusercontent.com/assets/4946579/5890891/1cb88648-a4ae-11e4-95bb-2894754ddaa2.jpg)
实现部分

**Comment by tangqiaoboy** [comment]
只要覆盖了 resumableDownloadPath 方法，就会自动开启断点续传功能。start方法会调用时，会看有没有上次下载到一半的文件，如果有，就会断点续传继续下载。

**Comment by torrlau** [comment]
hello，AF默认是utf8的，请问其他编码，例如繁体编码big5的，如何解析呢？能看到data，但是不是json，谢谢

**Comment by liangang** [comment]
resumableDownloadPath 这个方法里面的路径是下载完成的存放路径么？  那么断点续传应该判断的是临时文件的大小然后再继续吧？我找到一个AF自己生成的下载临时路径
![7db01d0c-b3a0-4eb1-892f-d27d3edca25d](https://cloud.githubusercontent.com/assets/4946579/5896425/2e3e1d3e-a570-11e4-8cf0-e185c0e90880.png)
但是每次调用start都会生成一个新的临时文件，没有接着继续下。

**Comment by tangqiaoboy** [comment]
你的临时文件名应该需要指定一下，resumableDownloadPath 应该返回具体的缓存文件名，而不是一个目录。

**Comment by liangang** [comment]
![image](https://cloud.githubusercontent.com/assets/4946579/6101674/19b1584c-b063-11e4-8ca0-cfcdecfaaed3.png)
我已经指定了一个文件路径，但是，每次调用start的时候 ，他还是重新下载了.....  能提供一个demo指导一下么

**Comment by thewingofthesky** [comment]
请问临时文件名应该如何指定？在start之前requestOperation是nil。

**Comment by tangqiaoboy** [comment]
那有可能是服务器端不支持 range 方式断点续传。  

--  
唐巧

Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by liangang** [comment]
找到原因了，当程序下载到一半的时候，关闭APP，再打开APP重新下载，并不可以接着上次的进度。当程序运行的时候，暂停后是可以继续的，但是关闭后再打开下载不接着下载。应该还是重新alloc后临时文件的名字变了。

**Comment by liangang** [comment]
是否有办法保持这个文件命名？

**Comment by liangang** [comment]
![image](https://cloud.githubusercontent.com/assets/4946579/6102951/2cabb6f2-b079-11e4-8cf7-7b66bee72421.png)
是afnetworking的问题，用的是绝对路径，切了一下 好了...

**Comment by tangqiaoboy** [comment]
OK，那我把这个 issue 关了。

**Comment by yangfangkuo** [comment]
这个应该是本地沙盒目录一直改变的问题 这个是bug吧 系统的沙盒目录是一直变化的 但是这个操作的方法 使用绝对路径生成的md5 肯定是一直找不到合适的本地缓存的 应该是系统bug

**Comment by yangfangkuo** [comment]
app的沙盒目录 为了安全是会动态变化的,但是看YTK的代码 是把绝对路径生成了md5 这个就是每次重启(沙盒目录变化 )找不到对应的续传使用的data的原因
