### ISSUE TITLE
为什么不在YTKRequest.h网络请求类中给一个解析网络数据的方法，这样用户就可以直接转化成自己想要的model了，而不需要到VC中去解析

### ISSUE THREAD

**Issue by gaodeying998** [yuantiku/YTKNetwork#419]
为什么不在YTKRequest.h网络请求类中给一个解析网络数据的方法，这样用户就可以直接转化成自己想要的model了，而不需要到VC中去解析

**Comment by ShannonChenCHN** [comment]
解析数据跟网络请求的逻辑其实应该是分开的，如果是解析过程比较复杂，你可以在拿到回调数据后，再将数据交给数据解析类去处理；如果解析过程成比较简单，可以直接在 VC 中处理或者通过继承 `YTKRequest` 再封装一层处理业务的网络请求基类。

**Comment by skyline75489** [comment]
Thanks @ShannonChenCHN
