### ISSUE TITLE
我的app中的网络请求不同的模块发不同的url地址，baseurl也不同，请问怎么搞。

### ISSUE THREAD

**Issue by jbasttdi** [yuantiku/YTKNetwork#42]
你好，现在我的app中a模块中的请求地址是：http://192.168.1.1:8081/api1, 而我同一个app中b模块的请求地址是：http://192.168.1.2:8000/api2/getUserInfo   ,那我怎么设置baseUrl呢？
谢谢。

**Comment by tangqiaoboy** [comment]
可以在子类中指定完整的URL路径，这样就会忽略在 YTKNetworkConfig 中的base url设置。

**Comment by jbasttdi** [comment]
谢谢
