### ISSUE TITLE
AFNetworing 3.2 会引起 A security policy configured with `AFSSLPinningModeCertificate` can only be applied on a manager with a secure base URL (i.e. https)

### ISSUE THREAD

**Issue by keepyounger** [yuantiku/YTKNetwork#424]
AFNetworing 3.2 会引起 A security policy configured with `AFSSLPinningModeCertificate` can only be applied on a manager with a secure base URL (i.e. https)
AFNetworing 3.1 无此问题，原因在于 AFNetworing 3.2 需要一个https开头的BaseURL，如果设置AFSSLPinningModeCertificate的话，我看到YTK源码里面没有初始化AFNetworing的BaseURL

**Comment by SuooL** [comment]
请问您是如何解决这个问题的呢.

**Comment by keepyounger** [comment]
@SuooL 继续使用AF3.1

**Comment by HaiTeng-Wang** [comment]
@keepyounger 请问谁告诉你“AFNetworing 3.1 无此问题”。不要瞎说行吗？你试过吗？

AF3.1 和 AF3.2此处代码有何区别吗？
```
- (void)setSecurityPolicy:(AFSecurityPolicy *)securityPolicy {
    if (securityPolicy.SSLPinningMode != AFSSLPinningModeNone && ![self.baseURL.scheme isEqualToString:@"https"]) {
        NSString *pinningMode = @"Unknown Pinning Mode";
        switch (securityPolicy.SSLPinningMode) {
            case AFSSLPinningModeNone:        pinningMode = @"AFSSLPinningModeNone"; break;
            case AFSSLPinningModeCertificate: pinningMode = @"AFSSLPinningModeCertificate"; break;
            case AFSSLPinningModePublicKey:   pinningMode = @"AFSSLPinningModePublicKey"; break;
        }
        NSString *reason = [NSString stringWithFormat:@"A security policy configured with `%@` can only be applied on a manager with a secure base URL (i.e. https)", pinningMode];
        @throw [NSException exceptionWithName:@"Invalid Security Policy" reason:reason userInfo:nil];
    }

    [super setSecurityPolicy:securityPolicy];
}

```

**Comment by HaiTeng-Wang** [comment]
@keepyounger 我特码想干死你丫的。艹。

**Comment by keepyounger** [comment]
@HaiTeng-Wang 逗比，AF3.1有这个方法吗，本来不想和逗比说话，但怕逗比误导更多人。

**Comment by keepyounger** [comment]
### **原来就是前几天丢人丢到国外的人，怪不得，这年头喷子都会写代码了。哦不，喷子不会写，是喷代码。**

![image](https://user-images.githubusercontent.com/6264752/41830882-32b9153a-7876-11e8-821b-9b5e725f85f5.png)

**Comment by HaiTeng-Wang** [comment]
@keepyounger 之前提issues只是开个玩笑，你给我翻出来干什么？自己看去好吗？

 版本：'AFNetworking', '~> 3.1'

 文件：AFHTTPSessionManager

 代码：103 行。

谁是逗比？

**Comment by HaiTeng-Wang** [comment]
想想都来气，你特码萨比。骂死你丫的。

**Comment by keepyounger** [comment]
@HaiTeng-Wang  你那是3.1 开玩笑  使用3.1要这么写 pod 'AFNetworking', '3.1.0'   pod 不会用？

**Comment by keepyounger** [comment]
@HaiTeng-Wang  马上就被自己的无知气死了吧

**Comment by HaiTeng-Wang** [comment]
@keepyounger 被自己气死了。Sorry。忽略细节了。确实OK。

**Comment by AllisonWangJiaoJiao** [comment]
设置了https开头的BaseURL后，报错
error:Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://nfmedia.com:8000/login_app?username=fulz&password=1, NSLocalizedDescription=cancelled, NSErrorFailingURLKey=https://nfmedia.com:8000/login_app?username=fulz&password=1}
