### ISSUE TITLE
请问如何在MRC项目下使用YTKNetwork框架

### ISSUE THREAD

**Issue by yongshideweiyi** [yuantiku/YTKNetwork#428]

**Comment by yongshideweiyi** [comment]
我在一个MRC的项目中使用pods方式下载了YTKNetwork，只要我写继承与YTKRequest的类
@interface BaseRequest : YTKRequest
就会报错
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_YTKRequest", referenced from:
      _OBJC_CLASS_$_BaseRequest in BaseRequest.o
  "_OBJC_METACLASS_$_YTKRequest", referenced from:
      _OBJC_METACLASS_$_BaseRequest in BaseRequest.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
请问，我还需要做其他什么修改吗，或者这个错误如何解决？

**Comment by xhp281** [comment]
@yongshideweiyi 你这应该是有重复文件 BaseRequest 这个是不是有俩一样的

**Comment by skyline75489** [comment]
YTKRequest 不支持 MRC，需要 ARC 环境

**Comment by yongshideweiyi** [comment]
@xhp281 我开始也以为是重复了，但是我检查了好几遍都没问题，然后我把引入方式从pods换成直接拖代码到项目里然后把YTK加上标示就没问题了

**Comment by yongshideweiyi** [comment]
@skyline75489 谢谢，确实是这样，已经解决
