### ISSUE TITLE
一个YTKRequest子类只能处理一个api地址的网络请求吗？

### ISSUE THREAD

**Issue by jbasttdi** [yuantiku/YTKNetwork#43]
感谢提供这样的一个框架，我想问的是我们一般是一个模块中会发起4，5个不同的api请求，那是否要创建4，5个不同名称的YTKRequest子类分别处理不同的网络请求吗？那是不是挺麻烦的，有能用一个类处理多个api地址的方法吗。
比如：UserApi类中，有/getUserInfo/:id ,/login/:name/:pwd, /changename/:id/newname 这样的3个不同的api类，那我要创建3个YTKRequest子类吗，能不能只创建一个YTKRequest类，在同一个类中处理这3个网络请求呢。
谢谢！

**Comment by lancy** [comment]
基于Single Responsibility Principle，我们推荐的做法是不同逻辑的API分别封装成不同的子类。
如果你觉得这几个子类有共有的逻辑，你可以选择，抽成Utils方法或者抽成共有基类。
事实上，如果你真的喜欢，你的确可以在一个YTKRequest里面处理三种不同的请求，只需要init的时候赋予不同的参数，然后在构建Url的时候根据参数的不同返回不同的Url即可。

**Comment by jbasttdi** [comment]
是的，通过参数来进行不同的处理应该是可以的，只是要判断的地方有点多，requestUrl，requestMethod，requestArgument，jsonValidator等等函数中都要用类似if...else这种方式来处理，那还不如用不同的Request的类了。
