### ISSUE TITLE
定制网络请求的问题

### ISSUE THREAD

**Issue by aimm** [yuantiku/YTKNetwork#433]
您好，我覆写了- (NSURLRequest *)buildCustomUrlRequest这个方法，自定义了一个soap请求，请求返回结果也是xml的，在请求完成后都回调到了请求失败的block里，但是我想让它在请求成功的block中，该怎么做啊

**Comment by skyline75489** [comment]
`responseSerializerType` 返回 `YTKResponseSerializerTypeXMLParser`
