### ISSUE TITLE
请教如何用mantle把model转换成json字符串

### ISSUE THREAD

**Issue by jbasttdi** [yuantiku/YTKNetwork#44]
不好意思，看到你们这边也用了mantle,在这里想请教一下如何用mantle把复杂的model转换成json字符串，用jsonModel有个toJSONString方法是可以直接把model转换成json字符串的，包括一些承继和复杂的自定义对象都可以转换出来，但总找不到如果用mantle把model转成json字符串。只找到一个把model转成NSDictionary，
    NSDictionary *jsonDictionary = [MTLJSONAdapter JSONDictionaryFromModel:notice];
请教如何能转换成json字符串呢。
不甚感激！

**Comment by tangqiaoboy** [comment]
你是问如何把 NSDictionary 转成 NSString的 JSON 吗？

**Comment by jbasttdi** [comment]
谢谢回复，我是有这样的类结构：

@interface A : Entity
@property(strong,nonatomic) NSString* _id;
@property(strong,nonatomic) NSString* title;
@property(strong,nonatomic) SyncEntity *syncEntity;

@interface SyncEntity:NSObject
@property(strong,nonatomic) NSString* synctitle;
@property(strong,nonatomic) NSString* comments;

@interface Entity:NSObject
@property(strong,nonatomic) NSString* entityKey;
@property(strong,nonatomic) NSString* entityValue;

调用：
A *a=[[A alloc]init];
a._id=@"id";
a.title=@"title";
a.syncEntity=[[SyncEntity alloc]init];
a.syncEntity.synctitle=@"synctitle";
a.syncEntity.comments=@"comments";
a.entityKey=@"entityKey";
a.entityValue=@"entityValue";'

我想能获取这个jsonString字符串，我用了一些NSDictionary 转NSString 的方法，总是报错：
Invalid type in JSON write (SyncEntity)
实在搞不懂了，所以还想请您帮看看，是不是mantle在model转json字符串这块没这个功能呢？我用了JSONModel是可以实现这个转换的。
非常感谢！

**Comment by jbasttdi** [comment]
算了，我改用JSONModel吧。
