### ISSUE TITLE
关于请求失败重发的问题

### ISSUE THREAD

**Issue by Aoce** [yuantiku/YTKNetwork#446]
操作步骤：
1.发送请求A，用Charles使其失败；
2.在失败的Block回调中，继续发请求A；
3.无返回

经过查看源码发现：
1.在YTKNetworkAgent中，请求成功或失败的回调后，先传回成功或失败的回调；
2.然后再把请求从队列中删除；
3.但此时，我已经在失败的回调中又发送了请求，而删除请求是在错误回调后触发的，这时候删除的是我当前的request；
4.在该request返回的时候，会判断队列中有没有该request，如果没有就直接返回了，没有回调.

这里我的处理是在失败回调中延时调用重新发请求的操作，但感觉这里或许还有更好的解决方案，失败重发的机制应该挺普遍的吧.

**Comment by veecci** [comment]
每次发请求时，应该重新创建一个YTKRequest实例
