### ISSUE TITLE
YTKNetwork TDD

### ISSUE THREAD

**Issue by AllanChen** [yuantiku/YTKNetwork#45]
如何在YTKNETWORK 中做TDD 和 BDD ??

**Comment by tangqiaoboy** [comment]
不做TDD和BDD。

**Comment by AllanChen** [comment]
请教一下，测试阶段你们是用什么来做测试的？在不做TDD/BDD的情况之下，如何保证代码质量？

**Comment by tangqiaoboy** [comment]
移动端现在基本上各大公司都是黑盒测试，另外有一些monkey test和自动化测试，但主要的还是手工测。
