### ISSUE TITLE
关于UrlFilterProtocol设置公共参数的问题

### ISSUE THREAD

**Issue by longitachi** [yuantiku/YTKNetwork#451]
你好，想提一点建议，就是关于实现YTKUrlFilterProtocol这个协议设置公共参数，

现在这个协议提供的`- (NSString *)filterUrl:(NSString *)originUrl withRequest:(YTKBaseRequest *)request;`这个方法，仅仅是把公共参数拼接在url中，

那这种情况一般用在`GET`中，而`POST`请求时候我们需要把公共参数放到`form`里

这时候这个如果采用 #73  这个issue里所说的，子类在`requestArgument`方法中拼接上父类的参数，会很麻烦，所以建议这个协议里是不是增加一个类似 `- (id)filterParams:(id)originParams withRequest:(YTKBaseRequest *)request`的方法比较好点。

**Comment by xiaohuapunk** [comment]
`- (NSString *)filterUrl:(NSString *)originUrl withRequest:(YTKBaseRequest *)request` 方法的逻辑是你自己实现的吧，你可以获取 request.requestArgument 然后将需要添加的参数放进去，这样是不是可以

**Comment by xiaohuapunk** [comment]
`- (NSString *)filterUrl:(NSString *)originUrl withRequest:(YTKBaseRequest *)request `方法的逻辑是你自己实现的吧，你可以获取 `request.requestArgument `然后将需要添加的参数放进去，这样是不是可以
