### ISSUE TITLE
走Postman可以上图图片

### ISSUE THREAD

**Issue by JianWenXie** [yuantiku/YTKNetwork#456]
但是我用代码却无法上传
//
//  DemoRequest.m
//  LoveGuQin
//
//  Created by fox on 13/06/2018.
//  Copyright © 2018 Moemoe. All rights reserved.
//

#import "DemoRequest.h"
#import "AFNetWorking.h"
#import "MTUserModel.h"
@implementation DemoRequest {
    UIImage *_image;
}
- (NSString *)requestUrl {
    return @"api/uploadAva";
}
- (instancetype)initImage:(UIImage *)image {
    if (self = [super init]) {
        _image = image;
    }
    return self;
}

/**
 如果要添加请求头,可以实现这个方法

 @return nullable = 表示可以为null
 */
- (nullable NSDictionary<NSString *, NSString *> *)requestHeaderFieldValueDictionary {

    if ([MTUserModel shareUserModel].token.length > 0 ) {

        NSString *token = [NSString stringWithFormat:@"Bearer %@",[MTUserModel shareUserModel].token];
        return @{@"Authorization":token};
    }else {
        return nil;
    }
}

/**
 重写请求参数

 @return 请求参数
 */
//-(id)requestArgument {
//    //可以在这里检查参数是否有带Token
//    //如果没有这里可以补一个token
//    //    MTLog(@"%@",_dict);
////    NSData *data = UIImageJPEGRepresentation(_image, 0.9);
//    return _di;
//}

- (AFConstructingBlock)constructingBodyBlock {
    return ^(id<AFMultipartFormData> formData) {
        NSData *data = UIImageJPEGRepresentation(_image, 0.9);
        NSString *name = @"file";
        NSString *formKey = @"image";
        NSString *type = @"image/jpeg";
        [formData appendPartWithFileData:data name:formKey fileName:name mimeType:type];
    };
}

- (YTKRequestMethod)requestMethod {
    return YTKRequestMethodPOST;
}
@end

基类
//
//  MTRequest.m
//  LoveGuQin
//
//  Created by fox on 2018/5/30.
//  Copyright © 2018年 Moemoe. All rights reserved.
//

#import "MTRequest.h"
#import "MTUserModel.h"

@interface MTRequest()<YTKRequestAccessory>

@end
@implementation MTRequest {
    NSDictionary *_dict;
}

- (instancetype)initWithDict:(NSDictionary *)dict {
    if (self = [super init]) {
        _dict = dict;
//        [self addAccessory:self];
        
    }
    return self;
}

- (NSString *)baseUrl {
    return @"http://test.moemoetech.com";
}

/**
 重写请求参数

 @return 请求参数
 */
-(id)requestArgument {
    //可以在这里检查参数是否有带Token
    //如果没有这里可以补一个token
//    MTLog(@"%@",_dict);
    return _dict;
}

/**
 按照需重写 默认就post

 @return post
 */
- (YTKRequestMethod)requestMethod {
    return YTKRequestMethodPOST;
}

/**
 如果要添加请求头,可以实现这个方法

 @return nullable = 表示可以为null
 */
- (nullable NSDictionary<NSString *, NSString *> *)requestHeaderFieldValueDictionary {

    if ([MTUserModel shareUserModel].token.length > 0 ) {

      NSString *token = [NSString stringWithFormat:@"Bearer %@",[MTUserModel shareUserModel].token];
        return @{@"Authorization":token};
    }else {
         return nil;
    }
}

@end

   YTKNetworkAgent *agent = [YTKNetworkAgent sharedAgent];
    
    [agent setValue:[NSSet setWithObjects:@"application/json", @"text/plain", @"text/javascript", @"text/json",@"text/html",@"text/css", nil] forKeyPath:@"_manager.responseSerializer.acceptableContentTypes"];

    YTKNetworkConfig *confing = [YTKNetworkConfig sharedConfig];
    confing.baseUrl = @"http://test.moemoetech.com";

我上传图片的时候, 直接走了error信息.
而且error里面任何东西都没有直接为null

**Comment by JianWenXie** [comment]
Error Domain=com.alamofire.error.serialization.response Code=-1016 "Request failed: unacceptable content-type: text/html" UserInfo={NSLocalizedDescription=Request failed: unacceptable content-type: text/html, NSErrorFailingURLKey=http://test.moemoetech.com/api/uploadAva, com.alamofire.serialization.response.error.data=<20>, com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x1c0231e00> { URL: http://test.moemoetech.com/api/uploadAva } { Status Code: 200, Headers

**Comment by JianWenXie** [comment]
NSData *data = UIImageJPEGRepresentation(_image, 0.9);
            NSString *name = @"file.png";
            NSString *formKey = @"file";
            NSString *type = @"png/jpeg/jpg";

抱歉,最后查阅了点基本知识,解决了...
丢人现眼了[捂脸]

**Comment by webMing** [comment]
既然问题已经解决了，可以把问题关闭了 @JianWenXie

**Comment by songc1992** [comment]
所以最后是怎么解决的？
