### ISSUE TITLE
关于文件上传

### ISSUE THREAD

**Issue by JianWenXie** [yuantiku/YTKNetwork#457]
### 提出问题前请先确认完成了下列几项步骤 New Issue Checklist

* [ ] 我已经阅读过 [贡献指南](CONTRIBUTING.md) I have read and understood the [CONTRIBUTING guide](CONTRIBUTING.md)
* [ ] 我已经阅读过 [程序文档]((http://cocoadocs.org/docsets/YTKNetwork)) I have read the [Documentation](http://cocoadocs.org/docsets/YTKNetwork)
* [ ] 我已经证实这个问题来源于 YTKNetwork 本身，而不是其所依赖的 [AFNetworking](https://github.com/AFNetworking/AFNetworking) I have confirmed that this issue is caused by YTKNetwork, not [AFNetworking](https://github.com/AFNetworking/AFNetworking)
* [ ] 我已经在项目的 [问题列表](https://github.com/yuantiku/YTKNetwork/issues) 中搜索过并且没有找到类似问题 I have searched for a similar issue in the [project](https://github.com/yuantiku/YTKNetwork/issues) and found none

### 问题描述 Issue Description

请给出所提出问题的详尽描述，包括具体的错误信息，打印的堆栈等等，以及重现此问题的具体步骤。

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

![cf966376-44df-4520-a5c5-53ccab258afc](https://user-images.githubusercontent.com/22439948/41864341-38708844-78dc-11e8-9567-5cdf2bf738c7.png)
关于像这种表单形式提交,该如何用YTKNework实现??
能给一个示例吗?
万分感谢!!!

**Comment by xiaohuapunk** [comment]
```
// 上传的图片资源
- (AFConstructingBlock)constructingBodyBlock {
    return ^(id<AFMultipartFormData> formData) {
        NSData *data = UIImageJPEGRepresentation(_image, 0.8);
        NSString *name = @"picture.jpg";
        NSString *formKey = @"file";
        NSString *type = @"image/jpeg";
        [formData appendPartWithFileData:data name:formKey fileName:name mimeType:type];
    };
}

// 附加的其他参数
- (id)requestArgument
{
    return @{@"title":@"title",...};
}
```

这样不行吗？

**Comment by JianWenXie** [comment]
可以,万分感谢.已经解决.
实际上YTKNetwork params 拼接的参数,最终是会在form-data中的
