### ISSUE TITLE
YTKNetworkAgent中AFHTTPSessionManagere现在可以通过什么方式修改。

### ISSUE THREAD

**Issue by MartinWong-H** [yuantiku/YTKNetwork#461]
您好，现在因为设置https证书的原因，调用到了
  _manager.securityPolicy = _config.securityPolicy;
从而跑到了AFNetworking的setSecurityPolicy里面去了
    if (securityPolicy.SSLPinningMode != AFSSLPinningModeNone && ![self.baseURL.scheme isEqualToString:@"https"]) {
        NSString *pinningMode = @"Unknown Pinning Mode";
        switch (securityPolicy.SSLPinningMode) {
            case AFSSLPinningModeNone:        pinningMode = @"AFSSLPinningModeNone"; break;
            case AFSSLPinningModeCertificate: pinningMode = @"AFSSLPinningModeCertificate"; break;
            case AFSSLPinningModePublicKey:   pinningMode = @"AFSSLPinningModePublicKey"; break;
        }
        NSString *reason = [NSString stringWithFormat:@"A security policy configured with `%@` can only be applied on a manager with a secure base URL (i.e. https)", pinningMode];
        @throw [NSException exceptionWithName:@"Invalid Security Policy" reason:reason userInfo:nil];
    }
但是manager并没有接口可以设置baseURL，请问这样可以怎么处理呢？

**Comment by skyline75489** [comment]
#424 用 3.1 版本的 AFN
