### ISSUE TITLE
使用YTKBatchRequest类承载多个Request请求，不走block方法

### ISSUE THREAD

**Issue by bowenhx** [yuantiku/YTKNetwork#47]
```
#import "YTKRequest.h"

@interface GetImageApi : YTKRequest
@end

#import "GetImageApi.h"

@implementation GetImageApi
- (id)init
{
    self = [super init];
    if (self) {
    }
    return self;
}
- (NSString *)requestUrl {
    return @"?mod=stand&op=forumtj";
}
- (YTKRequestMethod)requestMethod {
    return YTKRequestMethodPost;
}

@end

/////////////////////////////////
#import "YTKRequest.h"

@interface GetUserInfoApi : YTKRequest

- (id)initWithType:(NSString *)type;

@end

#import "GetUserInfoApi.h"

@implementation GetUserInfoApi {
    NSString *_type;
}

- (id)initWithType:(NSString *)type {
    self = [super init];
    if (self) {
        _type = type;
    }
    return self;
}

- (NSString *)requestUrl {
    return @"?mod=home&op=favorite";
}
- (YTKRequestMethod)requestMethod {
    return YTKRequestMethodPost;
}
- (id)requestArgument {
    return @{ @"token": @"YOeQWfl5shWJSKccidIf9AzdiRPI",
              @"type":_type,
              @"page":@(1)
              };
}
@end

////////////////////////////////////////////////////////////////////
@interface ViewController ()

@end

@implementation ViewController

/// Send batch request
- (void)sendBatchRequest {
   
  GetImageApi *a = [[GetImageApi alloc] init];
    GetUserInfoApi *b = [[GetUserInfoApi alloc] initWithType:@"all"];
    
    [a startWithCompletionBlockWithSuccess:^(YTKBaseRequest *request) {
        NSLog(@"respond11111 = %@",request.responseJSONObject);
        
    } failure:^(YTKBaseRequest *request) {
        
    }];
    
    [b startWithCompletionBlockWithSuccess:^(YTKBaseRequest *request) {
        NSLog(@"respond22222 = %@",request.responseJSONObject);
    } failure:^(YTKBaseRequest *request) {
        
    }];
}
```

2015-02-11 21:42:29.001 YTKNetworkDemo[1070:55786] Add request: GetImageApi
2015-02-11 21:42:29.013 YTKNetworkDemo[1070:55786] Add request: GetUserInfoApi
2015-02-11 21:42:29.439 YTKNetworkDemo[1070:55786] Finished Request: GetUserInfoApi
2015-02-11 21:42:31.804 YTKNetworkDemo[1070:55786] respond22222 = {
    data =     (
                {
            dateline = "4\U5c0f\U65f6\U524d";
            description = "";
            favid = 127;
            icon = "http://i.gugubaby.com/dz/static/image/feed/discuz.gif";
            id = 286;
            idtype = fid;
            spaceuid = 0;
            title = "\U6cf0\U5c71-\U4e94\U5cb3\U4e4b\U5c0a";
            uid = 190;
            url = "http://i.gugubaby.com/dz/BAPI/index.php?mod=forum&op=forumdisplay&ver=1.0&app=ios&fid=286";
        },
                {
            dateline = "9\U5c0f\U65f6\U524d";
            description = "";
            favid = 124;
            icon = "http://i.gugubaby.com/dz/static/image/feed/discuz.gif";
            id = 319;
            idtype = fid;
            spaceuid = 0;
            title = "\U5e16\U5b50\U6d4b\U8bd5";
            uid = 190;
            url = "http://i.gugubaby.com/dz/BAPI/index.php?mod=forum&op=forumdisplay&ver=1.0&app=ios&fid=319";
        },

2015-02-11 21:42:31.836 YTKNetworkDemo[1070:55786] Request queue size = 1
2015-02-11 21:42:31.836 YTKNetworkDemo[1070:55786] Finished Request: GetImageApi
2015-02-11 21:42:31.837 YTKNetworkDemo[1070:55786] respond11111 = {
    data =     {
        list =         (
                        {
                addtime = 1423117172;
                dateline = "2015-02-05 14:19";
                fid = 250;
                fup = 214;
                id = 4;
                imgurl = "http://i.gugubaby.com/dz/BAPI/admins/resource/uploadfile/imgfile/";
                lastpost = "";
                lastposter = "<null>";
                lastsubject = "";
                name = "\U957f\U5b59\U65e0\U5fcc";
                replies = "<null>";
                views = "<null>";
            },
                        {
                addtime = 1423117241;
                dateline = "2015-02-05 14:20";

用YTKBatchRequest 来承载请求不走block 方法，求解决，具体看下面：
```
/// Send batch request
- (void)sendBatchRequest 
{
    
    GetImageApi *a = [[GetImageApi alloc] init];
    GetUserInfoApi *b = [[GetUserInfoApi alloc] initWithType:@"all"];
    
//    [a startWithCompletionBlockWithSuccess:^(YTKBaseRequest *request) {
//        NSLog(@"respond11111 = %@",request.responseJSONObject);
//        
//    } failure:^(YTKBaseRequest *request) {
//        
//    }];
//    
//    [b startWithCompletionBlockWithSuccess:^(YTKBaseRequest *request) {
//        NSLog(@"respond22222 = %@",request.responseJSONObject);
//    } failure:^(YTKBaseRequest *request) {
//        
//    }];
    
    YTKBatchRequest *batchRequest = [[YTKBatchRequest alloc] initWithRequestArray:@[a, b]];
    [batchRequest startWithCompletionBlockWithSuccess:^(YTKBatchRequest *batchRequest) {
        NSLog(@"succeed"); //此处不走
        NSArray *requests = batchRequest.requestArray;
        GetImageApi *a = (GetImageApi *)requests[0];
        GetUserInfoApi *b = (GetUserInfoApi *)requests[1];
        // deal with requests result ...
        NSLog(@"a = \n%@, b = \n%@", a.responseJSONObject, b.responseJSONObject);
    } failure:^(YTKBatchRequest *batchRequest) {
        NSLog(@"failed");
    }];
}
```

2015-02-11 22:00:22.616 YTKNetworkDemo[1106:60745] Add request: GetImageApi
2015-02-11 22:00:22.620 YTKNetworkDemo[1106:60745] Add request: GetUserInfoApi
2015-02-11 22:00:22.621 YTKNetworkDemo[1106:60745] Request queue size = 1
2015-02-11 22:00:22.626 YTKNetworkDemo[1106:60745] Request queue size = 0
2015-02-11 22:00:22.658 YTKNetworkDemo[1106:60745] Finished Request: (null)
2015-02-11 22:00:22.659 YTKNetworkDemo[1106:60745] Request queue size = 0
2015-02-11 22:00:22.659 YTKNetworkDemo[1106:60745] Finished Request: (null)
2015-02-11 22:00:22.659 YTKNetworkDemo[1106:60745] Request queue size = 0

**Comment by tangqiaoboy** [comment]
@lancy  这个应该是 YTKBatchRequest 的一个bug，它没有持有自己，所以造成他自己被释放了。

**Comment by tangqiaoboy** [comment]
@bowenhx 我们稍后修复一下。

**Comment by tangqiaoboy** [comment]
@bowenhx  我把这个bug修复了，麻烦你再测试一下。需要使用 master 分支的最新提交。并且需要增加 `YTKBatchRequestAgent.h` 和 `YTKBatchRequestAgent.m` 到项目中。
