### ISSUE TITLE
[YTKNetworkUtils stringEncodingWithRequest:] 奔溃了

### ISSUE THREAD

**Issue by wzi90921** [yuantiku/YTKNetwork#479]
| +[YTKNetworkUtils stringEncodingWithRequest:] (YTKNetworkPrivate.m:127)
-- | --
 | -[YTKNetworkAgent handleRequestResult:responseObject:error:] (YTKNetworkAgent.m:322)
 | __113-[YTKNetworkAgent dataTaskWithHTTPMethod:requestSerializer:URLString:parameters:constructingBodyWithBlock:error:]_block_invoke (YTKNetworkAgent.m:458)
 | __72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke_2.117 (AFURLSessionManager.m:248)

**Comment by wzi90921** [comment]
CoreFoundation | CFStringGetCString + 88
-- | --
CoreFoundation | CFStringConvertIANACharSetNameToEncoding + 124
CoreFoundation | CFStringConvertIANACharSetNameToEncoding + 124
 SmartReading_Student | +[YTKNetworkUtils stringEncodingWithRequest:] (YTKNetworkPrivate.m:127)
| -[YTKNetworkAgent handleRequestResult:responseObject:error:] (YTKNetworkAgent.m:322)
| __113-[YTKNetworkAgent dataTaskWithHTTPMethod:requestSerializer:URLString:parameters:constructingBodyWithBlock:error:]_block_invoke (YTKNetworkAgent.m:458)
| __72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke_2.117 (AFURLSessionManager.m:248)

**Comment by joeshang** [comment]
已在 2.1.3 中尝试修复
