### ISSUE TITLE
请问有相应的androidth版本吗？

### ISSUE THREAD

**Issue by jbasttdi** [yuantiku/YTKNetwork#48]
感谢提供这么个好框架，已经用在我们的项目中，请问一下YTKNetwork有对应的Android版本吗，或有类似这样的提供缓存，封装的第三方库吗。
谢谢

**Comment by tangqiaoboy** [comment]
我们公司的Android版应该也有类似的功能，不过因为我并不负责相关的技术，所以不知道是否抽象得足够好能够方便开源出来。
