### ISSUE TITLE
Error Domain=com.yuantiku.request.validation Code=-8 "Invalid status code" UserInfo={NSLocalizedDescription=Invalid status code}

### ISSUE THREAD

**Issue by panghaoyuan** [yuantiku/YTKNetwork#480]
我看了好几个回答.没一个说清楚具体为啥会这样.跪求官方能说一下.这个怎么处理.
跪求
跪求

**Comment by skyline75489** [comment]
代码中默认对 statusCode 有要求：https://github.com/yuantiku/YTKNetwork/blob/a2ad5de23ca2b965a90df142fe68627919ccb735/YTKNetwork/YTKBaseRequest.m#L202

如果 statusCode 不在这个范围，就会报上面的错

**Comment by xhjss** [comment]
为什么在将要显示view里调用网络请求就报Invalid status code

**Comment by topws** [comment]
> 为什么在将要显示view里调用网络请求就报Invalid status code

有找到具体原因吗？
