### ISSUE TITLE
HTTP PUT METHOD constructingBodyBlock 缺失

### ISSUE THREAD

**Issue by vbonluk** [yuantiku/YTKNetwork#482]
### 提出问题前请先确认完成了下列几项步骤 New Issue Checklist

* [* ] 我已经阅读过 [贡献指南](CONTRIBUTING.md) I have read and understood the [CONTRIBUTING guide](CONTRIBUTING.md)
* [* ] 我已经阅读过 [程序文档]((http://cocoadocs.org/docsets/YTKNetwork)) I have read the [Documentation](http://cocoadocs.org/docsets/YTKNetwork)
* [*] 我已经证实这个问题来源于 YTKNetwork 本身，而不是其所依赖的 [AFNetworking](https://github.com/AFNetworking/AFNetworking) I have confirmed that this issue is caused by YTKNetwork, not [AFNetworking](https://github.com/AFNetworking/AFNetworking)
* [* ] 我已经在项目的 [问题列表](https://github.com/yuantiku/YTKNetwork/issues) 中搜索过并且没有找到类似问题 I have searched for a similar issue in the [project](https://github.com/yuantiku/YTKNetwork/issues) and found none

### 问题描述 Issue Description

关联问题：#81 @nonstriater

为何不支持PUT的body里面放文件呢？我的业务API恰好是用PUT来上传文件了。请问有没有办法支持呢？

![image](https://user-images.githubusercontent.com/7578155/53066415-b2f73000-350a-11e9-8dde-15d04d2030e0.png)

![image](https://user-images.githubusercontent.com/7578155/53066417-b7234d80-350a-11e9-8ef3-0f28dfcdd247.png)

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by 18734791527** [comment]
能尽快解决吗我也遇到了PUT上传文件的问题

**Comment by 18734791527** [comment]
查了一下，发现AFNetwork就没支持.....🤦‍♂️ 🤦‍♂️ 🤦‍♂️
我让后台改了请求方式
