### ISSUE TITLE
关于 AFNetworking 中 UIKit 子库携带 UIWebView 分类问题

### ISSUE THREAD

**Issue by FlameTinary** [yuantiku/YTKNetwork#499]
近日, 在提交App store 的时候发现苹果已经不支持 UIWebView 相关功能, 并且如果 App 带有 UIWebView 相关的功能会拒绝上架请求;

在过滤相关功能的时候发现 AFNetworking 的 UIKit 子库中带有 UIWebView 的分类;

请问, 这个分类会对审核造成影响吗? 

如果会造成影响的话您会对此做什么处理?

**Comment by raopipi** [comment]
这个库 不会不维护了吧？

**Comment by joeshang** [comment]
新版本 2.1.2 将 AFNetworking 中的 UIWebView 移除，感谢你的反馈。
