### ISSUE TITLE
如果接口中的baseUrl有一个例外的该怎么做，用哪个方法可以为单独的一个接口设置例外的baseUrl？

### ISSUE THREAD

**Issue by humf** [yuantiku/YTKNetwork#51]

**Comment by lancy** [comment]
重载`YTKRequest`的`requestUrl`方法，直接返回完整的带http开头的url，就会忽略baseUrl的设置。
相关实现代码可以参考`YTKNetworkAgent.m:55`的`buildRequestUrl:`方法。
