### ISSUE TITLE
AFN已经更新到4.0了，希望YTK也能跟上

### ISSUE THREAD

**Issue by MQL9011** [yuantiku/YTKNetwork#511]

**Comment by cocoadogs** [comment]
是的呢大神，貌似年底就不能提交包含UIWebView代码的APP了

**Comment by YuanJiaShuai** [comment]
2020年4月1日拒绝新提交应用包含UIWebView代码App，2020年12月31日，拒绝已上架之前应用更新带有UIWebView

**Comment by xiangBiaoOne** [comment]
> 是的呢大神，貌似年底就不能提交包含UIWebView代码的APP了

不是年底
ITMS-90809：不推荐的API使用-苹果将不再接受新的应用程序，使用UIWebView的4月30日，2020年和应用程序更新，使用UIWebView截至2020年12月。相反，使用WKWebView提高安全性和可靠性。学得更多（https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by Q14** [comment]
是的希望尽快跟上

**Comment by joeshang** [comment]
YTKNetwork 目前 2.1.4 版本已经移除了 UIWebView 的依赖，只依赖 AFNetwoking/NSURLSession，所以不用担心 ITMS-90809 问题
关于 AFNetworking 4.0 的更新，我们会尽快接入

**Comment by fanpengju** [comment]
新应用提交，直接被拒绝了， 现在依赖3.0的，3.0的上传包直接被拒绝，并不是审核被拒绝， 求更新

**Comment by ChanRoy** [comment]
希望能尽快进行关于 AFNetworking 4.0 的更新🥺🥺🥺

**Comment by joeshang** [comment]
> 新应用提交，直接被拒绝了， 现在依赖3.0的，3.0的上传包直接被拒绝，并不是审核被拒绝， 求更新

AFNetworking 有多个 Subspec，YTKNetwork 2.1.4 版本依赖的是 AFNetworking/NSURLSession，不包含 UIWebView。不知道你的具体情况，是如何确定就是使用 AFN 3.0 上传包就会直接被拒绝的？

Anyway，YTKNetwork 可以升级到 3.0 试试，AFN 已升级
