### ISSUE TITLE
你好，AFN更新4.0了，可否也跟进一下。

### ISSUE THREAD

**Issue by zR-Zr** [yuantiku/YTKNetwork#518]
### 提出问题前请先确认完成了下列几项步骤 New Issue Checklist

* [ ] 我已经阅读过 [贡献指南](CONTRIBUTING.md) I have read and understood the [CONTRIBUTING guide](CONTRIBUTING.md)
* [ ] 我已经阅读过 [程序文档]((http://cocoadocs.org/docsets/YTKNetwork)) I have read the [Documentation](http://cocoadocs.org/docsets/YTKNetwork)
* [ ] 我已经证实这个问题来源于 YTKNetwork 本身，而不是其所依赖的 [AFNetworking](https://github.com/AFNetworking/AFNetworking) I have confirmed that this issue is caused by YTKNetwork, not [AFNetworking](https://github.com/AFNetworking/AFNetworking)
* [ ] 我已经在项目的 [问题列表](https://github.com/yuantiku/YTKNetwork/issues) 中搜索过并且没有找到类似问题 I have searched for a similar issue in the [project](https://github.com/yuantiku/YTKNetwork/issues) and found none

### 问题描述 Issue Description

请给出所提出问题的详尽描述，包括具体的错误信息，打印的堆栈等等，以及重现此问题的具体步骤。

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by daichuan** [comment]
+1

**Comment by wy201807** [comment]
+1

**Comment by fanpengju** [comment]
+1

**Comment by UknowHui** [comment]
+1

**Comment by joeshang** [comment]
YTKNetwork [3.0.0 已发布](https://github.com/yuantiku/YTKNetwork/releases/tag/3.0.0)，依赖的 AFNetworking 更新到 4.x

**Comment by wangJS2345** [comment]
pod 安装后， AFNetworking 版本还是(3.2.1)

**Comment by wangJS2345** [comment]
> YTKNetwork [3.0.0 已发布](https://github.com/yuantiku/YTKNetwork/releases/tag/3.0.0)，依赖的 AFNetworking 更新到 4.x

pod 安装后， AFNetworking 版本是3.2.1

**Comment by fanpengju** [comment]
已收到，马上跟进，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wangJS2345"<notifications@github.com&gt;; 
发送时间: 2020年6月24日(星期三) 上午8:54
收件人: "yuantiku/YTKNetwork"<YTKNetwork@noreply.github.com&gt;; 
抄送: "樊鹏举"<798346437@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [yuantiku/YTKNetwork] 你好，AFN更新4.0了，可否也跟进一下。 (#518)





 
pod 安装后， AFNetworking 版本还是(3.2.1)

**Comment by joeshang** [comment]
> > YTKNetwork [3.0.0 已发布](https://github.com/yuantiku/YTKNetwork/releases/tag/3.0.0)，依赖的 AFNetworking 更新到 4.x
> 
> pod 安装后， AFNetworking 版本是3.2.1

你本地的 Podspec 库是否已经更新？pod repo update master（如果是 CDN，是 pod repo update trunk）
