### ISSUE TITLE
快速重复创建并取消请求，会导致报double free错误，然后崩溃

### ISSUE THREAD

**Issue by Wingzki** [yuantiku/YTKNetwork#54]
连续快速调用如下方法会导致程序崩溃。调用次数不确定，有时候四五次，有时候更多的时候崩溃。

- (void)getAutoComplateWithKeyWord:(NSString *)keyWord {
    
    if (self.autoComplateRequest.isExecuting) {
        [self.autoComplateRequest stop];
    }
    
    self.autoComplateRequest = [[QYAutoComplateRequest alloc] initWithKeyWord:keyWord];
    self.autoComplateRequest.isShowToast = NO;
    
    [self.autoComplateRequest startWithSuccess:^(id results, QYRequest *request) {
        
        if (request != self.autoComplateRequest) {
            return;
        }
        
        if (!self.isSearching) {
            
            if ([results isKindOfClass:[NSDictionary class]]) {
                
                self.searchKeyWords = results[@"entry"];
                
            }
            
        }
        
    } failure:^(QYRequestType type, QYRequest *request) {
        
    }];
    
}

**Comment by maojj** [comment]
add 和 remove request 的时候，现在处理了线程安全问题。这个应该也解决了。

**Comment by veecci** [comment]
不要使用isExecuting来判断request的状态，会导致线程安全问题

**Comment by tangqiaoboy** [comment]
@veecci 具体线程安全问题的场景是什么呢？
