### ISSUE TITLE
上传单个文件,希望可以增加上传进度状态的回调,

### ISSUE THREAD

**Issue by zhouyuan24** [yuantiku/YTKNetwork#55]
上传单个文件,希望可以增加上传进度状态的回调,

**Comment by tangqiaoboy** [comment]
这个功能当前还不支持。后面我们会考虑加上的。

**Comment by FutureChen** [comment]
上传图片的请求中添加这个方法可以实现，或者封装在自己上传文件的基类中去。 至于框架级的修改坐等唐巧大神他们搞定
 [netApi.requestOperation setUploadProgressBlock:^(NSUInteger bytesWritten, long long totalBytesWritten, long long totalBytesExpectedToWrite) {
        DMLog(@"Sent %lld of %lld bytes %.2f", totalBytesWritten, totalBytesExpectedToWrite,(double)totalBytesWritten/totalBytesExpectedToWrite);
    }];

**Comment by sesameImmortals** [comment]
@FutureChen  有应用示例吗？我想看一下。

**Comment by maojj** [comment]
1.0 不会改了 如 @FutureChen  代码 直接操作 requestOperation 吧

**Comment by yu0winter** [comment]
#import "AFHTTPRequestOperation.h"
after [request start];
use the fuction:
[request.requestOperation setUploadProgressBlock:progress];

**Comment by maojj** [comment]
YTK 2.0  正在开发， 也就是 AFN_3.x 分支

**Comment by ynot16** [comment]
现在还不支持吗

**Comment by woshilaozhang** [comment]
加一个方法就可以获取上传进度
- (NSURLSessionDataTask *)uploadTaskWithRequestSerializer:(AFHTTPRequestSerializer *)requestSerializer
                                                URLString:(NSString *)URLString
                                               parameters:(id)parameters
                                constructingBodyWithBlock:(nullable void (^)(id <AFMultipartFormData> formData))block
                                                 progress:(nullable void (^)(NSProgress *uploadProgress))uploadProgressBlock
                                                    error:(NSError * _Nullable __autoreleasing *)error {
    NSMutableURLRequest *urlRequest = nil;
    if (block) {
        urlRequest = [requestSerializer multipartFormRequestWithMethod:@"POST" URLString:URLString parameters:parameters constructingBodyWithBlock:block error:error];
    } else {
        urlRequest = [requestSerializer requestWithMethod:@"POST" URLString:URLString parameters:parameters error:error];
    }
    
    __block NSURLSessionDataTask *uploadDataTask = nil;
    uploadDataTask = [_manager dataTaskWithRequest:urlRequest uploadProgress:^(NSProgress * _Nonnull uploadProgress) {
        
        uploadProgressBlock(uploadProgress);
        
    } downloadProgress:^(NSProgress * _Nonnull downloadProgress) {
        
    } completionHandler:^(NSURLResponse * _Nonnull response, id  _Nullable responseObject, NSError * _Nullable _error) {
        [self handleRequestResult:uploadDataTask responseObject:responseObject error:_error];
    }];
    
    return uploadDataTask;

**Comment by woshilaozhang** [comment]
YTKBaseRequest.h
@property (nonatomic, copy, nullable) AFURLSessionTaskProgressBlock uploadDataTaskProgressBlock;

YTKNetworkAgent.m
case YTKRequestMethodPOST:
            if (request.uploadDataTaskProgressBlock) {
                return [self uploadTaskWithRequestSerializer:requestSerializer URLString:url parameters:param constructingBodyWithBlock:constructingBlock progress:request.uploadDataTaskProgressBlock error:error];
            } else {
                return [self dataTaskWithHTTPMethod:@"POST" requestSerializer:requestSerializer URLString:url parameters:param constructingBodyWithBlock:constructingBlock error:error];
            }

api.uploadDataTaskProgressBlock = ^(NSProgress * _Nonnull progress) {
        NSLog(@"progress========: %@", progress);
    };
