### ISSUE TITLE
关于图片缓存

### ISSUE THREAD

**Issue by hnzlk2014** [yuantiku/YTKNetwork#57]
图片默认是缓存的，那个图片缓存的机制是怎么样的呢？如果我要像json数据那样，判断图片数据是来自于缓存？或者获取图片缓存的路径？应该怎么做？

**Comment by maojj** [comment]
返回的图片数据没有做额外处理。需要缓存的话，需单独在做，但这部分有不少现成的 第三方图片缓存框架可以实现，如  https://github.com/rs/SDWebImage。
