### ISSUE TITLE
YTKNetwork 支持打印 命令行请求字符串

### ISSUE THREAD

**Issue by huangbaoyu** [yuantiku/YTKNetwork#58]
YTKNetwork 可以添加支持 打印 命令行请求字符串，例如 curl 命令
curl -X POST -H 'Content-Type: application/json; charset=utf-8' 'http://000.000.000.00:8080/xx/xx/xxx' -d '{}'

**Comment by maojj** [comment]
https://github.com/AFNetworking/AFNetworking/pull/314  matt 大神说了，有需要自己可以加一个 https://github.com/mattt/formatterkit.   把 Formatterkit 加到 YTKNetwork 不太合适。
比如在YTKRequest以category方式加个方法， 有个局限是需要start 后，等 self.requestOperation.request不是nil。
```
- (NSString *)curlCmdString {
    NSString *curlCmdString = [TTTURLRequestFormatter cURLCommandFromURLRequest:self.requestOperation.request];
    return curlCmdString;
}
```

**Comment by huangbaoyu** [comment]
嗯  我现在 是在自己 基类 写了这么 个方法  然后 请求 开始  或者  请求 成功后 打印  请求  和 返回 数据， 便于调试
