### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by xx-li** [yuantiku/YTKNetwork#59]
前几天，由于服务器维护。使用301重定向到另外一个地址，导致App没法请求到新的数据。 但是实际上有对AFNetworking的缓存策略做了修改：[AFHTTPRequestOperationManager manager].requestSerializer.cachePolicy = NSURLRequestReloadIgnoringCacheData;
但是，YTKNetwork 每次请求都会执行下列代码：
if (request.requestSerializerType == YTKRequestSerializerTypeHTTP) {
        _manager.requestSerializer = [AFHTTPRequestSerializer serializer];
    } else if (request.requestSerializerType == YTKRequestSerializerTypeJSON) {
        _manager.requestSerializer = [AFJSONRequestSerializer serializer];
    }
导致上面的代码设定失效。

YTKNetwork提供了把JSON数据以文件形式缓存在本地的自定义目录下的方法， 是不是应该把默认缓存协议改为 NSURLRequestReloadIgnoringCacheData？

**Comment by lancy** [comment]
一个是由客户端控制的缓存，一个是由服务端控制的缓存；我认为可以并存；
@tangqiaoboy @maojj 认为呢？

**Comment by maojj** [comment]
恩，可以并存的。 YTKNetwork 控制的是客户端缓存策略。
