### ISSUE TITLE
如何在设置了cacheTimeInSeconds缓存这种情况下更新缓存并获得新的数据

### ISSUE THREAD

**Issue by hnzlk2014** [yuantiku/YTKNetwork#60]
需求是这样的，设置了cacheTimeInSeconds大于0的，程序先调用缓存数据，再请求，再显示新数据。现在是这么个情况，就是第一次，使用的是缓存数据，start之前设置ignoreCache = YES，取新的请求数据，但是回调还是老的数据，其实这个时候缓存数据已经更新了，所以第二次程序执行的时候先用的缓存数据，所以数据更新了。请问有什么办法，第一次就能获取新的数据呢？

**Comment by hnzlk2014** [comment]
GetTimeApi *api = [[GetTimeApi alloc] init];
    if([api cacheJson]) {
        NSDictionary *json = [api cacheJson];
        NSLog(@"cache json = %@", json);
    }
    api.ignoreCache = YES;
    [api startWithCompletionBlockWithSuccess:^(YTKBaseRequest *request) {
        NSDictionary *json = request.responseJSONObject;
        NSLog(@"new jsondata:%@",json);
        NSLog(@"new jsonstring:%@",request.responseString);
    } failure:^(YTKBaseRequest *request) {
        NSLog(@"failed");
    }];
new jsondata和cache json的值一样，但是new jsonstring:却是正确的。下次执行时，cache joson结果会更新。
- (id)responseJSONObject {
    if (_cacheJson) {
        return _cacheJson;
    } else {
        return [super responseJSONObject];
    }
}
好像是因为这句，总是会返回缓存的数据。如果加个ignoreCache的判断，是否可以？

**Comment by lancy** [comment]
暂时建议调用过`cacheJson`后，重新创建一个新对象发请求。
我们正在考虑一下这个情况应该如何处理更好

```
GetTimeApi *loadCacheApi = [[GetTimeApi alloc] init];
if([loadCacheApi cacheJson]) {
    NSDictionary *json = [loadCacheApi cacheJson];
    NSLog(@"cache json = %@", json);
}
GetTimeApi *api = [[GetTimeApi alloc] init];
api.ignoreCache = YES;
[api startWithCompletionBlockWithSuccess:^(YTKBaseRequest *request) {
    NSDictionary *json = request.responseJSONObject;
    NSLog(@"new jsondata:%@",json);
    NSLog(@"new jsonstring:%@",request.responseString);
} failure:^(YTKBaseRequest *request) {
    NSLog(@"failed");
}]
```

**Comment by hnzlk2014** [comment]
我有这么一个需求，就是在没有网络的时候，我需要显示缓存数据，而ytk是按url和参数进行缓存的，参数中有个page,如果用户请求了N页，那第下次没有网络的时候，需要显示缓存的数据，这样似乎比较麻烦，不知道有没有的建议？

**Comment by bawn** [comment]
@lancy 确实需要改进下

**Comment by iOSDevCode** [comment]
如果当前VC上面动态变化的数据赋予一个Model。然后使用KVO去监听这边变化的数据可以吗？这样性能上面可能会有些消耗。

**Comment by maojj** [comment]
#106 设计思想是不要复用 request。

**Comment by xilin** [comment]
@lancy 这个issue里的信息和wiki上缓存一段的描述好像不太一致？wiki上并没有说要重新new一个request

**Comment by lancy** [comment]
@xilin 你说 Readme 里面么？我没看到有相关的描述，这个地方的确是没有说清楚。

**Comment by xilin** [comment]
@lancy https://github.com/yuantiku/YTKNetwork/blob/master/ProGuide.md#显示上次缓存的内容 
直接在检测完cacheJson之后又发起了`startWithCompletionBlockWithSuccess:failure:`
