### ISSUE TITLE
重用YTKRequest的缓存问题

### ISSUE THREAD

**Issue by xx-li** [yuantiku/YTKNetwork#64]
发现如果对一个YTKRequest 重复使用的话，会导致缓存问题。例如对一个YTKRequest修改了某个请求参数后， 重新执行start操作，但是不会将_cacheJson置空， 网络请求获取到新的数据后， 获取responseJSONObject， 由于代码如下：
- (id)responseJSONObject {
    if (_cacheJson) {
        return _cacheJson;
    } else {
        return [super responseJSONObject];
    }
}

导致获取的还是缓存， 但是实际进行了新的网络请求及获取到了新的数据。
我在start方法执行之前将_cacheJson置为nil后OK

**Comment by lancy** [comment]
`YTKRequest`目前并不支持重复使用，每次使用，都需要重新创建。
