### ISSUE TITLE
如何在库中使用cookie保存登录后返回的信息，并且在之后的请求中自动使用cookie

### ISSUE THREAD

**Issue by mlijin9011** [yuantiku/YTKNetwork#70]

**Comment by maojj** [comment]
cookie 是底层自动处理的，不需要额外处理。 登录后如果有返会 cookie  (如 persist cookie， session cookie 等)，下次请求匹配的域，则自动就带上相应 cookie 。

**Comment by chx632996066** [comment]
关闭App后，在下次打开app的时候还有对应的cookie带上吗？如果没有，应该如何保存cookie呢？

**Comment by maojj** [comment]
会带上的 除非主动清理
