### ISSUE TITLE
为什么startWithCompletionBlockWithSuccess执行后返回的responseString有数据，但是responseJSONObject为nil呢？

### ISSUE THREAD

**Issue by shiqyn** [yuantiku/YTKNetwork#72]
为什么startWithCompletionBlockWithSuccess执行后返回的responseString有数据，但是responseJSONObject为nil呢？
这样使得我jsonValidator老是失败。我按教程例子做的，是不是哪里错了？

**Comment by jbasttdi** [comment]
肯定返回的不是json格式的数据

**Comment by maojj** [comment]
贴一下代码 和返回的 responseString ？

**Comment by maojj** [comment]
参考下 #86  可能服务器设置有点问题。
