### ISSUE TITLE
如何添加多个api接口公用的header参数或query params

### ISSUE THREAD

**Issue by nonstriater** [yuantiku/YTKNetwork#73]
通常有这样的需求，在登录或注册以后，其余的借口需要在header里面带上token，或者query params上带上公用的一些参数。我设想的实现是：

@interface fillter1：NSObject<YTKUrlFilterProtocol>
@end

@implementation
- (NSString *)filterUrl:(NSString *)originUrl withRequest:(YTKBaseRequest *)request{
     if(originUrl != “login”){
          return originUrl?query1=xxx&query2=xxx;
     }
     return originUrl
}
@end

对于public query  params，这种实现应该没问题；但是对于public header filed，通过实现request公共子类，实现requestHeaderFieldValueDictionary这个方法添加public header filed

本来是想问问题的，写的过程中发现了实现方案。那就请大神确认下有没有问题，或者有没有其它更好的实现方式吧？

**Comment by maojj** [comment]
关于 public query params，  注意  originUrl 可能已经有'?' 了, 直接拼接一个，可能就出现两个'?'了。
可以参考这个 gist：  https://gist.github.com/maojj/4a5bf51fd0597f253e05

**Comment by nonstriater** [comment]
原来这样子，谢谢

**Comment by nonstriater** [comment]
再问下，如果api全部是post请求，怎么带公共参数呢

**Comment by maojj** [comment]
post 的 url 中同样是可以带公共的参数。  另一种方式是公共父类有通用参数， 子类返回参数时候再把父类参数拼起来。

**Comment by nonstriater** [comment]
你的意思大概是这样：

super: (baseRequest)
- requestArgument{
    return @{@"public":@"value"};
}


sub
- requestArgument{
   NSDictionary pub = [super requestArgument];
    return pub+@{};
}

**Comment by TuWei1992** [comment]
@nonstriater 在urlfilter 里面获取 requestArgs, 然后添加数据
