### ISSUE TITLE
建议在（YTKNetworkAgent.m 164行）加一条日志

### ISSUE THREAD

**Issue by nonstriater** [yuantiku/YTKNetwork#74]
![image](https://cloud.githubusercontent.com/assets/3192105/7669480/1c3efa88-fca8-11e4-88e2-d2a0696b59ca.png)

建议在这里加一条日志（YTKNetworkAgent.m 164行），不然url异常出现的error信息完全被过滤，上传业务拿到失败的request里面没有任何错误的线索~~

**Comment by bawn** [comment]
确实需要增加log信息

**Comment by jaybowong** [comment]
@nonstriater  你要找的应该是`ytkRequest.requestOperation.error`。

`YTKBaseRequest`中的`requestOperation`是继承于`AFURLConnectionOperation`，里面有一个NSError，这个error也正是`AFHTTPRequestOperation`失败的block中传回来的error，就是你截图中的那个error。

假设现在网络链接断开，可使用`ytkRequest.requestOperation.error.localizedDescription`来进行提示，断开网络的时候效果就是：`未能链接到服务器`。其他信息也在这里面。

打印log这个功能，现在我们项目是自己写的，继承一个YTKRequest子类，子类中复写了`requestCompleteFilter`和`requestFailedFilter`这两个方法，在这两个方法里打印log。
自己写log的一个好处就是随意控制想要打印的内容和格式。
比如成功的log和失败的log可以分别打印出不同的样子；业务上的错误和网络请求本身的错误可以提示得更加有区别。

如果更好一点的话，可以用[CocoaLumberjack](https://github.com/CocoaLumberjack/CocoaLumberjack) + [XcodeColors](https://github.com/robbiehanson/XcodeColors)，让错误的log更加明显。

**Comment by blackchena** [comment]
@jaybowong error. localizedDescription 里面的信息可以自定义吗？

**Comment by jaybowong** [comment]
@blackchena 自定义是指？

这里的NSError是系统返回的，能拿到它的错误码和描述，你可以根据错误码来自定义展现给用户的错误描述

**Comment by blackchena** [comment]
@jaybowong 我以为可以像应用名字国际化那种 自定义error. localizedDescription里面的信息。谢谢啦
