### ISSUE TITLE
使用意见

### ISSUE THREAD

**Issue by FutureChen** [yuantiku/YTKNetwork#76]
大神们 经过这一段时间的使用，提两个个意见
1、没有进行任何打印，在 将网络请求和httphead，以及请求结果打印出来，在开发阶段是非常必要的吧。
2、没有进行网络监测，网络断开的时候还会发起请求。

**Comment by maojj** [comment]
现在我是通过 po request.requestOperation 看请求的详情的。

**Comment by FutureChen** [comment]
我觉得这样挺不方便的。
那网络监测呢，断网的时候也发起请求，一般不是需要暂停挂起之类的。

**Comment by maojj** [comment]
这算是high level 的需求了，不同使用者可能需求不同，很难统一。现在是没有检测网络状态的，断网时候请求会发起，且faild，statusCode = 0， 需要自己处理断网情况，如提示，或者如你说的 暂停等待网络恢复后自动执行。
