### ISSUE TITLE
关于下载问题

### ISSUE THREAD

**Issue by wy19901227** [yuantiku/YTKNetwork#77]
首先 本框架是基于AF的，AF是对苹果的网络框架进行封装，我们用起来不需要了解太对苹果的api，对新手来说，而本框架是讲请求封装成对象，就想把json数据转化成Model’一样，这对于我们面向对象程序员来说，写起来会很舒服，这也是我习惯的编程方式，所以，我会一直用这个框架，遇到问题我斗会来说下，希望这个框架可以让使用AF的都过来用。

  开发过程中，我使用到了下载功能，在源码中，我发现，您是将下载请求也放在了和起来请求一样的manager中，这显然不是我们使用下载的需求，下载应该放在后台单独进行，而不影响其他页面的继续访问，所以我在源码中没把下载加到 manager的队列中，而是直接start。希望作者可以对这个需求进行更好的封装。

**Comment by iOSyan** [comment]
你好，我目前也有这个需求，请问你是怎么直接start的呢？

**Comment by duckls** [comment]
@iOSyan  你解决了吗  我也也有这个需求

**Comment by maojj** [comment]
已加优先级  YTKRequestPriority

**Comment by yangfangkuo** [comment]
加优先级不是根本解决问题的方式,加优先级,看源码的话,是使用的一个SessionManager,在iOS系统中,一个session默认的最多的tcp链接为4个 ,macOS为6个,如果同时有4个大文件的下载正在进行,这个时候 你即使进行一个优先级高的请求,这个请求也不会立刻响应, 这个处理方式应该是 使用不同的session,一般的普通请求,可以使用一个session来减少握手,遇到紧急的,还是需要单独一个session来保证及时响应,这个是我的个人意见,如有错误 ,请指出
