### ISSUE TITLE
 如果我们有自己的json加密机制，该怎么把这些加进去。

### ISSUE THREAD

**Issue by wzhifang** [yuantiku/YTKNetwork#79]
如果我们有自己的json加密机智，该怎么把这些加进去。不知道到您这个是不是支持啊。

**Comment by maojj** [comment]
这个json加密机制原理是怎样的？  整个字符串加密（json结构已被破坏）呢， 还是只是key和value加密，而json结构不变，或者其他方式？
可以根据加密机制在合适的时间加上解密过程。

**Comment by wzhifang** [comment]
是json结构已经破坏加密的，那加解密过程就是需要修改源代码是吧？

**Comment by maojj** [comment]
YTKBaseRequest 的 responseObject 有这个 getter方法：
```
- (id)responseJSONObject {
    return self.requestOperation.responseObject;
}
```
可以在这里试试，加上解密。 或者到 AFNetworking 那层去改 reponseString
