### ISSUE TITLE
AFNetworking第三方依赖关系

### ISSUE THREAD

**Issue by MooYoo** [yuantiku/YTKNetwork#8]
从YTKNetwork库来看的话，目前的AFNetworking并不是由cocospod管理起来的，那么问题来了，如果AFNetworking版本更新了，YTKNetworking如何更新第三方库？

**Comment by nilsun** [comment]
@tangqiaoboy    s.dependency "AFNetworking", "~> 2.0"    现在YTKNetworking一直使用的AFNetworking 2.0的版本？后续有同步AFNetworking更新的打算么？

**Comment by maojj** [comment]
不是指定 2.0 吧，是要求 2.0 以上， 例如用 pod install结果如下：
```
maojj@Sunny Demo  % pod install
Analyzing dependencies
Downloading dependencies
Installing AFDownloadRequestOperation (2.0.1)
Installing AFNetworking (2.5.4)
Installing YTKNetwork (0.4.0)
Generating Pods project
Integrating client project
```

可以看到 AFNetworking 使用的是 2.5.4
