### ISSUE TITLE
上传文件问题

### ISSUE THREAD

**Issue by wy19901227** [yuantiku/YTKNetwork#83]
我用这个框架 上传头像时 ios8 可以，ios7 报错
Error Domain=NSURLErrorDomain Code=-1021 "request body stream exhausted" UserInfo=0x78fc5dd0 {NSErrorFailingURLStringKey=http://admin.izhangchu.com:80/HandHeldKitchenCommunity/api/user/users!updateUserInfo.do, NSErrorFailingURLKey=http://admin.izhangchu.com:80/HandHeldKitchenCommunity/api/user/users!updateUserInfo.do, NSLocalizedDescription=request body stream exhausted, NSUnderlyingError=0x7bbdc630 "request body stream exhausted”}

看了 源码，应该是af得问题，但是这种post文件的方式是支持到ios6得啊，为什么ios7就不可以了。希望帮解决下。

**Comment by EggmanQi** [comment]
同问。
不过我是iOS 8 下一直会失败，转用 AFHTTPRequestOperationManager 就成功。

**Comment by duckls** [comment]
求问，同时上传多个文件或者图片的时候 。这么用

**Comment by maojj** [comment]
先关了，有问题再 reopen
