### ISSUE TITLE
如何自定义Http Header

### ISSUE THREAD

**Issue by YueHonghui** [yuantiku/YTKNetwork#84]
在发起restful请求时, 经常会有将Token放到Authorization这个http header里的需求,　有时还要自己设置User-Agent这个http header, 但在这个框架里没有找到这一块的接口. 请求怎么用这个框架实现这类需要自定义http header的需求?

**Comment by xserver** [comment]
/// 在HTTP报头添加的自定义参数
YTKBaseRequest - (NSDictionary *)requestHeaderFieldValueDictionary;
子类覆盖这个方法。
