### ISSUE TITLE
cacheSensitiveData YTKCacheDirPathFilterProtocol

### ISSUE THREAD

**Issue by lilin87788** [yuantiku/YTKNetwork#85]
YTKRequest 的这个cacheSensitiveData 这个接口
YTKNetworkConfig 里面这个协议YTKCacheDirPathFilterProtocol
cacheVersion 的使用场景 
这3 个  不太懂 谁能帮我解释 下吗，谢谢了

**Comment by maojj** [comment]
cacheSensitiveData： 现在只在 ``` - (NSString *)cacheFileName ``` 用到，其他没什么用。
YTKCacheDirPathFilterProtocol： 其功能为根据不同的 request 设置不同的缓存路径。
cacheVersion：如果缓存的文件还没有过期，但版本更新了，api 返回数据结构有变化时，需要丢弃缓存，所以用这个字段控制。

**Comment by Huang-Libo** [comment]
@lilin87788 @maojj 
根据@lancy最近的解释https://github.com/yuantiku/YTKNetwork/issues/198：
- cacheVersion 一般是服务端在其他地方返回的，重载的时候带上，如果 cacheVersion 和上次不一样，就会发请求。
- cacheSensitiveData 是在 cacheVersion 的基础上，再加上一些敏感数据，例如，加上 userId，这样当 userId 变化的时候，即使 cacheVersion 没有变，也会重新发请求
