### ISSUE TITLE
如何返回json数据responseJSONObject为空

### ISSUE THREAD

**Issue by overcls** [yuantiku/YTKNetwork#86]
如何返回json数据?

request.responseJSONObject为空

请帮忙下

**Comment by Ailix** [comment]
responseString >> {"rsm":2,"errno":1,"err":null}
responseJSONObject >> (null)

**Comment by overcls** [comment]
responseJSONObject 要让它返回信息怎么操作

**Comment by Ailix** [comment]
responseString有数据吗
有的话我这边临时的解决方法是把responseString转成字典

**Comment by overcls** [comment]
responseString是有的 ，但responseJSONObject没数据不科学哈

**Comment by xserver** [comment]
推测是 AFHTTPRequestOperation 做 responseSerializer 时出错了。
{
  "rsm": 2,
  "errno": 1,
  "err": null
}

把 err 改成 @""  试试，如果可以提供 Demo 更好。

**Comment by Ailix** [comment]
基本找到问题
暂时的解决方案:
```
    YTKNetworkAgent *agent = [YTKNetworkAgent sharedInstance];
    [agent setValue:[NSSet setWithObjects:@"application/json", @"text/plain", @"text/javascript", @"text/json",@"text/html", nil]
         forKeyPath:@"_manager.responseSerializer.acceptableContentTypes"];
```

**Comment by lancy** [comment]
如果后端返回的结果不是"application/json"，afn 的 jsonResponseSerializer 是不认的。
解决方法可以是客户端改一下，如 @Ailix 所言；
或者是让后端返回的结果符合标准
