### ISSUE TITLE
请问如何处理请求在外面飞的情况

### ISSUE THREAD

**Issue by wulie88** [yuantiku/YTKNetwork#87]
具体是上一个界面还在请求数据，打开了下一个界面，如何取消上一个界面的所有请求，保证当前页面快速显示处理？或者有更好的网络质量管理方案。

**Comment by xserver** [comment]
目前YTKNetwork 只提供了一个 Agent，库本身不支持你的需求。
@interface YTKRequest : YTKBaseRequest 提供了 stop 方法。
你可以把这个页面的 request add array，自己手动执行 [request stop]。

**Comment by wulie88** [comment]
我目前也是采用这种方案，但觉得不够强壮。

每个controller 对应一个 APICilent ，维护一个 Request Array，由 viewWillAppear  viewWillDisapper dealoc 来触发控制，分别处理 Wifi 和 3G/2G 的请求控制策略。

再就是图片了。
