### ISSUE TITLE
jsonValidator 数据合理性检查只能检查一层，不能嵌套检查

### ISSUE THREAD

**Issue by nilsun** [yuantiku/YTKNetwork#88]
![image](https://cloud.githubusercontent.com/assets/6940201/8061176/31df3040-0efc-11e5-8000-20ec3a577410.png)

这个函数返回的太早了

举个例子，下面的返回结果只检查了 response_header 就返回了；比如说paginator 里面再嵌套一些数组，字典，根本检查不到；我觉得 jsonValidator 的设计不是这样吧
response =     { 
     paginator =         {
         page = NSNumber;
         pageSize = NSNumber;
         totalPage = NSNumber;
         totalResult = NSNumber;
     };
    "response_header" =     {
        command = NSNumber;
        "error_info" = NSString;
        "sequence_id" = NSNumber;
        status = NSString;
    };
}

**Comment by tangqiaoboy** [comment]
好象是我的bug。。。。我写个 test case 检查一下。稍后回复。

**Comment by tangqiaoboy** [comment]
已经修复，另外加了一些test case，谢谢 @nilsun
