### ISSUE TITLE
能否放出并发数的设置接口，方便调用方在不同的网络情况下改变并发数

### ISSUE THREAD

**Issue by s6530085** [yuantiku/YTKNetwork#92]
目前在YTKNetworkAgent里由内部成员变量写死为4，无法在外部设置
_manager.operationQueue.maxConcurrentOperationCount = 4;

**Comment by maojj** [comment]
类似需求反馈比较少，你可以考虑fork后，自己修改下，满足特定的需求。如果类似需求比较多，可以再发pullRequest。
