### ISSUE TITLE
设置按时间缓存的时候，会回调2次呀

### ISSUE THREAD

**Issue by BaiCanLin** [yuantiku/YTKNetwork#95]
设置按时间缓存的时候，会回调2次呀，如果需要设置 UI，那么一个控件需要设置2次的吗？
    NSString *userId = @"1";
    GetUserInfoApi *api = [[GetUserInfoApi alloc] initWithUserId:userId];
    if ([api cacheJson]) {
        NSDictionary *json = [api cacheJson];
        NSLog(@"json = %@", json);
        // show cached data
    }
    [api startWithCompletionBlockWithSuccess:^(YTKBaseRequest *request) {
        NSLog(@"update ui %@",request.responseJSONObject);
    } failure:^(YTKBaseRequest *request) {
        NSLog(@"failed");
    }];

**Comment by BaiCanLin** [comment]
而且回调2次，转换模型很麻烦呀

**Comment by lancy** [comment]
我们这边没有这样的问题，能否提供一个 Demo ？
