### ISSUE TITLE
支持SSL 认证

### ISSUE THREAD

**Issue by jiangwenju** [yuantiku/YTKNetwork#96]
如何在不改变源码的基础上，支持ssl 认证 可以使用https 访问请求

**Comment by liangang** [comment]
我改了源码，实现了

**Comment by JessieHu** [comment]
@jiangwenju 
我也遇到了这个问题，请问你解决了么？
如果解决了，能告诉我解决方案么？

**Comment by jiangwenju** [comment]
请问 您的 ssl证书  是花钱买的 还是 自签名？                             原始邮件                             发件人: JessieHu<notifications@github.com>收件人: yuantiku/YTKNetwork<YTKNetwork@noreply.github.com>抄送: jiangwenju<jiangwenjun@ayibang.com>发送时间: 2015年10月14日(周三) 16:14主题: Re: [YTKNetwork] 支持SSL 认证 (#96)@jiangwenju 
我也遇到了这个问题，请问你解决了么？
如果解决了，能告诉我解决方案么？

**Comment by xiaoer371** [comment]
@JessieHu  @jiangwenju 
![222](https://cloud.githubusercontent.com/assets/7375120/11056323/c2d6055a-87bb-11e5-97ff-1dc079ba19a5.png)

**Comment by maojj** [comment]
fixed 
https://github.com/yuantiku/YTKNetwork/blob/master/YTKNetwork/YTKNetworkAgent.m#L51
```
        _manager.securityPolicy = _config.securityPolicy;
```
